"""MarginMap Phase 4C (slice 2) — AO-02 Contribution by Discount Band.

Scope (per docs/PHASE_4C_ANALYTICAL_INTERPRETATION_DESIGN.md, AO-02):
  ONE observed-baseline Overall x Discount Band reading. ORDER-basis rows
  carry authoritative contribution; LINE-basis companion rows are labeled
  partials beside — never instead of — the ORDER rows. No scenarios, no
  order detail, no visuals, no forecasts, no causal claims. Every figure
  below is an observed historical fact, a derived reference, or a modeled
  estimate conditional on the frozen benchmark structure, with
  return/support OFF (zero means scenario-excluded, never actual cost).

Inputs (READ-ONLY — never modified, never regenerated by this script):
    data/processed/discount_band_summary.csv    (14 rows; primary source:
                                                 ORDER band rows B0-B5 plus
                                                 TOTAL; LINE companions)
    data/processed/order_margin_map_phase2.csv (5,009 rows; independent
                                                 TOTAL cross-check)
    data/processed/fact_margin_map_phase2.csv  (9,994 rows; independent
                                                 count/quantity cross-check)

Outputs (NEW files only; written after every validation check passes):
    data/processed/phase4c_band_contribution.csv
    data/processed/phase4c_band_contribution_quality.json

Usage (all paths have frozen defaults; overrides exist ONLY so that
missing/invalid-input behavior can be tested without touching frozen files):
    python src/data/build_phase4c_band_contribution.py

Rules (frozen definitions restated — not redefined):
    bands group hypothetical-free observed values only (baseline order-WAD
    bands, D3B-03 rule; never re-banded); margins are SUM/SUM on net
    revenue; WAD is gross-revenue-weighted; averaging percentages is
    forbidden (verified by recomputation); below-order-grain contribution
    does not exist (LINE rows are partials with the stated gap).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
BAND_CSV = ROOT / "data" / "processed" / "discount_band_summary.csv"
ORDER_CSV = ROOT / "data" / "processed" / "order_margin_map_phase2.csv"
LINE_CSV = ROOT / "data" / "processed" / "fact_margin_map_phase2.csv"
OUT_DIR = ROOT / "data" / "processed"
OUT_CSV_NAME = "phase4c_band_contribution.csv"
OUT_JSON_NAME = "phase4c_band_contribution_quality.json"

# ---- frozen expectations (Phase 2 / Phase 3B freeze records) ------------------
EXPECTED_BAND_ROWS = 14
EXPECTED_LINES = 9994
EXPECTED_ORDERS = 5009
EXPECTED_QTY = 37873
EXPECTED_CONTRIB = 565116.9418
EXPECTED_LINE_GAP = 200.0476  # ORDER TOTAL minus LINE partial TOTAL
BAND_ORDER = ["B0", "B1", "B2", "B3", "B4", "B5", "TOTAL"]
BASIS_ORDER = ["ORDER", "LINE"]
EXPECTED_ORDER_COUNTS = {"B0": 2055, "B1": 415, "B2": 1634, "B3": 278,
                         "B4": 274, "B5": 353}
EXPECTED_NEG_ORDERS = {"B0": 14, "B1": 3, "B2": 24, "B3": 1, "B4": 3,
                       "B5": 5, "TOTAL": 50}
TOL = 0.05  # currency tolerance for source-total reconciliation only
RATIO_TOL = 1e-6  # SUM/SUM and WAD recomputation tolerance
MARGIN_TOL = 1e-6

# ---- frozen input hashes (all prior freeze records) ---------------------------
FROZEN_HASHES = {
    "discount_band_summary.csv":
        "ad8f7e571c76f295bde3cb119bca4b7ff56c7b3e1734869ebf60f8d7e3c236eb",
    "order_margin_map_phase2.csv":
        "ae6c349c9995747f2fef91cf1db6b940a73d99d6b2fede5ff3dff918f429d267",
    "fact_margin_map_phase2.csv":
        "4c471feeda642e5ecbd2263782b4fc0f1655962f6c6488bdfe47886df2f01cb1",
}

QUARANTINE_COL = "source_profit_quarantined"
OUTPUT_NAME = "Contribution by discount band (observed, ORDER basis)"
SCENARIO_STATUS = "OBSERVED BASELINE"
GRAIN = "Overall x discount band"

REQUIRED_BAND_COLS = {"basis", "band", "line_count", "order_count", "quantity",
                      "gross_revenue", "net_revenue", "discount_amount", "wad",
                      "discount_amount_pct_of_gross", "revenue_realization_rate",
                      "modeled_gross_profit", "modeled_gross_margin_pct",
                      "freight_cost", "cost_to_serve", "contribution_profit",
                      "contribution_margin_pct", "neg_contribution_orders",
                      "neg_contribution_lines", "contribution_authority",
                      "low_sample_flag"}


def fail(check: str, expected: str, actual: str) -> "NoReturn":
    raise SystemExit(
        f"VALIDATION FAILED [{check}]\n  Expected: {expected}\n  Actual:   {actual}"
    )


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Phase 4C slice 2: AO-02 contribution by discount band.")
    p.add_argument("--band-csv", type=Path, default=BAND_CSV)
    p.add_argument("--order-csv", type=Path, default=ORDER_CSV)
    p.add_argument("--line-csv", type=Path, default=LINE_CSV)
    p.add_argument("--out-dir", type=Path, default=OUT_DIR)
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    band_csv, order_csv, line_csv = args.band_csv, args.order_csv, args.line_csv
    out_dir = args.out_dir

    # ---- 1. source-artifact identity (fail-loud before any further I/O) --------
    for label, path in (("band summary", band_csv), ("order fact", order_csv),
                        ("line fact", line_csv)):
        if not path.is_file():
            fail("inputs-exist", f"{label} present at {path}", "file missing")

    hashes = {name: sha256(p) for name, p in
              (("discount_band_summary.csv", band_csv),
               ("order_margin_map_phase2.csv", order_csv),
               ("fact_margin_map_phase2.csv", line_csv))}
    for name, digest in hashes.items():
        if digest != FROZEN_HASHES[name]:
            fail("frozen-inputs", FROZEN_HASHES[name], digest)

    # ---- 2. load -----------------------------------------------------------------
    bands = pd.read_csv(band_csv)
    orders = pd.read_csv(order_csv)
    if QUARANTINE_COL in bands.columns:
        fail("quarantine", f"{QUARANTINE_COL} absent from band summary",
             "quarantine column present")
    if REQUIRED_BAND_COLS - set(bands.columns):
        fail("band-schema", f"band columns {sorted(REQUIRED_BAND_COLS)}",
             f"columns {list(bands.columns)}")
    if len(bands) != EXPECTED_BAND_ROWS:
        fail("inputs", f"{EXPECTED_BAND_ROWS} band rows", f"{len(bands)} rows")
    if len(orders) != EXPECTED_ORDERS or orders["order_id"].nunique() != EXPECTED_ORDERS:
        fail("inputs", f"{EXPECTED_ORDERS} unique orders",
             f"{len(orders)} rows / {orders['order_id'].nunique()} unique")
    line_head = pd.read_csv(line_csv, nrows=0)
    if QUARANTINE_COL not in line_head.columns:
        fail("quarantine", f"{QUARANTINE_COL} present-but-excluded in line fact",
             "quarantine column missing from input")

    # ---- 3. block completeness (ORDER + LINE, B0-B5 + TOTAL) -----------------------
    blocks: dict[str, pd.DataFrame] = {}
    for basis in BASIS_ORDER:
        block = bands[bands["basis"] == basis].copy()
        if [str(b) for b in block["band"]] != BAND_ORDER:
            fail("band-coverage", f"{basis} bands {BAND_ORDER}",
                 repr([str(b) for b in block["band"]]))
        blocks[basis] = block.reset_index(drop=True)

    # ---- 4. authority markers -------------------------------------------------------
    if not bool((blocks["ORDER"]["contribution_authority"]
                 == "AUTHORITATIVE_ORDER").all()):
        fail("authority", "ORDER rows AUTHORITATIVE_ORDER",
             repr(blocks["ORDER"]["contribution_authority"].unique().tolist()))
    if not bool((blocks["LINE"]["contribution_authority"]
                 == "LINE_PARTIAL_EXCL_AMBIGUOUS").all()):
        fail("authority", "LINE rows LINE_PARTIAL_EXCL_AMBIGUOUS",
             repr(blocks["LINE"]["contribution_authority"].unique().tolist()))

    # ---- 5. flags preserved (provisional 30-line / 10-order thresholds) --------------
    if bool(blocks["ORDER"]["low_sample_flag"].fillna(False).any()) or \
            bool(blocks["LINE"]["low_sample_flag"].fillna(False).any()):
        fail("flags", "low_sample_flag FALSE on all 14 band rows",
             "TRUE flag found")

    # ---- 6. per-basis totals reconcile (band rows sum to TOTAL) ----------------------
    for basis, block in blocks.items():
        detail = block[block["band"] != "TOTAL"]
        total = block[block["band"] == "TOTAL"].iloc[0]
        # NOTE: LINE-basis order_counts overlap across bands (multi-band
        # orders), so they must not be summed; ORDER-basis counts partition
        # orders exactly (D3B-03 single rule).
        count_cols = ("line_count", "order_count", "quantity") \
            if basis == "ORDER" else ("line_count", "quantity")
        for col in count_cols + ("gross_revenue",
                                 "net_revenue", "discount_amount", "freight_cost",
                                 "cost_to_serve", "contribution_profit"):
            if abs(float(detail[col].sum()) - float(total[col])) > TOL:
                fail("band-totals-reconcile",
                     f"{basis} {col} bands sum to TOTAL",
                     f"sum={float(detail[col].sum())!r} total={float(total[col])!r}")
        if int(detail["order_count"].sum()) != EXPECTED_ORDERS and basis == "ORDER":
            fail("band-totals-reconcile", f"ORDER counts sum to {EXPECTED_ORDERS}",
                 str(int(detail["order_count"].sum())))

    order_total = blocks["ORDER"][blocks["ORDER"]["band"] == "TOTAL"].iloc[0]
    line_total = blocks["LINE"][blocks["LINE"]["band"] == "TOTAL"].iloc[0]

    # ---- 7. authoritative TOTAL + LINE gap ---------------------------------------------
    if abs(float(order_total["contribution_profit"]) - EXPECTED_CONTRIB) > TOL:
        fail("authoritative-total", f"contribution {EXPECTED_CONTRIB} +/- {TOL}",
             repr(float(order_total["contribution_profit"])))
    gap = float(order_total["contribution_profit"]) - float(line_total["contribution_profit"])
    if abs(gap - EXPECTED_LINE_GAP) > TOL:
        fail("line-gap", f"ORDER minus LINE = {EXPECTED_LINE_GAP} +/- {TOL}",
             repr(gap))

    # ---- 8. ratio discipline (recomputed, never averaged) --------------------------------
    for basis, block in blocks.items():
        for _, r in block.iterrows():
            net, contrib = float(r["net_revenue"]), float(r["contribution_profit"])
            if abs(contrib / net * 100 - float(r["contribution_margin_pct"])) > MARGIN_TOL:
                fail("margins-recomputed", f"{basis} {r['band']} SUM/SUM margin",
                     repr(float(r["contribution_margin_pct"])))
            if abs(float(r["discount_amount"]) / float(r["gross_revenue"])
                   - float(r["wad"])) > RATIO_TOL:
                fail("wad-recomputed", f"{basis} {r['band']} gross-weighted WAD",
                     repr(float(r["wad"])))
            gp = float(r["modeled_gross_profit"])
            if abs(gp / net * 100 - float(r["modeled_gross_margin_pct"])) > MARGIN_TOL:
                fail("margins-recomputed", f"{basis} {r['band']} gross margin",
                     repr(float(r["modeled_gross_margin_pct"])))

    # ---- 9. negative-order distribution + independent fact cross-checks --------------------
    for band, expected in EXPECTED_NEG_ORDERS.items():
        actual = blocks["ORDER"][blocks["ORDER"]["band"] == band][
            "neg_contribution_orders"].iloc[0]
        if int(float(actual)) != expected:
            fail("negatives", f"ORDER {band} neg orders {expected}", repr(actual))
    if int((orders["order_contribution_profit"] < 0).sum()) != 50:
        fail("negatives", "order fact neg orders 50",
             str(int((orders["order_contribution_profit"] < 0).sum())))
    if abs(float(orders["order_contribution_profit"].sum()) - EXPECTED_CONTRIB) > TOL:
        fail("order-fact-crosscheck", f"order contrib {EXPECTED_CONTRIB}",
             repr(float(orders["order_contribution_profit"].sum())))
    if abs(float(orders["order_revenue"].sum()) - float(order_total["net_revenue"])) > TOL:
        fail("order-fact-crosscheck", "order revenue = ORDER TOTAL net",
             repr(float(orders["order_revenue"].sum())))
    if abs(float(orders["order_freight"].sum()) - float(order_total["freight_cost"])) > TOL:
        fail("order-fact-crosscheck", "order freight = ORDER TOTAL freight",
             repr(float(orders["order_freight"].sum())))
    line_qty_frame = pd.read_csv(line_csv, usecols=["quantity"])
    if len(line_qty_frame) != EXPECTED_LINES:
        fail("inputs", f"{EXPECTED_LINES} lines", f"{len(line_qty_frame)} lines")
    line_qty = line_qty_frame["quantity"].sum()
    if int(line_qty) != EXPECTED_QTY or int(line_qty) != int(order_total["quantity"]):
        fail("order-fact-crosscheck", f"quantity {EXPECTED_QTY}",
             f"line fact {int(line_qty)} / ORDER TOTAL {order_total['quantity']!r}")
    for band, expected in EXPECTED_ORDER_COUNTS.items():
        actual = blocks["ORDER"][blocks["ORDER"]["band"] == band]["order_count"].iloc[0]
        if int(actual) != expected:
            fail("band-counts", f"ORDER {band} orders {expected}", repr(actual))
    # LINE neg lines (109) stay on their own grain; ORDER neg lines stay NULL.
    # TOTAL rows carry 0.0 counts on both grains by file convention; the NULL
    # discipline below applies to band detail rows (band != TOTAL).
    order_detail = blocks["ORDER"][blocks["ORDER"]["band"] != "TOTAL"]
    line_detail = blocks["LINE"][blocks["LINE"]["band"] != "TOTAL"]
    if int(float(line_total["neg_contribution_lines"])) != 109:
        fail("negatives", "LINE TOTAL neg lines 109",
             repr(float(line_total["neg_contribution_lines"])))
    if order_detail["neg_contribution_lines"].notna().any():
        fail("grain-consistency", "ORDER detail neg_contribution_lines all NULL",
             "non-NULL found")
    if line_detail["neg_contribution_orders"].notna().any():
        fail("grain-consistency", "LINE detail neg_contribution_orders all NULL",
             "non-NULL found")

    # ---- 10. build deterministic metric table --------------------------------------------
    B = "discount_band_summary.csv"
    O = "order_margin_map_phase2.csv"
    L = "fact_margin_map_phase2.csv"
    rows: list[dict[str, str]] = []

    def sval(value: object) -> str:
        if value is None:
            return ""
        if isinstance(value, float):
            if pd.isna(value):
                return ""
            return repr(value)
        return str(value)

    def add(basis: str, band: str, metric: str, value: object, unit: str,
            source: str, definition_ref: str, limitation: str) -> None:
        rows.append({
            "output_name": OUTPUT_NAME,
            "scenario_status": SCENARIO_STATUS,
            "grain": GRAIN,
            "basis": basis,
            "band": band,
            "source_artifact": source,
            "metric_name": metric,
            "metric_value": sval(value),
            "unit": unit,
            "definition_ref": definition_ref,
            "limitation": limitation,
        })

    ORDER_METRICS: list[tuple[str, str, str, str]] = [
        ("net_revenue", "CUR", "Net revenue (SUM); denominator for margins",
         "Authoritative; never subtract discount again"),
        ("gross_revenue", "CUR", "Gross revenue (SUM, derived reference)",
         "Derived reference only; never an observed list price"),
        ("discount_amount", "CUR", "Discount amount (SUM); revenue forgone",
         "Revenue forgone, not profit loss"),
        ("wad", "DEC", "WAD, gross-revenue-weighted; never averaged",
         "Never an arithmetic mean of rates"),
        ("revenue_realization_rate", "PCT", "Realization = net/gross x 100",
         "Complement of discount absorption"),
        ("modeled_gross_profit", "CUR", "Gross profit (SUM, conditional)",
         "Excludes serve costs; not contribution"),
        ("modeled_gross_margin_pct", "PCT", "Gross margin SUM/SUM on net",
         "Conditional on benchmarks; within-group constancy by construction"),
        ("freight_cost", "CUR", "Freight (SUM, observed join)",
         "Observed field, methodology unverified (Phase 2 caveat)"),
        ("cost_to_serve", "CUR", "Serve cost (SUM; return/support OFF)",
         "Zero means scenario-excluded, never actual cost"),
        ("contribution_profit", "CUR", "Contribution (SUM, authoritative)",
         "Authoritative at order grain and above; OFF baseline"),
        ("contribution_margin_pct", "PCT", "Contribution margin SUM/SUM on net",
         "Denominator net revenue, never gross"),
        ("quantity", "CT", "Quantity (SUM, co-occurrence context)",
         "Compares compositions; isolates no influence"),
        ("order_count", "CT", "Order count (sample-size companion)",
         "Part of the output; drives low_sample_flag"),
        ("line_count", "CT", "Line count (sample-size companion)",
         "Part of the output; drives low_sample_flag"),
        ("neg_contribution_orders", "CT", "Negative-contribution orders",
         "Preserved with flags and summed, never averaged away"),
        ("low_sample_flag", "Flag", "Thin-cell marker (30 lines / 10 orders)",
         "Provisional analytical thresholds; all 14 band rows FALSE"),
    ]
    NA_ORDER_LINE = ("N/A at LINE partial grain (not licensed); "
                     "see neg_contribution_lines on the LINE block")
    NA_LINE_ORDER = ("N/A at ORDER authoritative grain (detail rows); "
                     "see neg_contribution_orders on the ORDER block; "
                     "TOTAL-row zeros are file convention, not licensed detail")

    for basis in BASIS_ORDER:
        block = blocks[basis]
        authority = ("AUTHORITATIVE_ORDER: authoritative contribution"
                     if basis == "ORDER"
                     else "LINE_PARTIAL_EXCL_AMBIGUOUS: partial beside — never "
                          "instead of — the authoritative ORDER rows (gap 200.0476)")
        for _, r in block.iterrows():
            band = str(r["band"])
            for metric, unit, definition_ref, limitation in ORDER_METRICS:
                if metric == "neg_contribution_orders" and basis == "LINE":
                    add(basis, band, metric, None, "CT", B, definition_ref,
                        NA_ORDER_LINE)
                    continue
                if metric == "low_sample_flag":
                    add(basis, band, metric, str(bool(r[metric])), "Flag", B,
                        definition_ref, limitation)
                    continue
                value = r[metric]
                lim = limitation + "; " + authority if metric in (
                    "contribution_profit", "contribution_margin_pct") else limitation
                add(basis, band, metric, value, unit, B, definition_ref, lim)
            if basis == "ORDER":
                add(basis, band, "neg_contribution_lines", None, "CT", B,
                    "Negative-contribution lines (LINE partial grain only)",
                    NA_LINE_ORDER)
            if basis == "LINE":
                add(basis, band, "neg_contribution_lines",
                    r["neg_contribution_lines"], "CT", B,
                    "Negative-contribution lines (LINE partial grain)",
                    "Partial view; 109 LINE TOTAL vs 50 orders — grains differ")

    out_csv = out_dir / OUT_CSV_NAME
    out_json = out_dir / OUT_JSON_NAME

    # ---- 11. write outputs only after every check passed -----------------------------------
    out_dir.mkdir(parents=True, exist_ok=True)
    import csv as _csv
    with open(out_csv, "w", newline="", encoding="utf-8") as f:
        w = _csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    quality = {
        "phase": "4C slice 2 — AO-02 contribution by discount band (observed baseline; not a forecast)",
        "output": {
            "output_name": OUTPUT_NAME,
            "scenario_status": SCENARIO_STATUS,
            "grain": GRAIN,
            "standing": "OBSERVED_BASELINE",
        },
        "inputs": {
            "discount_band_summary.csv": {"rows": len(bands),
                                          "sha256": hashes["discount_band_summary.csv"]},
            "order_margin_map_phase2.csv": {"rows": len(orders),
                                            "sha256": hashes["order_margin_map_phase2.csv"]},
            "fact_margin_map_phase2.csv": {"rows": len(line_qty_frame),
                                           "sha256": hashes["fact_margin_map_phase2.csv"]},
        },
        "checks": [
            {"id": "inputs-exist", "description": "required frozen inputs present",
             "expected": "band + order + line files", "actual": "present", "status": "PASS"},
            {"id": "frozen-inputs", "description": "frozen hashes match records",
             "expected": "byte-identical SHA-256 (3 files)", "actual": "match", "status": "PASS"},
            {"id": "quarantine", "description": "quarantined Profit absent/excluded",
             "expected": "source_profit_quarantined in line fact but never loaded; absent from band summary",
             "actual": "excluded", "status": "PASS"},
            {"id": "inputs", "description": "frozen input shapes",
             "expected": "14 band rows / 5009 unique orders",
             "actual": f"{len(bands)} band rows / {orders['order_id'].nunique()} orders", "status": "PASS"},
            {"id": "band-schema", "description": "band summary schema complete",
             "expected": "all 21 required columns", "actual": "present", "status": "PASS"},
            {"id": "band-coverage", "description": "ORDER + LINE blocks, B0-B5 + TOTAL",
             "expected": "7 rows per basis in band order", "actual": "complete", "status": "PASS"},
            {"id": "authority", "description": "authority markers correct per basis",
             "expected": "ORDER AUTHORITATIVE_ORDER; LINE LINE_PARTIAL_EXCL_AMBIGUOUS",
             "actual": "correct", "status": "PASS"},
            {"id": "flags", "description": "low_sample_flag preserved (all FALSE)",
             "expected": "FALSE on all 14 rows", "actual": "all FALSE", "status": "PASS"},
            {"id": "band-totals-reconcile", "description": "per-basis bands sum to TOTAL",
             "expected": "counts/quantity/currency reconciled within 0.05",
             "actual": "reconciled", "status": "PASS"},
            {"id": "authoritative-total", "description": "ORDER TOTAL contribution authoritative",
             "expected": f"{EXPECTED_CONTRIB} +/- {TOL}",
             "actual": repr(float(order_total['contribution_profit'])), "status": "PASS"},
            {"id": "line-gap", "description": "LINE partial gap stated",
             "expected": f"ORDER minus LINE = {EXPECTED_LINE_GAP} +/- {TOL}",
             "actual": repr(gap), "status": "PASS"},
            {"id": "margins-recomputed", "description": "margins recomputed SUM/SUM (never averaged)",
             "expected": f"gaps <= {MARGIN_TOL} on all 14 rows", "actual": "recomputed", "status": "PASS"},
            {"id": "wad-recomputed", "description": "WAD recomputed gross-weighted (never averaged)",
             "expected": f"gaps <= {RATIO_TOL} on all 14 rows", "actual": "recomputed", "status": "PASS"},
            {"id": "negatives", "description": "negative-order distribution + order-fact count",
             "expected": "B0 14 / B1 3 / B2 24 / B3 1 / B4 3 / B5 5 / TOTAL 50; fact 50",
             "actual": "match", "status": "PASS"},
            {"id": "order-fact-crosscheck", "description": "ORDER TOTAL vs order/line facts",
             "expected": "contribution/revenue/freight/quantity/counts match",
             "actual": "match", "status": "PASS"},
            {"id": "band-counts", "description": "ORDER band order counts frozen",
             "expected": "B0 2055 / B1 415 / B2 1634 / B3 278 / B4 274 / B5 353",
             "actual": "match", "status": "PASS"},
            {"id": "grain-consistency", "description": "neg-count NULL discipline per basis (detail rows)",
             "expected": "ORDER detail neg lines NULL; LINE detail neg orders NULL",
             "actual": "consistent", "status": "PASS"},
        ],
        "limitations": [
            "Conditional on revenue-based modeled COGS benchmarks.",
            "Return/support OFF (zero means excluded); return status not used.",
            "Freight methodology caveat carried from Phase 2.",
            "Descriptive comparison only; no causal attribution.",
            "LINE block is partial (gap 200.0476); authoritative reading is ORDER.",
        ],
        "failure_behavior": [
            "Missing file fails [inputs-exist] before any I/O beyond existence checks.",
            "Hash mismatch fails [frozen-inputs] before loading.",
            "Wrong schema fails [band-schema]; no partial output is written.",
            "Any failed check raises VALIDATION FAILED and writes no output files.",
        ],
        "determinism": "Fixed basis/band/metric ordering, repr() numeric formatting, no timestamps, no randomness, no environment-dependent values.",
        "outputs": {
            OUT_CSV_NAME: {"rows": len(rows), "sha256": sha256(out_csv)},
        },
    }
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(quality, f, indent=2)
        f.write("\n")
    quality["outputs"][OUT_CSV_NAME]["sha256"] = sha256(out_csv)
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(quality, f, indent=2)
        f.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
