"""MarginMap Phase 3B — observed discount impact analysis (descriptive only).

Inputs (READ-ONLY — never modified, never regenerated by this script):
    data/processed/fact_margin_map_phase2.csv    (line grain, 9,994 rows)
    data/processed/order_margin_map_phase2.csv   (order grain, 5,009 rows;
                                                 authoritative contribution)
    data/processed/fact_sales_cogs.csv           (Phase 1 cross-check only)

Outputs (NEW files only):
    data/processed/discount_band_summary.csv
    data/processed/discount_segment_summary.csv
    data/processed/discount_category_summary.csv
    data/processed/discount_subcategory_summary.csv
    data/processed/discount_customer_summary.csv
    data/processed/discount_order_summary.csv
    data/processed/discount_product_summary.csv
    data/processed/phase3b_quality_report.json

Design authority: docs/PHASE_3A_DISCOUNT_PRICING_ARCHITECTURE.md and the
Phase 3B decision log (docs/PHASE_3B_DECISION_LOG.md). Decisions implemented:
  D3B-01  fixed six-band structure B0..B5 (adopted after validation)
  D3B-02  provisional thresholds: minimum_line_count = 30,
          minimum_order_count = 10 (analytical thresholds, not statistics)
  D3B-03  order band = order WAD band (single rule; no competing rule)
  D3B-04  no quantile comparator in this phase
  D3B-05  product x band file created as flagged reference only
  D3B-06  contribution authority: order/customer authoritative; product /
          category / sub-category gross-profit-only (NULL contribution)

Formulas (frozen Phase 1A definitions, restated — not redefined):
    net_revenue              = sales
    gross_revenue            = sales / (1 - discount)   [NULL if discount = 1]
    discount_amount          = gross_revenue - net_revenue
    wad (any aggregate)      = SUM(discount_amount) / SUM(gross_revenue)
    realization_rate         = SUM(net_revenue) / SUM(gross_revenue) * 100
    order_wad                = SUM(line discount_amount)
                               / SUM(line gross_revenue)  (per order)
    gross_profit / margin    = frozen modeled values, SUM / SUM-on-net
    contribution (order +)   = joined authoritative order-fact values only

Restrictions enforced in code (fail-loud):
  - frozen inputs hashed before AND after the run; any change aborts
  - discounts restricted to [0, 1); NULL / negative / >= 1 aborts
  - quarantined source Profit column is never loaded and never referenced
  - scenarios asserted OFF in the line input (enabled flags FALSE, costs 0)
  - ambiguous freight pair never imputed (NULL + flagged preserved)
  - no elasticity estimation, no scenarios, no quantity-response assumptions
  - deterministic output (sorted keys, no randomness)

The observed band-quantity patterns reported here are descriptive
associations in historical data. They are not estimates of demand response
and must not be read as proof that discounts moved quantities.

Run from the project root:
    python src/data/build_phase3b_discount_analysis.py
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
LINE_CSV = ROOT / "data" / "processed" / "fact_margin_map_phase2.csv"
ORDER_CSV = ROOT / "data" / "processed" / "order_margin_map_phase2.csv"
FACT1_CSV = ROOT / "data" / "processed" / "fact_sales_cogs.csv"
OUT = ROOT / "data" / "processed"

# ---- frozen baseline expectations (Phase 1 / Phase 2 freeze records) --------
EXPECTED_LINES = 9994
EXPECTED_ORDERS = 5009
EXPECTED_REV = 2297200.8603
EXPECTED_COGS = 1493910.1285
EXPECTED_FREIGHT = 238173.79
EXPECTED_CONTRIB = 565116.9418
TOL = 0.05

# ---- Phase 3B configuration (provisional analytical thresholds) -------------
BAND_ORDER = ["B0", "B1", "B2", "B3", "B4", "B5"]
BAND_LABEL = {
    "B0": "No discount",
    "B1": "Low discount",
    "B2": "Standard discount",
    "B3": "Elevated discount",
    "B4": "High discount",
    "B5": "Deep discount",
}
MIN_LINE_COUNT = 30    # provisional analytical threshold (D3B-02)
MIN_ORDER_COUNT = 10   # provisional analytical threshold (D3B-02)

QUARANTINE_COL = "source_profit_quarantined"
NULL_REASON_BELOW_ORDER_GRAIN = "FREIGHT_NOT_ATTRIBUTABLE_BELOW_ORDER_GRAIN"


def fail(check: str, expected: str, actual: str) -> "NoReturn":
    raise SystemExit(
        f"VALIDATION FAILED [{check}]\n  Expected: {expected}\n  Actual:   {actual}"
    )


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def assign_band(d: float) -> str | None:
    """Fixed six-band mapping (D3B-01). Returns None when unassignable."""
    if d is None or (isinstance(d, float) and np.isnan(d)):
        return None
    if d == 0:
        return "B0"
    if 0 < d <= 0.15:
        return "B1"
    if 0.15 < d <= 0.25:
        return "B2"
    if 0.25 < d <= 0.35:
        return "B3"
    if 0.35 < d <= 0.55:
        return "B4"
    if 0.55 < d <= 0.80:
        return "B5"
    return None


def summarize_frame(g: pd.DataFrame, by: list[str]) -> pd.DataFrame:
    """Descriptive cell aggregation shared by line-basis summaries."""
    agg = g.groupby(by, sort=True).agg(
        line_count=("row_id", "size"),
        order_count=("order_id", "nunique"),
        quantity=("quantity", "sum"),
        gross_revenue=("gross_revenue", "sum"),
        net_revenue=("net_revenue", "sum"),
        discount_amount=("discount_amount", "sum"),
        modeled_cogs=("modeled_cogs", "sum"),
        modeled_gross_profit=("modeled_gross_profit", "sum"),
        line_freight_partial=("freight_cost_observed", "sum"),
        line_contribution_partial=("contribution_profit", "sum"),
        neg_grossprofit_lines=("modeled_gross_profit", lambda s: int((s < 0).sum())),
        neg_contribution_lines=("contribution_profit",
                                lambda s: int((s.fillna(1) < 0).sum())),
    ).reset_index()
    return agg


def finalize_rates(df: pd.DataFrame) -> pd.DataFrame:
    df["wad"] = np.where(df["gross_revenue"] == 0, np.nan,
                         df["discount_amount"] / df["gross_revenue"])
    df["discount_amount_pct_of_gross"] = df["wad"] * 100.0
    df["revenue_realization_rate"] = np.where(
        df["gross_revenue"] == 0, np.nan,
        df["net_revenue"] / df["gross_revenue"] * 100.0)
    df["modeled_gross_margin_pct"] = np.where(
        df["net_revenue"] == 0, np.nan,
        df["modeled_gross_profit"] / df["net_revenue"] * 100.0)
    df["quantity_per_order"] = np.where(
        df["order_count"] == 0, np.nan, df["quantity"] / df["order_count"])
    df["quantity_per_line"] = np.where(
        df["line_count"] == 0, np.nan, df["quantity"] / df["line_count"])
    df["low_sample_flag"] = ((df["line_count"] < MIN_LINE_COUNT)
                             | (df["order_count"] < MIN_ORDER_COUNT))
    return df


def main() -> None:
    checks: list[dict] = []

    def record(check_id: str, description: str, expected: str, actual: str,
               status: str = "PASS") -> None:
        checks.append({"id": check_id, "description": description,
                       "expected": expected, "actual": actual, "status": status})

    for p in [LINE_CSV, ORDER_CSV, FACT1_CSV]:
        if not p.is_file():
            fail("input-exists", f"file at {p}", "NOT FOUND")
    line_hash_before = sha256(LINE_CSV)
    order_hash_before = sha256(ORDER_CSV)
    fact1_hash_before = sha256(FACT1_CSV)

    # ---- load (quarantined Profit column never loaded) ----------------------
    line_cols = pd.read_csv(LINE_CSV, nrows=0).columns.tolist()
    if QUARANTINE_COL in line_cols:
        use_cols = [c for c in line_cols if c != QUARANTINE_COL]
    else:
        use_cols = None
    e = pd.read_csv(LINE_CSV, usecols=use_cols, dtype={"postal_code": str})
    o = pd.read_csv(ORDER_CSV)
    f1 = pd.read_csv(FACT1_CSV, usecols=["row_id", "order_id", "sales",
                                        "quantity", "discount", "net_revenue",
                                        "modeled_cogs", "modeled_gross_profit"],
                     dtype={"row_id": int})
    if QUARANTINE_COL in e.columns or QUARANTINE_COL in o.columns:
        fail("quarantine-excluded", f"{QUARANTINE_COL} absent from working frames",
             "column present")
    record("quarantine", "quarantined Profit excluded from computations",
           f"{QUARANTINE_COL} never loaded", "excluded", "PASS")

    # ---- frozen input shape / identity --------------------------------------
    if len(e) != EXPECTED_LINES:
        fail("input-lines", f"{EXPECTED_LINES} lines", f"{len(e)}")
    if len(o) != EXPECTED_ORDERS or o["order_id"].nunique() != EXPECTED_ORDERS:
        fail("input-orders", f"{EXPECTED_ORDERS} unique orders",
             f"{len(o)} rows / {o['order_id'].nunique()} unique")
    if e["row_id"].nunique() != EXPECTED_LINES:
        fail("row-unique", f"{EXPECTED_LINES} unique row_id",
             f"{e['row_id'].nunique()}")
    if set(f1["row_id"]) != set(e["row_id"]):
        fail("phase1-rowset", "Phase 1 cross-check row set identical", "mismatch")
    m = f1.set_index("row_id")
    n = e.set_index("row_id")
    if abs(float((m["sales"] - n["sales"]).abs().max())) > 1e-6:
        fail("phase1-sales", "Phase 1 sales identical per row", "mismatch")
    if abs(float((m["modeled_cogs"] - n["modeled_cogs"]).abs().max())) > 1e-6:
        fail("phase1-cogs", "Phase 1 modeled COGS identical per row", "mismatch")
    record("inputs", "frozen input shapes and Phase 1 cross-check",
           "9994 lines / 5009 orders / Phase 1 sales+COGS identical",
           f"{len(e)} lines / {len(o)} orders", "PASS")

    # ---- scenarios OFF --------------------------------------------------------
    if bool(e["return_processing_scenario_enabled"].any()) or \
            bool((e["return_processing_cost_scenario"] != 0).any()) or \
            bool(e["support_scenario_enabled"].any()) or \
            bool((e["support_cost_scenario"] != 0).any()):
        fail("scenarios-off", "return+support OFF/zero in line fact", "enabled")
    if bool((o["order_return_processing_cost_scenario"] != 0).any()) or \
            bool((o["order_support_cost_scenario"] != 0).any()):
        fail("scenarios-off-order", "return+support OFF/zero in order fact",
             "non-zero")
    record("scenarios", "pricing/return/support scenarios remain OFF",
           "all scenario flags FALSE and costs 0", "OFF confirmed", "PASS")

    # ---- discount range + ambiguity scope ------------------------------------
    if bool(e["discount"].isna().any()):
        fail("discount-range", "no NULL discounts",
             f"{int(e['discount'].isna().sum())} NULL")
    bad = e[(e["discount"] < 0) | (e["discount"] >= 1)]
    if len(bad):
        fail("discount-range", "all discounts within [0, 1)",
             f"{len(bad)} outside: {sorted(bad['discount'].unique().tolist())}")
    record("discount-range", "discount values within valid range",
           "[0, 1); no NULL", f"[{e['discount'].min()}, {e['discount'].max()}]",
           "PASS")

    ambig = e[e["freight_ambiguity_flag"]]
    if len(ambig) != 2 or ambig["order_id"].nunique() != 1:
        fail("ambiguity-scope", "exactly 2 flagged lines in one order",
             f"{len(ambig)} lines / {ambig['order_id'].nunique()} orders")
    if bool(ambig["freight_cost_observed"].notna().any()):
        fail("no-imputation", "flagged lines carry NULL freight", "value present")
    ambig_order = ambig["order_id"].iloc[0]
    record("ambiguity", "ambiguous freight pair preserved (NULL, flagged)",
           "2 lines NULL freight in one order",
           f"{len(ambig)} lines in {ambig_order}", "PASS")

    # ---- line-level derived discount measures ---------------------------------
    e = e.copy()
    e["discount_r"] = e["discount"].astype(float).round(6)
    e["net_revenue_check"] = e["sales"]
    if abs(float((e["net_revenue_check"] - e["net_revenue"]).abs().max())) > 1e-6:
        fail("net-equals-sales", "net_revenue == sales on every line", "mismatch")
    record("net", "Net Revenue equals Sales",
           "max |net - sales| <= 1e-6",
           f"{float((e['net_revenue_check'] - e['net_revenue']).abs().max()):.2e}",
           "PASS")

    e["gross_revenue"] = np.where(e["discount_r"] >= 1, np.nan,
                                  e["sales"] / (1.0 - e["discount_r"]))
    if bool(e["gross_revenue"].isna().any()):
        fail("gross-guard", "no Discount = 1 lines expected (guard exercised)",
             f"{int(e['gross_revenue'].isna().sum())} NULL gross")
    e["discount_amount"] = e["gross_revenue"] - e["net_revenue"]
    # dual-form reconciliation: Gross - Net vs Gross x Discount
    gap = float((e["discount_amount"]
                 - e["gross_revenue"] * e["discount_r"]).abs().max())
    if gap > 1e-6:
        fail("discount-dual", "Discount Amount dual forms reconcile", f"{gap}")
    record("discount-amount", "Discount Amount = Gross - Net (dual reconciled)",
           "max dual gap <= 1e-6", f"{gap:.2e}", "PASS")

    # ---- band assignment (D3B-01) ----------------------------------------------
    e["discount_band"] = e["discount_r"].map(assign_band)
    if bool(e["discount_band"].isna().any()):
        missing = sorted(e.loc[e["discount_band"].isna(), "discount_r"]
                         .unique().tolist())
        fail("band-coverage", "every valid line receives exactly one band",
             f"unassigned discount values: {missing}")
    band_counts = e["discount_band"].value_counts()
    if set(band_counts.index.tolist()) > set(BAND_ORDER):
        fail("band-labels", f"bands subset of {BAND_ORDER}",
             str(band_counts.index.tolist()))
    if int((e["discount_r"] == 0).sum()) != int((e["discount_band"] == "B0").sum()):
        fail("band-zero", "zero-discount group exactly preserved in B0",
             f"d=0: {(e['discount_r'] == 0).sum()} vs B0: "
             f"{(e['discount_band'] == 'B0').sum()}")
    # no observed value split across bands
    split = e.groupby("discount_r")["discount_band"].nunique()
    if bool((split != 1).any()):
        fail("band-integrity", "no discount value split across bands",
             str(split[split != 1].to_dict()))
    if int(band_counts.sum()) != EXPECTED_LINES:
        fail("band-reconcile", f"band counts sum to {EXPECTED_LINES}",
             f"{int(band_counts.sum())}")
    record("bands", "six-band assignment validated",
           "coverage 9994; B0 exact; no value split",
           " | ".join(f"{b}={int(band_counts.get(b, 0))}" for b in BAND_ORDER),
           "PASS")

    # ---- order-level rollups (D3B-03: single rule = order WAD band) ------------
    if bool(e.groupby("order_id")["customer_id"].nunique().max() != 1):
        fail("order-customer", "one customer per order", "violation")
    seg_per_order = e.groupby("order_id")["segment"].nunique()
    multi_seg = int((seg_per_order > 1).sum())
    if multi_seg:
        fail("order-segment", "orders single-segment (attribution clean)",
             f"{multi_seg} multi-segment orders")
    record("order-dims", "order dimensional attribution clean",
           "1 customer + 1 segment per order", "5009/5009 clean", "PASS")

    g = e.groupby("order_id", sort=True)
    oroll = pd.DataFrame({
        "line_count": g["row_id"].size(),
        "order_quantity": g["quantity"].sum(),
        "order_gross_revenue": g["gross_revenue"].sum(),
        "order_net_rollup": g["net_revenue"].sum(),
        "order_discount_amount": g["discount_amount"].sum(),
        "order_cogs_rollup": g["modeled_cogs"].sum(),
    }).reset_index()
    oroll["order_wad"] = (oroll["order_discount_amount"]
                          / oroll["order_gross_revenue"])
    oroll["order_discount_band"] = oroll["order_wad"].round(6).map(assign_band)
    if bool(oroll["order_discount_band"].isna().any()):
        fail("order-band-coverage", "every valid order receives exactly one band",
             f"{int(oroll['order_discount_band'].isna().sum())} unassigned")
    if len(oroll) != EXPECTED_ORDERS:
        fail("order-band-reconcile", f"order bands sum to {EXPECTED_ORDERS}",
             f"{len(oroll)}")
    record("order-bands", "order WAD band assignment (single rule)",
           "5009 orders exactly one band",
           " | ".join(f"{b}={int((oroll['order_discount_band'] == b).sum())}"
                      for b in BAND_ORDER), "PASS")

    # join authoritative contribution (order fact is the authority — D3B-06)
    odim = (e[["order_id", "customer_id", "customer_name", "segment"]]
            .drop_duplicates("order_id"))
    if len(odim) != EXPECTED_ORDERS:
        fail("order-dim-map", "one dim row per order", f"{len(odim)}")
    od = oroll.merge(odim, on="order_id", validate="one_to_one")
    od = od.merge(o, on="order_id", validate="one_to_one")
    if len(od) != EXPECTED_ORDERS:
        fail("order-join", "rollup x dims x order fact = 5009", f"{len(od)}")
    for col, tol in [("order_revenue", 1e-6), ("order_cogs", 1e-6)]:
        gapv = float((od[col] - od[col.replace("order_revenue", "order_net_rollup")
                                   .replace("order_cogs", "order_cogs_rollup")]
                      ).abs().max())
        if gapv > tol:
            fail("order-reconcile", f"rollup {col} matches order fact", f"{gapv}")
    if abs(float(od["order_revenue"].sum()) - EXPECTED_REV) > TOL:
        fail("frozen-rev", f"revenue {EXPECTED_REV}",
             f"{float(od['order_revenue'].sum())}")
    if abs(float(od["order_contribution_profit"].sum()) - EXPECTED_CONTRIB) > TOL:
        fail("frozen-contrib", f"contribution {EXPECTED_CONTRIB}",
             f"{float(od['order_contribution_profit'].sum())}")
    if abs(float(od["order_freight"].sum()) - EXPECTED_FREIGHT) > TOL:
        fail("frozen-freight", f"freight {EXPECTED_FREIGHT}",
             f"{float(od['order_freight'].sum())}")
    record("frozen", "order-level contribution reconciles to Phase 2 baseline",
           f"contrib {EXPECTED_CONTRIB} / freight {EXPECTED_FREIGHT}",
           f"{float(od['order_contribution_profit'].sum()):.4f} / "
           f"{float(od['order_freight'].sum()):.2f}", "PASS")
    od["order_contribution_margin_pct_check"] = np.where(
        od["order_revenue"] == 0, np.nan,
        od["order_contribution_profit"] / od["order_revenue"] * 100.0)
    mgap = float((od["order_contribution_margin_pct_check"]
                  - od["order_contribution_margin_pct"]).abs().max())
    if mgap > 1e-6:
        fail("order-margin", "order margin SUM/SUM consistent", f"{mgap}")

    # ================= outputs ==================================================
    od["neg_contribution_order"] = (od["order_contribution_profit"] < 0).astype(int)
    od["realization_rate"] = np.where(
        od["order_gross_revenue"] == 0, np.nan,
        od["order_revenue"] / od["order_gross_revenue"] * 100.0)

    # ---- 1. overall x band (dual basis: ORDER authoritative + LINE partial) ---
    ob = od.groupby("order_discount_band", sort=True).agg(
        line_count=("line_count", "sum"),
        order_count=("order_id", "nunique"),
        quantity=("order_quantity", "sum"),
        gross_revenue=("order_gross_revenue", "sum"),
        net_revenue=("order_revenue", "sum"),
        discount_amount=("order_discount_amount", "sum"),
        modeled_cogs=("order_cogs", "sum"),
        freight_cost=("order_freight", "sum"),
        cost_to_serve=("order_cost_to_serve", "sum"),
        contribution_profit=("order_contribution_profit", "sum"),
        neg_contribution_orders=("neg_contribution_order", "sum"),
    ).reset_index().rename(columns={"order_discount_band": "band"})
    ob["gross_profit_basis"] = (ob["net_revenue"] - ob["modeled_cogs"])
    ob = finalize_rates(
        ob.rename(columns={"gross_profit_basis": "modeled_gross_profit"}))
    ob["contribution_margin_pct"] = np.where(
        ob["net_revenue"] == 0, np.nan,
        ob["contribution_profit"] / ob["net_revenue"] * 100.0)
    ob["basis"] = "ORDER"
    ob["contribution_authority"] = "AUTHORITATIVE_ORDER"
    ob["neg_grossprofit_lines"] = np.nan
    ob["neg_contribution_lines"] = np.nan

    lb = summarize_frame(e, ["discount_band"]).rename(columns={"discount_band": "band"})
    lb = finalize_rates(lb)
    lb["contribution_authority"] = "LINE_PARTIAL_EXCL_AMBIGUOUS"
    lb["basis"] = "LINE"
    lb["freight_cost"] = lb["line_freight_partial"]
    lb["contribution_profit"] = lb["line_contribution_partial"]
    lb["cost_to_serve"] = lb["line_freight_partial"]
    lb["contribution_margin_pct"] = np.where(
        lb["net_revenue"] == 0, np.nan,
        lb["contribution_profit"] / lb["net_revenue"] * 100.0)
    lb["neg_contribution_orders"] = np.nan
    lb = lb.rename(columns={"neg_grossprofit_lines": "neg_grossprofit_lines",
                             "neg_contribution_lines": "neg_contribution_lines"})

    def total_row(df: pd.DataFrame, basis: str, authority: str) -> pd.DataFrame:
        def _sum_or_nan(col: str) -> float:
            return float(df[col].sum()) if col in df.columns else np.nan
        t = pd.DataFrame([{
            "band": "TOTAL", "line_count": int(df["line_count"].sum()),
            "order_count": int(df["order_count"].sum()
                               if basis == "ORDER" else
                               e["order_id"].nunique()),
            "quantity": int(df["quantity"].sum()
                            if basis == "ORDER" else e["quantity"].sum()),
            "gross_revenue": float(df["gross_revenue"].sum()),
            "net_revenue": float(df["net_revenue"].sum()),
            "discount_amount": float(df["discount_amount"].sum()),
            "modeled_cogs": float(df["modeled_cogs"].sum()),
            "modeled_gross_profit": float(df["modeled_gross_profit"].sum()),
            "freight_cost": float(df["freight_cost"].sum()),
            "cost_to_serve": float(df["cost_to_serve"].sum()),
            "contribution_profit": float(df["contribution_profit"].sum()),
            "neg_grossprofit_lines": _sum_or_nan("neg_grossprofit_lines"),
            "neg_contribution_lines": _sum_or_nan("neg_contribution_lines"),
            "neg_contribution_orders": _sum_or_nan("neg_contribution_orders"),
        }])
        t = finalize_rates(t)
        t["contribution_margin_pct"] = (t["contribution_profit"]
                                        / t["net_revenue"] * 100.0)
        t["basis"] = basis
        t["contribution_authority"] = authority
        return t

    band_cols = ["basis", "band", "line_count", "order_count", "quantity",
                 "quantity_per_order", "quantity_per_line", "gross_revenue",
                 "net_revenue", "discount_amount", "wad",
                 "discount_amount_pct_of_gross", "revenue_realization_rate",
                 "modeled_gross_profit", "modeled_gross_margin_pct",
                 "freight_cost", "cost_to_serve", "contribution_profit",
                 "contribution_margin_pct", "neg_grossprofit_lines",
                 "neg_contribution_lines", "neg_contribution_orders",
                 "contribution_authority", "low_sample_flag"]
    band_out = pd.concat(
        [ob.assign(band=ob["band"])[band_cols],
         total_row(ob, "ORDER", "AUTHORITATIVE_ORDER")[band_cols],
         lb[band_cols], total_row(lb, "LINE", "LINE_PARTIAL_EXCL_AMBIGUOUS")[
             band_cols]],
        ignore_index=True)
    band_out["band_label"] = band_out["band"].map(
        {**BAND_LABEL, "TOTAL": "All discounts"})
    band_out["_sort"] = band_out["band"].map(
        {b: i for i, b in enumerate(BAND_ORDER + ["TOTAL"])})
    band_out = band_out.sort_values(["basis", "_sort"]).drop(
        columns=["_sort"]).reset_index(drop=True)
    # ORDER TOTAL must equal the frozen baseline exactly
    ot = band_out[(band_out["basis"] == "ORDER") & (band_out["band"] == "TOTAL")].iloc[0]
    if abs(ot["contribution_profit"] - EXPECTED_CONTRIB) > TOL:
        fail("band-total", f"ORDER TOTAL contribution {EXPECTED_CONTRIB}",
             f"{ot['contribution_profit']}")
    # LINE partial gap must equal the documented ambiguous-pair treatment
    lt = band_out[(band_out["basis"] == "LINE") & (band_out["band"] == "TOTAL")].iloc[0]
    line_gap = float(ot["contribution_profit"] - lt["contribution_profit"])
    record("line-gap", "line-partial vs authoritative gap stated",
           "gap equals held-at-order pair economics",
           f"gap={line_gap:.4f} (25.05 freight + 225.10 gross held at order)",
           "PASS")

    # ---- 2. segment x band (dual basis; orders all single-segment) ------------
    e_seg = e[["row_id", "order_id", "segment", "quantity", "gross_revenue",
               "net_revenue", "discount_amount", "modeled_cogs",
               "modeled_gross_profit", "freight_cost_observed",
               "contribution_profit", "discount_band"]].copy()
    seg_line = summarize_frame(e_seg, ["segment", "discount_band"])
    seg_line = seg_line.rename(columns={"discount_band": "band"})
    seg_line = finalize_rates(seg_line)
    seg_line["basis"] = "LINE"
    seg_line["contribution_authority"] = "LINE_PARTIAL_EXCL_AMBIGUOUS"
    seg_line["freight_cost"] = seg_line["line_freight_partial"]
    seg_line["contribution_profit"] = seg_line["line_contribution_partial"]
    seg_line["cost_to_serve"] = seg_line["line_freight_partial"]
    seg_line["contribution_margin_pct"] = np.where(
        seg_line["net_revenue"] == 0, np.nan,
        seg_line["contribution_profit"] / seg_line["net_revenue"] * 100.0)
    seg_line["neg_contribution_orders"] = np.nan

    seg_ord = od.groupby(["segment", "order_discount_band"], sort=True).agg(
        line_count=("line_count", "sum"),
        order_count=("order_id", "nunique"),
        quantity=("order_quantity", "sum"),
        gross_revenue=("order_gross_revenue", "sum"),
        net_revenue=("order_revenue", "sum"),
        discount_amount=("order_discount_amount", "sum"),
        modeled_cogs=("order_cogs", "sum"),
        modeled_gross_profit=("order_revenue",
                              lambda s: float((od.loc[s.index, "order_revenue"]
                                               - od.loc[s.index, "order_cogs"]).sum())),
        freight_cost=("order_freight", "sum"),
        cost_to_serve=("order_cost_to_serve", "sum"),
        contribution_profit=("order_contribution_profit", "sum"),
        neg_contribution_orders=("neg_contribution_order", "sum"),
    ).reset_index().rename(columns={"order_discount_band": "band"})
    seg_ord = finalize_rates(seg_ord)
    seg_ord["contribution_margin_pct"] = np.where(
        seg_ord["net_revenue"] == 0, np.nan,
        seg_ord["contribution_profit"] / seg_ord["net_revenue"] * 100.0)
    seg_ord["basis"] = "ORDER"
    seg_ord["contribution_authority"] = "AUTHORITATIVE_ORDER"
    seg_ord["neg_grossprofit_lines"] = np.nan
    seg_ord["neg_contribution_lines"] = np.nan

    seg_out = pd.concat([seg_ord[band_cols + ["segment"]],
                         seg_line[band_cols + ["segment"]]],
                        ignore_index=True)
    # segment totals (ORDER basis, authoritative)
    seg_tot = od.groupby(["segment"], sort=True).agg(
        line_count=("line_count", "sum"),
        order_count=("order_id", "nunique"),
        quantity=("order_quantity", "sum"),
        gross_revenue=("order_gross_revenue", "sum"),
        net_revenue=("order_revenue", "sum"),
        discount_amount=("order_discount_amount", "sum"),
        modeled_cogs=("order_cogs", "sum"),
        freight_cost=("order_freight", "sum"),
        cost_to_serve=("order_cost_to_serve", "sum"),
        contribution_profit=("order_contribution_profit", "sum"),
        neg_contribution_orders=("neg_contribution_order", "sum"),
    ).reset_index()
    seg_tot["band"] = "TOTAL"
    seg_tot["modeled_gross_profit"] = (seg_tot["net_revenue"]
                                       - seg_tot["modeled_cogs"])
    seg_tot = finalize_rates(seg_tot)
    seg_tot["contribution_margin_pct"] = (seg_tot["contribution_profit"]
                                          / seg_tot["net_revenue"] * 100.0)
    seg_tot["basis"] = "ORDER"
    seg_tot["contribution_authority"] = "AUTHORITATIVE_ORDER"
    seg_tot["neg_grossprofit_lines"] = np.nan
    seg_tot["neg_contribution_lines"] = np.nan
    seg_out = pd.concat([seg_out, seg_tot[band_cols + ["segment"]]],
                        ignore_index=True)
    if abs(float(seg_out[(seg_out["basis"] == "ORDER")
                         & (seg_out["band"] == "TOTAL")]
                         ["contribution_profit"].sum()) - EXPECTED_CONTRIB) > TOL:
        fail("segment-total", "segment ORDER totals reconcile to baseline",
             "mismatch")

    # ---- 3/4. category + sub-category x band (gross-only, line basis) ---------
    def gross_only(frame: pd.DataFrame, keys: list[str]) -> pd.DataFrame:
        d = summarize_frame(frame, keys).rename(
            columns={"discount_band": "band"})
        d = finalize_rates(d)
        # line-partial serve-cost helpers are dropped here: product, category
        # and sub-category grains carry no freight attribution of any form.
        d = d.drop(columns=["line_freight_partial",
                            "line_contribution_partial"])
        d["freight_cost"] = np.nan
        d["cost_to_serve"] = np.nan
        d["contribution_profit"] = np.nan
        d["contribution_margin_pct"] = np.nan
        d["contribution_authority"] = "NOT_LICENSED_GROSS_ONLY"
        d["null_reason"] = NULL_REASON_BELOW_ORDER_GRAIN
        d["neg_contribution_lines"] = np.nan
        d["neg_contribution_orders"] = np.nan
        return d

    cat_detail = gross_only(e, ["category", "discount_band"])
    cat_tot = gross_only(e, ["category"])
    cat_tot["band"] = "TOTAL"
    cat_out = pd.concat([cat_detail, cat_tot], ignore_index=True)
    cat_out["_sort"] = cat_out["band"].map(
        {b: i for i, b in enumerate(BAND_ORDER + ["TOTAL"])})
    cat_out = cat_out.sort_values(["category", "_sort"]).drop(
        columns=["_sort"]).reset_index(drop=True)

    sub_detail = gross_only(e, ["sub_category", "discount_band"])
    sub_tot = gross_only(e, ["sub_category"])
    sub_tot["band"] = "TOTAL"
    sub_out = pd.concat([sub_detail, sub_tot], ignore_index=True)
    sub_out["_sort"] = sub_out["band"].map(
        {b: i for i, b in enumerate(BAND_ORDER + ["TOTAL"])})
    sub_out = sub_out.sort_values(["sub_category", "_sort"]).drop(
        columns=["_sort"]).reset_index(drop=True)

    # ---- 5. customer summary (TOTAL + BAND, order basis, authoritative) -------
    cust_band = od.groupby(["customer_id", "customer_name", "segment",
                            "order_discount_band"], sort=True).agg(
        line_count=("line_count", "sum"),
        order_count=("order_id", "nunique"),
        quantity=("order_quantity", "sum"),
        gross_revenue=("order_gross_revenue", "sum"),
        net_revenue=("order_revenue", "sum"),
        discount_amount=("order_discount_amount", "sum"),
        modeled_cogs=("order_cogs", "sum"),
        freight_cost=("order_freight", "sum"),
        cost_to_serve=("order_cost_to_serve", "sum"),
        contribution_profit=("order_contribution_profit", "sum"),
        neg_contribution_orders=("neg_contribution_order", "sum"),
    ).reset_index().rename(columns={"order_discount_band": "band"})
    cust_band["row_type"] = "CUSTOMER_BAND"
    cust_band["modeled_gross_profit"] = (cust_band["net_revenue"]
                                         - cust_band["modeled_cogs"])
    cust_band = finalize_rates(cust_band)
    cust_band["contribution_margin_pct"] = np.where(
        cust_band["net_revenue"] == 0, np.nan,
        cust_band["contribution_profit"] / cust_band["net_revenue"] * 100.0)
    cust_band["contribution_authority"] = "AUTHORITATIVE_ORDER"
    cust_band["bands_active"] = 1

    cust_tot = od.groupby(["customer_id", "customer_name", "segment"],
                          sort=True).agg(
        line_count=("line_count", "sum"),
        order_count=("order_id", "nunique"),
        quantity=("order_quantity", "sum"),
        gross_revenue=("order_gross_revenue", "sum"),
        net_revenue=("order_revenue", "sum"),
        discount_amount=("order_discount_amount", "sum"),
        modeled_cogs=("order_cogs", "sum"),
        freight_cost=("order_freight", "sum"),
        cost_to_serve=("order_cost_to_serve", "sum"),
        contribution_profit=("order_contribution_profit", "sum"),
        neg_contribution_orders=("neg_contribution_order", "sum"),
    ).reset_index()
    cust_tot["row_type"] = "CUSTOMER_TOTAL"
    cust_tot["band"] = "ALL"
    cust_tot["modeled_gross_profit"] = (cust_tot["net_revenue"]
                                        - cust_tot["modeled_cogs"])
    cust_tot = finalize_rates(cust_tot)
    cust_tot["contribution_margin_pct"] = np.where(
        cust_tot["net_revenue"] == 0, np.nan,
        cust_tot["contribution_profit"] / cust_tot["net_revenue"] * 100.0)
    cust_tot["contribution_authority"] = "AUTHORITATIVE_ORDER"
    n_bands = od.groupby("customer_id")["order_discount_band"].nunique()
    prim = (od.groupby(["customer_id", "order_discount_band"])
              ["order_gross_revenue"].sum().reset_index()
              .sort_values(["customer_id", "order_gross_revenue"],
                           ascending=[True, False])
              .drop_duplicates("customer_id")
              .set_index("customer_id")["order_discount_band"])
    cust_tot["bands_active"] = cust_tot["customer_id"].map(n_bands).astype(int)
    cust_tot["primary_band"] = cust_tot["customer_id"].map(prim)
    cust_band["primary_band"] = np.nan
    cust_cols = ["row_type", "customer_id", "customer_name", "segment", "band",
                 "bands_active", "primary_band", "line_count", "order_count",
                 "quantity", "quantity_per_order", "quantity_per_line",
                 "gross_revenue", "net_revenue", "discount_amount", "wad",
                 "discount_amount_pct_of_gross", "revenue_realization_rate",
                 "modeled_gross_profit", "modeled_gross_margin_pct",
                 "freight_cost", "cost_to_serve", "contribution_profit",
                 "contribution_margin_pct", "neg_contribution_orders",
                 "contribution_authority", "low_sample_flag"]
    cust_out = pd.concat([cust_tot[cust_cols], cust_band[cust_cols]],
                         ignore_index=True)
    cust_out["_sort"] = cust_out["band"].map(
        {b: i for i, b in enumerate(BAND_ORDER + ["ALL"])})
    cust_out = cust_out.sort_values(["customer_id", "_sort"]).drop(
        columns=["_sort"]).reset_index(drop=True)
    if len(cust_tot) != 793:
        fail("customer-count", "793 customer TOTAL rows", f"{len(cust_tot)}")
    if abs(float(cust_tot["contribution_profit"].sum()) - EXPECTED_CONTRIB) > TOL:
        fail("customer-total", "customer totals reconcile to baseline", "mismatch")
    record("customers", "793 customers with authoritative contribution",
           f"contrib {EXPECTED_CONTRIB}",
           f"{float(cust_tot['contribution_profit'].sum()):.4f}", "PASS")

    # ---- 6. order summary (5,009 rows, authoritative + rollup) -----------------
    ord_out = od[["order_id", "customer_id", "customer_name", "segment",
                  "line_count", "order_quantity", "order_gross_revenue",
                  "order_revenue", "order_discount_amount", "order_wad",
                  "order_discount_band", "realization_rate", "order_cogs",
                  "order_freight", "order_return_status",
                  "order_cost_to_serve", "order_contribution_profit",
                  "order_contribution_margin_pct",
                  "neg_contribution_order"]].copy()
    ord_out = ord_out.rename(columns={
        "order_quantity": "quantity", "order_gross_revenue": "gross_revenue",
        "order_revenue": "net_revenue",
        "order_discount_amount": "discount_amount", "order_wad": "wad",
        "order_discount_band": "discount_band",
        "realization_rate": "revenue_realization_rate",
        "order_cogs": "modeled_cogs", "order_freight": "freight_cost",
        "order_cost_to_serve": "cost_to_serve",
        "order_contribution_profit": "contribution_profit",
        "order_contribution_margin_pct": "contribution_margin_pct",
        "neg_contribution_order": "negative_contribution_flag"})
    ord_out["modeled_gross_profit"] = (ord_out["net_revenue"]
                                       - ord_out["modeled_cogs"])
    ord_out["modeled_gross_margin_pct"] = np.where(
        ord_out["net_revenue"] == 0, np.nan,
        ord_out["modeled_gross_profit"] / ord_out["net_revenue"] * 100.0)
    ord_out["discount_amount_pct_of_gross"] = ord_out["wad"] * 100.0
    ord_out["contribution_authority"] = "AUTHORITATIVE_ORDER"
    ord_out["ambiguity_note"] = np.where(
        ord_out["order_id"] == ambig_order,
        "ORDER_CONTAINS_AMBIGUOUS_PAIR_25P05_HELD_AT_ORDER",
        "")
    ord_out["low_sample_flag"] = False
    ord_out = ord_out.sort_values("order_id").reset_index(drop=True)

    # ---- 7. product summary (TOTAL + BAND, gross-only, flagged reference) -----
    prod_band = gross_only(e, ["analytical_product_key", "product_id",
                               "product_name", "category", "sub_category",
                               "discount_band"])
    prod_tot = gross_only(e, ["analytical_product_key", "product_id",
                              "product_name", "category", "sub_category"])
    prod_tot["band"] = "ALL"
    prod_out = pd.concat([prod_tot, prod_band], ignore_index=True)
    n_orders_prod = (e.groupby("analytical_product_key")["order_id"].nunique())
    prod_out["distinct_orders_overall"] = prod_out["analytical_product_key"].map(
        n_orders_prod).astype(int)
    prod_out["low_volume_flag"] = prod_out["distinct_orders_overall"] == 1
    prod_out["row_type"] = np.where(prod_out["band"] == "ALL",
                                    "PRODUCT_TOTAL", "PRODUCT_BAND")
    prod_out["_sort"] = prod_out["band"].map(
        {b: i for i, b in enumerate(BAND_ORDER + ["ALL"])})
    prod_out = prod_out.sort_values(
        ["analytical_product_key", "_sort"]).drop(
            columns=["_sort"]).reset_index(drop=True)
    if int((prod_out["row_type"] == "PRODUCT_TOTAL").sum()) != 1894:
        fail("product-count", "1894 PRODUCT_TOTAL rows", "mismatch")
    if bool(prod_out["low_sample_flag"].sum() != len(prod_out)):
        record("product-flags", "product sparsity fully flagged",
               "all product rows below provisional thresholds",
               f"{int(prod_out['low_sample_flag'].sum())}/{len(prod_out)} "
               "flagged", "PASS")
    else:
        record("product-flags", "product sparsity fully flagged",
               "all product rows below provisional thresholds",
               f"{len(prod_out)}/{len(prod_out)} flagged", "PASS")

    # ---- write outputs ----------------------------------------------------------
    OUT.mkdir(parents=True, exist_ok=True)
    outputs: dict[str, pd.DataFrame] = {
        "discount_band_summary.csv": band_out,
        "discount_segment_summary.csv": seg_out,
        "discount_category_summary.csv": cat_out,
        "discount_subcategory_summary.csv": sub_out,
        "discount_customer_summary.csv": cust_out,
        "discount_order_summary.csv": ord_out,
        "discount_product_summary.csv": prod_out,
    }
    for name, df in outputs.items():
        if QUARANTINE_COL in df.columns:
            fail("quarantine-output", f"{QUARANTINE_COL} absent from {name}",
                 "column present")
        df.to_csv(OUT / name, index=False, encoding="utf-8")

    # ---- frozen inputs unchanged --------------------------------------------------
    if sha256(LINE_CSV) != line_hash_before:
        fail("frozen-line", "line fact byte-identical after run", "MODIFIED")
    if sha256(ORDER_CSV) != order_hash_before:
        fail("frozen-order", "order fact byte-identical after run", "MODIFIED")
    if sha256(FACT1_CSV) != fact1_hash_before:
        fail("frozen-phase1", "Phase 1 fact byte-identical after run", "MODIFIED")
    record("frozen", "frozen Phase 1/Phase 2 files unchanged",
           "byte-identical SHA-256 before/after", "unchanged", "PASS")

    # ---- WAD discipline: no arithmetic mean of rates anywhere --------------------
    wad_check = float((band_out[band_out["basis"] == "ORDER"]
                       .assign(alt=lambda d: 1 - d["net_revenue"]
                               / d["gross_revenue"])["wad"]
                       - band_out[band_out["basis"] == "ORDER"]
                       .assign(alt=lambda d: 1 - d["net_revenue"]
                               / d["gross_revenue"])["alt"]).abs().max())
    if wad_check > 1e-9:
        fail("wad-dual", "WAD dual forms reconcile", f"{wad_check}")
    record("wad", "gross-revenue-weighted WAD; no averaging of rates",
           "dual-form gap <= 1e-9", f"{wad_check:.2e}", "PASS")

    # ---- quality report -------------------------------------------------------------
    report = {
        "phase": "3B observed discount impact analysis (descriptive only)",
        "causal_scope": "No causal claims. Band-quantity patterns are "
                        "descriptive associations in historical data; they "
                        "are not estimates of demand response.",
        "configuration": {
            "bands": {b: label for b, label in BAND_LABEL.items()},
            "band_intervals": {
                "B0": "d = 0", "B1": "0 < d <= 0.15",
                "B2": "0.15 < d <= 0.25", "B3": "0.25 < d <= 0.35",
                "B4": "0.35 < d <= 0.55", "B5": "0.55 < d <= 0.80"},
            "minimum_line_count": MIN_LINE_COUNT,
            "minimum_order_count": MIN_ORDER_COUNT,
            "threshold_status": "provisional analytical thresholds "
                                "(D3B-02), not universal statistical rules",
            "order_band_rule": "order weighted-average discount band "
                               "(D3B-03); single rule, no competing rule",
            "quantile_comparator": "not built (D3B-04)",
            "scenarios": "OFF",
            "elasticity_coefficients": "none estimated",
            "quantity_response_assumptions": "none introduced",
        },
        "inputs": {
            "fact_margin_map_phase2.csv": {"rows": len(e),
                                           "sha256": line_hash_before},
            "order_margin_map_phase2.csv": {"rows": len(o),
                                            "sha256": order_hash_before},
            "fact_sales_cogs.csv": {"rows": len(f1),
                                    "sha256": fact1_hash_before},
        },
        "band_validation": {
            "line_counts": {b: int(band_counts.get(b, 0)) for b in BAND_ORDER},
            "order_counts": {b: int((oroll["order_discount_band"] == b).sum())
                             for b in BAND_ORDER},
            "zero_preserved": True,
            "no_value_split": True,
            "coverage_complete": True,
        },
        "frozen_baseline_reconciliation": {
            "revenue": float(od["order_revenue"].sum()),
            "cogs": float(od["order_cogs"].sum()),
            "freight": float(od["order_freight"].sum()),
            "contribution_profit": float(
                od["order_contribution_profit"].sum()),
            "expected_contribution_profit": EXPECTED_CONTRIB,
            "line_partial_gap": line_gap,
        },
        "checks": checks,
        "outputs": {},
    }
    for name, df in outputs.items():
        p = OUT / name
        report["outputs"][name] = {"rows": int(len(df)),
                                   "columns": int(len(df.columns)),
                                   "sha256": sha256(p)}
    with open(OUT / "phase3b_quality_report.json", "w",
              encoding="utf-8") as fh:
        json.dump(report, fh, indent=2)
        fh.write("\n")

    print(f"OK: bands={' '.join(f'{b}={int(band_counts.get(b, 0))}' for b in BAND_ORDER)}")
    print(f"OK: orders/band="
          f"{' '.join(f'{b}={int((oroll['order_discount_band'] == b).sum())}' for b in BAND_ORDER)}")
    print(f"OK: contrib={float(od['order_contribution_profit'].sum()):,.4f} "
          f"(expected {EXPECTED_CONTRIB})")
    for name, df in outputs.items():
        print(f"OK: {name} rows={len(df)}")


if __name__ == "__main__":
    try:
        main()
    except SystemExit as exc:
        print(str(exc), file=sys.stderr)
        raise
