"""MarginMap Phase 4C (slice 4) — AO-04 Contribution Variance by Discount Band.

Scope (per docs/PHASE_4C_ANALYTICAL_INTERPRETATION_DESIGN.md, AO-04):
  ONE per-baseline-band arithmetic-sensitivity reading for each frozen
  scenario instance, on the existing baseline order-WAD bands (ORDER basis,
  never re-banded). Baseline and hypothetical values remain clearly
  separated; band-level variance is never inferred from incompatible
  grains. No order detail, no visuals, no forecasts, no causal claims.
  Identity slices (0.00) carry zero variances by construction (integrity,
  not economics).

Inputs (READ-ONLY — never modified, never regenerated by this script):
    data/processed/phase4b_scenario_uniform_0.10.csv  + quality JSON (15/15)
    data/processed/phase4b_scenario_increase_0.00.csv + quality JSON (22/22)
    data/processed/phase4b_scenario_decrease_0.00.csv + quality JSON (22/22)

Outputs (NEW files only; written after every validation check passes):
    data/processed/phase4c_contribution_variance_by_band.csv
    data/processed/phase4c_contribution_variance_by_band_quality.json

Usage (all paths have frozen defaults; overrides exist ONLY so that
missing/invalid-input behavior can be tested without touching frozen files):
    python src/data/build_phase4c_band_variance.py

Rules (frozen definitions restated — not redefined):
    variance = hypothetical - baseline, reconciled both ways (<=1e-9);
    relative variance = variance / baseline x 100, NULL/blank where the
    baseline is zero (absolute variance still reported); margin changes in
    percentage points (SUM/SUM margins, never averaged); freight variance
    exactly 0 per band by passthrough design; band rows sum to TOTAL.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
PROCESSED = ROOT / "data" / "processed"
OUT_DIR = PROCESSED
OUT_CSV_NAME = "phase4c_contribution_variance_by_band.csv"
OUT_JSON_NAME = "phase4c_contribution_variance_by_band_quality.json"

# ---- frozen instances (Phase 4B freeze records; nothing else is a source) ----
INSTANCES = (
    {"key": "uniform",
     "csv": "phase4b_scenario_uniform_0.10.csv",
     "json": "phase4b_scenario_uniform_0.10_quality.json",
     "scenario_id": "uniform_replace_0.10",
     "scenario_type": "uniform_replacement",
     "input_form": "replacement_rate",
     "stated_col": "stated_rate",
     "stated_value": 0.10,
     "n_checks": 15},
    {"key": "uniform020",
     "csv": "phase4b_scenario_uniform_0.20.csv",
     "json": "phase4b_scenario_uniform_0.20_quality.json",
     "scenario_id": "uniform_replace_0.20",
     "scenario_type": "uniform_replacement",
     "input_form": "replacement_rate",
     "stated_col": "stated_rate",
     "stated_value": 0.20,
     "n_checks": 15},
    {"key": "increase",
     "csv": "phase4b_scenario_increase_0.00.csv",
     "json": "phase4b_scenario_increase_0.00_quality.json",
     "scenario_id": "discount_increase_pp_0.00",
     "scenario_type": "discount_increase",
     "input_form": "increase_pp",
     "stated_col": "stated_increase_pp",
     "stated_value": 0.0,
     "n_checks": 22},
    {"key": "decrease",
     "csv": "phase4b_scenario_decrease_0.00.csv",
     "json": "phase4b_scenario_decrease_0.00_quality.json",
     "scenario_id": "discount_decrease_pp_0.00",
     "scenario_type": "discount_decrease",
     "input_form": "decrease_pp",
     "stated_col": "stated_decrease_pp",
     "stated_value": 0.0,
     "n_checks": 22},
)

# ---- frozen expectations (Phase 2 / Phase 3B freeze records) ------------------
BAND_ORDER = ["B0", "B1", "B2", "B3", "B4", "B5", "TOTAL"]
EXPECTED_ORDER_COUNTS = {"B0": 2055, "B1": 415, "B2": 1634, "B3": 278,
                         "B4": 274, "B5": 353, "TOTAL": 5009}
EXPECTED_QTY = {"B0": 13784, "B1": 5056, "B2": 10930, "B3": 2912,
                "B4": 2812, "B5": 2379, "TOTAL": 37873}
EXPECTED_NEG_BASE = {"B0": 14, "B1": 3, "B2": 24, "B3": 1, "B4": 3,
                     "B5": 5, "TOTAL": 50}
EXPECTED_CONTRIB = 565116.9418
TOL = 0.05  # currency tolerance for source-total reconciliation only
VAR_TOL = 1e-9  # per-band variance arithmetic reconciliation tolerance

# ---- frozen fact hashes (chain-of-custody via scenario quality JSONs) ---------
FROZEN_FACT_HASHES = {
    "fact_margin_map_phase2.csv":
        "4038684d113ffee5697a4859991159b630802eb1697c3e12ee59735db5d42e06",
    "order_margin_map_phase2.csv":
        "ae6c349c9995747f2fef91cf1db6b940a73d99d6b2fede5ff3dff918f429d267",
}

OUTPUT_NAME = "Contribution variance by discount band"
GRAIN = "Overall x discount band"
STATUS_BASE = "OBSERVED BASELINE"
STATUS_HYPO = "HYPOTHETICAL_ARITHMETIC_SENSITIVITY"

REQUIRED_CSV_COLS = {"band", "order_count", "line_count", "quantity",
                     "base_contrib", "hypo_contrib",
                     "variance_net_revenue", "variance_discount_amount",
                     "variance_cogs", "variance_freight", "variance_cost_to_serve",
                     "variance_contribution_profit",
                     "base_wad", "hypo_wad", "base_contrib_margin",
                     "hypo_contrib_margin", "margin_change_pp",
                     "neg_base_orders", "neg_hypo_orders", "low_sample_flag",
                     "scenario_id", "scenario_type", "input_form", "scope", "basis",
                     "result_standing", "quantity_assumption", "cogs_method",
                     "freight_method", "return_support", "fixed_unit_cost_view",
                     "fixed_unit_cost_reason", "demand_response_view",
                     "demand_response_reason"}


def fail(check: str, expected: str, actual: str) -> "NoReturn":
    raise SystemExit(
        f"VALIDATION FAILED [{check}]\n  Expected: {expected}\n  Actual:   {actual}"
    )


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Phase 4C slice 4: AO-04 contribution variance by discount band.")
    p.add_argument("--processed-dir", type=Path, default=PROCESSED)
    p.add_argument("--out-dir", type=Path, default=OUT_DIR)
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    proc, out_dir = args.processed_dir, args.out_dir

    # ---- 1. source-artifact identity (fail-loud before any further I/O) --------
    for inst in INSTANCES:
        for label, name in (("scenario CSV", inst["csv"]),
                            ("quality JSON", inst["json"])):
            if not (proc / name).is_file():
                fail("inputs-exist", f"{label} present at {proc / name}",
                     "file missing")

    # ---- 2. quality evidence: counts, PASS status, unique IDs --------------------
    qualities: dict[str, dict] = {}
    for inst in INSTANCES:
        try:
            q = json.loads((proc / inst["json"]).read_text(encoding="utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError) as e:
            fail("quality-status", f"{inst['json']} valid JSON", f"parse error: {e}")
        checks = q.get("checks", [])
        ids = [c.get("id") for c in checks]
        if len(checks) != inst["n_checks"] or len(set(ids)) != len(ids):
            fail("quality-status",
                 f"{inst['json']} {inst['n_checks']}/{inst['n_checks']} unique checks",
                 f"{len(checks)} checks / {len(set(ids))} unique IDs")
        if any(c.get("status") != "PASS" for c in checks):
            bad = [c.get("id") for c in checks if c.get("status") != "PASS"]
            fail("quality-status", f"all {inst['json']} checks PASS",
                 f"non-PASS: {bad}")
        scen = q.get("scenario", {})
        if scen.get("scenario_id") != inst["scenario_id"] or \
                scen.get("scenario_type") != inst["scenario_type"] or \
                scen.get("input_form") != inst["input_form"]:
            fail("identifiers", f"{inst['scenario_id']} / {inst['scenario_type']} / "
                                f"{inst['input_form']}",
                 f"{scen.get('scenario_id')} / {scen.get('scenario_type')} / "
                 f"{scen.get('input_form')}")
        if scen.get("scope") != "all_valid_lines":
            fail("identifiers", "scope all_valid_lines", repr(scen.get("scope")))
        for fname, digest in FROZEN_FACT_HASHES.items():
            recorded = q.get("inputs", {}).get(fname, {}).get("sha256")
            if recorded != digest:
                fail("fact-chain", f"{fname} {digest}", repr(recorded))
        qualities[inst["key"]] = q

    # ---- 3. chain integrity: CSV bytes match sha recorded in quality JSON --------
    frames: dict[str, pd.DataFrame] = {}
    for inst in INSTANCES:
        digest = sha256(proc / inst["csv"])
        recorded = qualities[inst["key"]].get("outputs", {}).get(
            inst["csv"], {}).get("sha256")
        if digest != recorded:
            fail("quality-chain", f"{inst['csv']} sha {recorded}", digest)
        frames[inst["key"]] = pd.read_csv(proc / inst["csv"])

    # ---- 4. shapes, ORDER basis, band order, schema, quarantine ---------------------
    for inst in INSTANCES:
        df = frames[inst["key"]]
        if df.shape != (7, 52):
            fail("shapes", f"{inst['csv']} 7 rows x 52 cols", repr(df.shape))
        if REQUIRED_CSV_COLS - set(df.columns):
            fail("band-schema", f"columns {sorted(REQUIRED_CSV_COLS)}",
                 f"columns {list(df.columns)}")
        if "source_profit_quarantined" in df.columns or "profit" in df.columns:
            fail("quarantine", "no quarantined-Profit column", "profit column present")
        if [str(b) for b in df["band"]] != BAND_ORDER:
            fail("band-coverage", f"bands {BAND_ORDER}",
                 repr([str(b) for b in df["band"]]))
        if not bool((df["basis"] == "ORDER").all()):
            fail("grain", "basis ORDER on every row (baseline bands, never re-banded)",
                 repr(df["basis"].unique().tolist()))
        row0 = df.iloc[0]
        if row0["scenario_id"] != inst["scenario_id"] or \
                row0["scenario_type"] != inst["scenario_type"] or \
                row0["input_form"] != inst["input_form"]:
            fail("identifiers", f"rows carry {inst['scenario_id']}",
                 repr(row0["scenario_id"]))
        if float(row0[inst["stated_col"]]) != inst["stated_value"]:
            fail("input-forms", f"{inst['stated_col']} {inst['stated_value']}",
                 repr(row0[inst["stated_col"]]))
        if row0["scope"] != "all_valid_lines":
            fail("identifiers", "scope all_valid_lines", repr(row0["scope"]))
        if row0["result_standing"] != "HYPOTHETICAL_ARITHMETIC_SENSITIVITY_NOT_A_FORECAST":
            fail("identifiers", "standing HYPOTHETICAL_ARITHMETIC_SENSITIVITY_NOT_A_FORECAST",
                 repr(row0["result_standing"]))
        for col, label in (("quantity_assumption", "CONSTANT_OBSERVED_QUANTITY"),
                           ("cogs_method", "FROZEN_MODELED_COGS_PCT"),
                           ("freight_method", "OBSERVED_PASSTHROUGH"),
                           ("return_support", "OFF")):
            if not bool((df[col] == label).all()):
                fail("assumption-labels", f"{col} {label} on every band row",
                     repr(df[col].unique().tolist()))
        if df["fixed_unit_cost_view"].notna().any() or \
                not bool((df["fixed_unit_cost_reason"]
                          == "COMPARATOR_NOT_IN_INITIAL_BUILD").all()):
            fail("na-markers", "fixed_unit_cost N/A with reason on every band row",
                 "violation found")
        if df["demand_response_view"].notna().any() or \
                not bool((df["demand_response_reason"]
                          == "RESPONSE_NOT_ESTIMATED").all()):
            fail("na-markers", "demand_response N/A with reason on every band row",
                 "violation found")
        if bool(df["low_sample_flag"].fillna(False).any()):
            fail("flags", "low_sample_flag FALSE on every band row", "TRUE found")

    # ---- 5. frozen per-band counts ----------------------------------------------------
    for inst in INSTANCES:
        df = frames[inst["key"]]
        for _, r in df.iterrows():
            band = str(r["band"])
            if int(r["order_count"]) != EXPECTED_ORDER_COUNTS[band]:
                fail("counts-per-band",
                     f"{inst['key']} {band} orders {EXPECTED_ORDER_COUNTS[band]}",
                     repr(r["order_count"]))
            if int(r["quantity"]) != EXPECTED_QTY[band]:
                fail("counts-per-band",
                     f"{inst['key']} {band} quantity {EXPECTED_QTY[band]}",
                     repr(r["quantity"]))
            if int(float(r["neg_base_orders"])) != \
                    {"B0": 14, "B1": 3, "B2": 24, "B3": 1, "B4": 3,
                     "B5": 5, "TOTAL": 50}[band]:
                fail("negatives", f"{inst['key']} {band} neg_base_orders",
                     repr(r["neg_base_orders"]))
            if float(r["neg_hypo_orders"]) < 0 or \
                    float(r["neg_hypo_orders"]) != int(float(r["neg_hypo_orders"])):
                fail("negatives", f"{inst['key']} {band} neg_hypo_orders nonneg int",
                     repr(r["neg_hypo_orders"]))

    # ---- 6. band rows sum to TOTAL (per instance) -----------------------------------------
    for inst in INSTANCES:
        df = frames[inst["key"]]
        detail = df[df["band"] != "TOTAL"]
        total = df[df["band"] == "TOTAL"].iloc[0]
        for col in ("order_count", "line_count", "quantity",
                    "variance_net_revenue", "variance_discount_amount",
                    "variance_cogs", "variance_freight", "variance_cost_to_serve",
                    "variance_contribution_profit", "base_contrib", "hypo_contrib"):
            if abs(float(detail[col].sum()) - float(total[col])) > TOL:
                fail("band-totals-reconcile",
                     f"{inst['key']} {col} bands sum to TOTAL",
                     f"sum={float(detail[col].sum())!r} total={float(total[col])!r}")

    # ---- 7. TOTAL baselines identical + frozen ------------------------------------------------
    ref = frames["uniform"]
    ref_total = ref[ref["band"] == "TOTAL"].iloc[0]
    for key in ("uniform020", "increase", "decrease"):
        tot = frames[key][frames[key]["band"] == "TOTAL"].iloc[0]
        if abs(float(tot["base_contrib"]) - float(ref_total["base_contrib"])) > TOL:
            fail("baseline-identical", "TOTAL base_contrib identical across instances",
                 repr(float(tot["base_contrib"])))
    if abs(float(ref_total["base_contrib"]) - EXPECTED_CONTRIB) > TOL:
        fail("baseline-frozen", f"TOTAL base_contrib {EXPECTED_CONTRIB}",
             repr(float(ref_total["base_contrib"])))

    # ---- 8. per-band variance + margin reconciliation ----------------------------------------------
    CUR_PAIRS = (("variance_net_revenue", "hypo_net", "base_net"),
                 ("variance_discount_amount", "hypo_disc", "base_disc"),
                 ("variance_cogs", "hypo_cogs", "base_cogs"),
                 ("variance_contribution_profit", "hypo_contrib", "base_contrib"))
    for inst in INSTANCES:
        for _, r in frames[inst["key"]].iterrows():
            band = str(r["band"])
            for var_col, hypo_col, base_col in CUR_PAIRS:
                gap = abs(float(r[var_col]) - (float(r[hypo_col]) - float(r[base_col])))
                if gap > VAR_TOL:
                    fail("variance-reconcile",
                         f"{inst['key']} {band} {var_col} gap <= {VAR_TOL}", repr(gap))
            if float(r["variance_freight"]) != 0.0:
                fail("freight-zero", f"{inst['key']} {band} variance_freight exactly 0",
                     repr(float(r["variance_freight"])))
            if float(r["variance_cost_to_serve"]) != 0.0:
                fail("freight-zero", f"{inst['key']} {band} variance_cost_to_serve exactly 0",
                     repr(float(r["variance_cost_to_serve"])))
            pp_gap = abs(float(r["margin_change_pp"]) -
                         (float(r["hypo_contrib_margin"]) - float(r["base_contrib_margin"])))
            if pp_gap > VAR_TOL:
                fail("margin-pp", f"{inst['key']} {band} margin_change_pp gap <= {VAR_TOL}",
                     repr(pp_gap))

    # ---- 9. build deterministic metric table (baseline bands; TOTAL included) -----------------------
    rows: list[dict[str, str]] = []

    def sval(value: object) -> str:
        if value is None:
            return ""
        try:
            if pd.isna(value):
                return ""
        except (TypeError, ValueError):
            return str(value)
        if type(value).__module__ == "numpy":
            value = value.item()
            if value is None:
                return ""
        return repr(value) if isinstance(value, float) else str(value)

    def add(scenario_id: str, band: str, block: str, status: str, metric: str,
            value: object, unit: str, source: str, definition_ref: str,
            limitation: str) -> None:
        rows.append({
            "output_name": OUTPUT_NAME,
            "scenario_status": status,
            "grain": GRAIN,
            "scenario_id": scenario_id,
            "band": band,
            "block": block,
            "source_artifact": source,
            "metric_name": metric,
            "metric_value": sval(value),
            "unit": unit,
            "definition_ref": definition_ref,
            "limitation": limitation,
        })

    BASE_LIM = "Observed baseline on existing baseline bands; identical scope to hypothetical"
    HYPO_LIM = ("Hypothetical arithmetic sensitivity (constant quantity, frozen "
                "COGS pct, freight passthrough, return/support OFF); not a forecast")
    COND = "Conditional illustration under stated assumptions; not a forecast"
    for inst in INSTANCES:
        sid, csv = inst["scenario_id"], inst["csv"]
        for _, r in frames[inst["key"]].iterrows():
            band = str(r["band"])
            for metric, col, unit, dref in (
                    ("base_contribution", "base_contrib", "CUR", "Stored baseline contribution on baseline band"),
                    ("base_wad", "base_wad", "DEC", "Stored baseline WAD; never averaged"),
                    ("quantity", "quantity", "CT", "Observed quantity SUM on baseline band"),
                    ("order_count", "order_count", "CT", "Stored ORDER-basis order count"),
                    ("line_count", "line_count", "CT", "Stored line count"),
                    ("neg_base_orders", "neg_base_orders", "CT", "Stored baseline negative-order count")):
                add(sid, band, "baseline", STATUS_BASE, metric, r[col], unit, csv,
                    "Baseline block; " + dref, BASE_LIM)
            for metric, col, unit, dref in (
                    ("hypo_contribution", "hypo_contrib", "CUR", "Arithmetic scenario contribution on baseline band"),
                    ("hypo_wad", "hypo_wad", "DEC", "Hypothetical WAD under stated d'"),
                    ("neg_hypo_orders", "neg_hypo_orders", "CT", "Stored hypothetical negative-order count")):
                add(sid, band, "hypothetical", STATUS_HYPO, metric, r[col], unit, csv,
                    "Hypothetical block; " + dref, HYPO_LIM)
            for metric, col, unit, dref in (
                    ("variance_net_revenue", "variance_net_revenue", "CUR", "Hypothetical minus baseline"),
                    ("variance_discount_amount", "variance_discount_amount", "CUR", "Hypothetical minus baseline"),
                    ("variance_cogs", "variance_cogs", "CUR", "Hypothetical minus baseline"),
                    ("variance_freight", "variance_freight", "CUR", "Exactly 0 by passthrough design"),
                    ("variance_cost_to_serve", "variance_cost_to_serve", "CUR", "Exactly 0 by passthrough design"),
                    ("variance_contribution", "variance_contribution_profit", "CUR", "Hypothetical minus baseline")):
                add(sid, band, "variance", STATUS_HYPO, metric, r[col], unit, csv,
                    "Stored variance, reconciled both ways (<=1e-9); " + dref, COND)
            base_c = float(r["base_contrib"])
            var_c = float(r["variance_contribution_profit"])
            rel = var_c / base_c * 100 if base_c != 0 else None
            add(sid, band, "variance", STATUS_HYPO, "relative_contribution_variance",
                rel, "PCT", csv,
                "Computed variance/baseline x 100; NULL/blank where baseline is zero",
                COND + "; shown only where baseline nonzero")
            add(sid, band, "variance", STATUS_HYPO, "margin_change_pp",
                r["margin_change_pp"], "PP", csv,
                "Stored pp change, recomputed hypo minus base (<=1e-9)", COND)
            add(sid, band, "variance", STATUS_HYPO, "low_sample_flag",
                str(bool(r["low_sample_flag"])), "Flag", csv,
                "Thin-cell marker carried from source band row",
                "Provisional thresholds; FALSE on every band row")
            add(sid, band, "variance", STATUS_HYPO, "fixed_unit_cost_view", None,
                "Label", csv, "N/A: COMPARATOR_NOT_IN_INITIAL_BUILD",
                "Marked unavailable with reason; never estimated")
            add(sid, band, "variance", STATUS_HYPO, "demand_response_view", None,
                "Label", csv, "N/A: RESPONSE_NOT_ESTIMATED",
                "Marked unavailable with reason; never estimated")

    out_csv = out_dir / OUT_CSV_NAME
    out_json = out_dir / OUT_JSON_NAME

    # ---- 10. write outputs only after every check passed ---------------------------------------
    out_dir.mkdir(parents=True, exist_ok=True)
    import csv as _csv
    with open(out_csv, "w", newline="", encoding="utf-8") as f:
        w = _csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    quality = {
        "phase": "4C slice 4 — AO-04 contribution variance by discount band (arithmetic sensitivity; not a forecast)",
        "output": {
            "output_name": OUTPUT_NAME,
            "grain": GRAIN,
            "scenario_status": "BASELINE_BESIDE_HYPOTHETICAL",
            "standing": "HYPOTHETICAL_ARITHMETIC_SENSITIVITY_NOT_A_FORECAST",
        },
        "inputs": {
            inst["csv"]: {"rows": 7, "columns": 52,
                          "sha256": sha256(proc / inst["csv"]),
                          "scenario_id": inst["scenario_id"]}
            for inst in INSTANCES
        },
        "evidence": {
            inst["json"]: {"checks": inst["n_checks"], "status": "all PASS",
                           "scenario_id": inst["scenario_id"]}
            for inst in INSTANCES
        },
        "checks": [
            {"id": "inputs-exist", "description": "4 scenario CSVs + 4 quality JSONs present",
             "expected": "8 files", "actual": "present", "status": "PASS"},
            {"id": "quality-status", "description": "frozen quality evidence all PASS, unique IDs",
             "expected": "15/15 + 15/15 + 22/22 + 22/22 unique",
             "actual": "15/15 + 15/15 + 22/22 + 22/22 unique", "status": "PASS"},
            {"id": "quality-chain", "description": "CSV bytes match sha recorded in quality JSON",
             "expected": "4/4 match", "actual": "4/4 match", "status": "PASS"},
            {"id": "fact-chain", "description": "fact hashes in scenario evidence match freeze records",
             "expected": "2 facts x 4 evidence files match", "actual": "match", "status": "PASS"},
            {"id": "identifiers", "description": "scenario_id/type/scope/standing per instance",
             "expected": "uniform_replace_0.10 / uniform_replace_0.20 / discount_increase_pp_0.00 / discount_decrease_pp_0.00; all_valid_lines",
             "actual": "match", "status": "PASS"},
            {"id": "input-forms", "description": "stated input form + value per instance",
             "expected": "replacement_rate 0.10; replacement_rate 0.20; increase_pp 0.0; decrease_pp 0.0",
             "actual": "match", "status": "PASS"},
            {"id": "shapes", "description": "scenario file shapes",
             "expected": "7 rows x 52 cols x 4 files", "actual": "match", "status": "PASS"},
            {"id": "band-schema", "description": "required per-band columns present",
             "expected": "all required columns", "actual": "present", "status": "PASS"},
            {"id": "quarantine", "description": "no quarantined-Profit column",
             "expected": "absent from all 4 CSVs", "actual": "absent", "status": "PASS"},
            {"id": "grain", "description": "ORDER basis, baseline bands, band order",
             "expected": "basis ORDER all rows; B0-B5 + TOTAL; never re-banded",
             "actual": "ORDER baseline bands", "status": "PASS"},
            {"id": "assumption-labels", "description": "assumption labels on every band row",
             "expected": "CONSTANT_OBSERVED_QUANTITY / FROZEN_MODELED_COGS_PCT / OBSERVED_PASSTHROUGH / OFF",
             "actual": "match", "status": "PASS"},
            {"id": "na-markers", "description": "unlicensed views N/A with reasons on every band row",
             "expected": "COMPARATOR_NOT_IN_INITIAL_BUILD / RESPONSE_NOT_ESTIMATED",
             "actual": "match", "status": "PASS"},
            {"id": "flags", "description": "low_sample_flag FALSE on every band row",
             "expected": "FALSE x 28 rows", "actual": "all FALSE", "status": "PASS"},
            {"id": "counts-per-band", "description": "frozen order counts + quantities per band",
             "expected": "2055/415/1634/278/274/353/5009 and band quantities x 4",
             "actual": "match", "status": "PASS"},
            {"id": "negatives", "description": "baseline neg distribution + hypo counts valid",
             "expected": "14/3/24/1/3/5/50 x 4; hypo nonneg ints", "actual": "match", "status": "PASS"},
            {"id": "band-totals-reconcile", "description": "band rows sum to TOTAL per instance",
             "expected": "counts/currency reconciled within 0.05 x 4", "actual": "reconciled", "status": "PASS"},
            {"id": "baseline-identical", "description": "TOTAL baselines identical across instances",
             "expected": "base_contrib identical within 0.05", "actual": "identical", "status": "PASS"},
            {"id": "baseline-frozen", "description": "TOTAL baseline equals frozen baseline",
             "expected": f"{EXPECTED_CONTRIB} +/- {TOL}", "actual": "match", "status": "PASS"},
            {"id": "variance-reconcile", "description": "per-band stored variances equal hypo-base",
             "expected": "4 currency pairs x 7 bands x 4 instances, gaps <= 1e-9",
             "actual": "reconciled", "status": "PASS"},
            {"id": "freight-zero", "description": "freight/CTS variance exactly 0 per band",
             "expected": "0.0 x 28 band rows", "actual": "zero", "status": "PASS"},
            {"id": "margin-pp", "description": "per-band stored pp change equals recomputed",
             "expected": "7 bands x 4 instances, gaps <= 1e-9", "actual": "recomputed", "status": "PASS"},
        ],
        "limitations": [
            "Baseline bands only; never re-banded by hypothetical discounts.",
            "Identity slices show zero variance by construction (integrity, not economics).",
            "Nonzero universal pp shifts have no valid band output and do not appear here.",
            "No LINE-basis scenario detail; no disaggregation into order-level hypotheticals.",
            "Conditional illustration under stated assumptions; not a forecast.",
        ],
        "failure_behavior": [
            "Missing file fails [inputs-exist] before any further I/O.",
            "Non-PASS or malformed quality evidence fails [quality-status].",
            "CSV/evidence sha mismatch fails [quality-chain] before loading.",
            "Wrong schema, band order, or basis fails loudly; any failed check writes no outputs.",
        ],
        "determinism": "Fixed instance/band/block/metric ordering, repr() numeric formatting, no timestamps, no randomness, no environment-dependent values.",
        "outputs": {
            OUT_CSV_NAME: {"rows": len(rows), "sha256": sha256(out_csv)},
        },
    }
    with open(out_json, "w", encoding="utf-8", newline="\n") as f:
        json.dump(quality, f, indent=2)
        f.write("\n")
    quality["outputs"][OUT_CSV_NAME]["sha256"] = sha256(out_csv)
    with open(out_json, "w", encoding="utf-8", newline="\n") as f:
        json.dump(quality, f, indent=2)
        f.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
