"""MarginMap Phase 4C (slice 5) — AO-05 Order-Level Baseline Reading.

Scope (per docs/PHASE_4C_ANALYTICAL_INTERPRETATION_DESIGN.md, AO-05):
  ONE observed-baseline reading at order grain, preserving order-level
  visibility (WAD distribution, negative-contribution orders, the single
  ambiguity-noted order, quantity and line-count context) that band
  aggregates average over. Supporting — never replacing — band readings.
  No scenarios, no visuals, no forecasts, no causal claims. Return status
  is filter context only (UNKNOWN never defaulted).

Inputs (READ-ONLY — never modified, never regenerated by this script):
    data/processed/discount_order_summary.csv  (5,009 rows; authoritative
                                                contribution joined with
                                                line-derived discount rollup)
    data/processed/order_margin_map_phase2.csv (5,009 rows; independent
                                                 rollup cross-check)
    data/processed/phase3b_quality_report.json (16/16 PASS upstream standing)

Outputs (NEW files only; written after every validation check passes):
    data/processed/phase4c_order_reading.csv
    data/processed/phase4c_order_reading_quality.json

Usage (all paths have frozen defaults; overrides exist ONLY so that
missing/invalid-input behavior can be tested without touching frozen files):
    python src/data/build_phase4c_order_reading.py

Rules (frozen definitions restated — not redefined):
    one row per order_id; margins SUM/SUM-consistent per order (recomputed,
    never averaged); WAD gross-revenue-weighted per order; each order
    carries exactly one baseline band; hypothetical order-level scenario
    detail does not exist and is never fabricated.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
ORDER_SUMMARY_CSV = ROOT / "data" / "processed" / "discount_order_summary.csv"
ORDER_CSV = ROOT / "data" / "processed" / "order_margin_map_phase2.csv"
QUALITY_JSON = ROOT / "data" / "processed" / "phase3b_quality_report.json"
OUT_DIR = ROOT / "data" / "processed"
OUT_CSV_NAME = "phase4c_order_reading.csv"
OUT_JSON_NAME = "phase4c_order_reading_quality.json"

# ---- frozen expectations (Phase 2 / Phase 3B freeze records) ------------------
EXPECTED_ORDERS = 5009
EXPECTED_BANDS = {"B0": 2055, "B1": 415, "B2": 1634, "B3": 278,
                  "B4": 274, "B5": 353}
EXPECTED_NEG_ORDERS = 50
EXPECTED_RETURN_YES = 296
EXPECTED_RETURN_UNKNOWN = 1
EXPECTED_UNKNOWN_ORDER = "CA-2015-102015"
EXPECTED_AMBIGUOUS_ORDER = "US-2014-150119"
EXPECTED_AMBIGUOUS_FREIGHT = 26.55
EXPECTED_AMBIGUOUS_NOTE = "ORDER_CONTAINS_AMBIGUOUS_PAIR_25P05_HELD_AT_ORDER"
ROLLUP_TOL = 1e-6  # order rollup vs order fact (design mandate)
RATIO_TOL = 1e-6  # per-order margin/WAD recomputation tolerance
TOL = 0.05  # currency total cross-check tolerance

# ---- frozen input hashes (all prior freeze records) ---------------------------
FROZEN_HASHES = {
    "discount_order_summary.csv":
        "17389c40b45823a3046f17c33f8a77bac3acc39896b33ce3ae19bb7306a521d2",
    "order_margin_map_phase2.csv":
        "ae6c349c9995747f2fef91cf1db6b940a73d99d6b2fede5ff3dff918f429d267",
}

QUARANTINE_COL = "source_profit_quarantined"
OUTPUT_NAME = "Order-level baseline reading"
SCENARIO_STATUS = "OBSERVED BASELINE"
GRAIN = "Order"

REQUIRED_COLS = {"order_id", "discount_band", "order_return_status",
                 "line_count", "negative_contribution_flag", "ambiguity_note",
                 "wad", "revenue_realization_rate", "net_revenue",
                 "gross_revenue", "modeled_gross_profit",
                 "modeled_gross_margin_pct", "freight_cost", "cost_to_serve",
                 "contribution_profit", "contribution_margin_pct", "quantity",
                 "discount_amount", "customer_id", "segment",
                 "contribution_authority", "low_sample_flag"}


def fail(check: str, expected: str, actual: str) -> "NoReturn":
    raise SystemExit(
        f"VALIDATION FAILED [{check}]\n  Expected: {expected}\n  Actual:   {actual}"
    )


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Phase 4C slice 5: AO-05 order-level baseline reading.")
    p.add_argument("--order-summary-csv", type=Path, default=ORDER_SUMMARY_CSV)
    p.add_argument("--order-csv", type=Path, default=ORDER_CSV)
    p.add_argument("--quality-json", type=Path, default=QUALITY_JSON)
    p.add_argument("--out-dir", type=Path, default=OUT_DIR)
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    summary_csv, order_csv, quality_path = (
        args.order_summary_csv, args.order_csv, args.quality_json)
    out_dir = args.out_dir

    # ---- 1. source-artifact identity (fail-loud before any further I/O) --------
    for label, path in (("order summary", summary_csv),
                        ("order fact", order_csv),
                        ("quality report", quality_path)):
        if not path.is_file():
            fail("inputs-exist", f"{label} present at {path}", "file missing")

    hashes = {name: sha256(p) for name, p in
              (("discount_order_summary.csv", summary_csv),
               ("order_margin_map_phase2.csv", order_csv))}
    for name, digest in hashes.items():
        if digest != FROZEN_HASHES[name]:
            fail("frozen-inputs", FROZEN_HASHES[name], digest)

    # ---- 2. upstream standing: 16/16 PASS, unique IDs ------------------------------
    try:
        q = json.loads(quality_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as e:
        fail("upstream-standing", "phase3b_quality_report.json valid JSON",
             f"parse error: {e}")
    qchecks = q.get("checks", [])
    qids = [c.get("id") for c in qchecks]
    # NOTE: the frozen upstream record carries 16 checks with one reused ID
    # ('frozen' appears twice); uniqueness is therefore asserted for AO-05's
    # own checks only, while upstream standing requires 16 checks, all PASS.
    if len(qchecks) != 16:
        fail("upstream-standing", "16 checks",
             f"{len(qchecks)} checks / {len(set(qids))} unique IDs")
    if any(c.get("status") != "PASS" for c in qchecks):
        bad = [c.get("id") for c in qchecks if c.get("status") != "PASS"]
        fail("upstream-standing", "all 16 checks PASS", f"non-PASS: {bad}")

    # ---- 3. load ----------------------------------------------------------------------
    summary = pd.read_csv(summary_csv)
    orders = pd.read_csv(order_csv)
    if QUARANTINE_COL in summary.columns or "profit" in summary.columns:
        fail("quarantine", "no quarantined-Profit column", "profit column present")
    if REQUIRED_COLS - set(summary.columns):
        fail("order-schema", f"columns {sorted(REQUIRED_COLS)}",
             f"columns {list(summary.columns)}")
    if len(summary) != EXPECTED_ORDERS or summary["order_id"].nunique() != EXPECTED_ORDERS:
        fail("inputs", f"{EXPECTED_ORDERS} unique orders",
             f"{len(summary)} rows / {summary['order_id'].nunique()} unique")
    if len(orders) != EXPECTED_ORDERS or orders["order_id"].nunique() != EXPECTED_ORDERS:
        fail("inputs", f"{EXPECTED_ORDERS} unique orders in fact",
             f"{len(orders)} rows / {orders['order_id'].nunique()} unique")
    if set(summary["order_id"]) != set(orders["order_id"]):
        fail("inputs", "summary order set = fact order set", "order sets differ")

    # ---- 4. bands: exactly one per order, frozen distribution ----------------------------
    if summary["discount_band"].isna().any():
        fail("band-coverage", "exactly one band per order (no NULL)",
             "NULL band found")
    if set(summary["discount_band"].unique()) - set(EXPECTED_BANDS):
        fail("band-coverage", f"bands subset of {sorted(EXPECTED_BANDS)}",
             repr(summary["discount_band"].unique().tolist()))
    band_counts = summary["discount_band"].value_counts().to_dict()
    for band, expected in EXPECTED_BANDS.items():
        if int(band_counts.get(band, 0)) != expected:
            fail("band-coverage", f"{band} orders {expected}",
                 repr(band_counts.get(band, 0)))

    # ---- 5. authority + flags ----------------------------------------------------------------
    if not bool((summary["contribution_authority"] == "AUTHORITATIVE_ORDER").all()):
        fail("authority", "all rows AUTHORITATIVE_ORDER",
             repr(summary["contribution_authority"].unique().tolist()))
    if bool(summary["low_sample_flag"].fillna(False).any()):
        fail("flags", "low_sample_flag FALSE (single-observation convention)",
             "TRUE flag found")

    # ---- 6. rollups vs order fact (<=1e-6, design mandate) --------------------------------------
    for col, fact_col in (("net_revenue", "order_revenue"),
                          ("modeled_cogs", "order_cogs"),
                          ("freight_cost", "order_freight"),
                          ("cost_to_serve", "order_cost_to_serve"),
                          ("contribution_profit", "order_contribution_profit")):
        gap = abs(float(summary[col].sum()) - float(orders[fact_col].sum()))
        if gap > ROLLUP_TOL:
            fail("rollups", f"{col} rollup gap <= {ROLLUP_TOL}", repr(gap))

    # ---- 7. per-order ratio discipline (recomputed, never averaged) -------------------------------
    bad_margin = 0
    bad_wad = 0
    for r in summary.itertuples():
        net = float(r.net_revenue)
        if abs(float(r.contribution_profit) / net * 100
               - float(r.contribution_margin_pct)) > RATIO_TOL:
            bad_margin += 1
        if abs(float(r.modeled_gross_profit) / net * 100
               - float(r.modeled_gross_margin_pct)) > RATIO_TOL:
            bad_margin += 1
        if abs(float(r.discount_amount) / float(r.gross_revenue)
               - float(r.wad)) > RATIO_TOL:
            bad_wad += 1
        if abs(float(r.net_revenue) / float(r.gross_revenue) * 100
               - float(r.revenue_realization_rate)) > RATIO_TOL:
            bad_wad += 1
    if bad_margin:
        fail("margins-recomputed", "SUM/SUM-consistent margins on all orders",
             f"{bad_margin} mismatches")
    if bad_wad:
        fail("wad-recomputed", "gross-weighted WAD/realization on all orders",
             f"{bad_wad} mismatches")

    # ---- 8. negative flags: 50, exactly matching contrib<0 ----------------------------------------------
    neg_flag = summary["negative_contribution_flag"].fillna(False).astype(bool)
    if int(neg_flag.sum()) != EXPECTED_NEG_ORDERS:
        fail("negatives", f"{EXPECTED_NEG_ORDERS} flagged orders",
             str(int(neg_flag.sum())))
    neg_value = summary["contribution_profit"] < 0
    if bool((neg_flag != neg_value).any()):
        fail("negatives", "flag TRUE exactly where contribution < 0",
             f"{int((neg_flag != neg_value).sum())} mismatches")

    # ---- 9. ambiguity: exactly one noted order ---------------------------------------------------------
    noted = summary[summary["ambiguity_note"].notna()]
    if len(noted) != 1 or noted.iloc[0]["order_id"] != EXPECTED_AMBIGUOUS_ORDER:
        fail("ambiguity", f"exactly one noted order {EXPECTED_AMBIGUOUS_ORDER}",
             repr(noted["order_id"].tolist()))
    if noted.iloc[0]["ambiguity_note"] != EXPECTED_AMBIGUOUS_NOTE:
        fail("ambiguity", EXPECTED_AMBIGUOUS_NOTE,
             repr(noted.iloc[0]["ambiguity_note"]))
    if abs(float(noted.iloc[0]["freight_cost"]) - EXPECTED_AMBIGUOUS_FREIGHT) > TOL:
        fail("ambiguity", f"noted-order freight {EXPECTED_AMBIGUOUS_FREIGHT}",
             repr(float(noted.iloc[0]["freight_cost"])))

    # ---- 10. attribution + return cohorts ------------------------------------------------------------------
    if summary[["customer_id", "segment"]].isna().any().any():
        fail("attribution", "one non-null customer + segment per order row",
             "NULL customer/segment found")
    rc = summary["order_return_status"].value_counts(dropna=False)
    n_yes, n_unk = int(rc.get("YES", 0)), int(rc.get("UNKNOWN", 0))
    if n_yes != EXPECTED_RETURN_YES or n_unk != EXPECTED_RETURN_UNKNOWN:
        fail("return-cohorts", "YES 296 / UNKNOWN 1", f"YES {n_yes} / UNKNOWN {n_unk}")
    unk_orders = summary.loc[summary["order_return_status"] == "UNKNOWN",
                             "order_id"].tolist()
    if unk_orders != [EXPECTED_UNKNOWN_ORDER]:
        fail("return-cohorts", f"UNKNOWN order never defaulted ({EXPECTED_UNKNOWN_ORDER})",
             repr(unk_orders))
    if n_yes + n_unk + int(rc.get("NOT_RETURNED", 0)) != EXPECTED_ORDERS:
        fail("return-cohorts", f"cohorts sum to {EXPECTED_ORDERS}", "mismatch")

    # ---- 11. grain: no hypothetical/scenario content --------------------------------------------------------------
    for token in ("hypo_", "hypothetical", "scenario_", "variance_"):
        if any(token in c for c in summary.columns):
            fail("grain", "no hypothetical/scenario columns", f"found '{token}'")

    # ---- 12. build deterministic metric table (file order; unique order_id) --------------------------------------------
    rows: list[dict[str, str]] = []

    def sval(value: object) -> str:
        if value is None:
            return ""
        try:
            if pd.isna(value):
                return ""
        except (TypeError, ValueError):
            return str(value)
        if type(value).__module__ == "numpy":
            value = value.item()
            if value is None:
                return ""
        return repr(value) if isinstance(value, float) else str(value)

    METRICS: list[tuple[str, str, str, str, str]] = [
        ("wad", "order_wad", "DEC", "Order WAD (gross-weighted, D3B-03 input)",
         "Never averaged; band assigned from this value"),
        ("revenue_realization_rate", "order_realization", "PCT",
         "Order realization = net/gross x 100", "Complement of discount absorption"),
        ("net_revenue", "order_net", "CUR", "Order net revenue (authoritative)",
         "Authoritative; never subtract discount again"),
        ("gross_revenue", "order_gross", "CUR", "Order gross (derived reference)",
         "Derived reference only; never an observed list price"),
        ("modeled_gross_profit", "order_gross_profit", "CUR",
         "Order gross profit (conditional)", "Excludes serve costs; not contribution"),
        ("modeled_gross_margin", "order_gross_margin", "PCT",
         "Order gross margin, recomputed per order", "Conditional on benchmarks"),
        ("freight_cost", "order_freight", "CUR", "Order freight (observed join)",
         "Observed field, methodology unverified (Phase 2 caveat)"),
        ("cost_to_serve", "order_cts", "CUR", "Order CTS = freight + 0 + 0 (OFF)",
         "Zero means scenario-excluded, never actual cost"),
        ("contribution_profit", "order_contrib", "CUR",
         "Order contribution (authoritative)", "Authoritative order grain; OFF baseline"),
        ("contribution_margin", "order_contrib_margin", "PCT",
         "Order contribution margin, recomputed per order", "Denominator net, never gross"),
        ("quantity", "order_qty", "CT", "Order quantity SUM",
         "Volume context; reused bit-identical in scenarios"),
        ("line_count", "order_lines", "CT", "Order line count",
         "Sample-size companion"),
    ]
    COL = {"wad": "wad", "revenue_realization_rate": "revenue_realization_rate",
           "net_revenue": "net_revenue", "gross_revenue": "gross_revenue",
           "modeled_gross_profit": "modeled_gross_profit",
           "modeled_gross_margin": "modeled_gross_margin_pct",
           "freight_cost": "freight_cost", "cost_to_serve": "cost_to_serve",
           "contribution_profit": "contribution_profit",
           "contribution_margin": "contribution_margin_pct",
           "quantity": "quantity", "line_count": "line_count"}

    for r in summary.itertuples():
        base = {"output_name": OUTPUT_NAME, "scenario_status": SCENARIO_STATUS,
                "grain": GRAIN, "order_id": str(r.order_id),
                "discount_band": str(r.discount_band),
                "return_status": str(r.order_return_status),
                "neg_flag": str(bool(r.negative_contribution_flag)),
                "ambiguity_note": "" if pd.isna(r.ambiguity_note) else str(r.ambiguity_note),
                "source_artifact": "discount_order_summary.csv"}
        for metric, _, unit, dref, lim in METRICS:
            rows.append({**base, "metric_name": metric,
                         "metric_value": sval(getattr(r, COL[metric])),
                         "unit": unit, "definition_ref": dref, "limitation": lim})

    out_csv = out_dir / OUT_CSV_NAME
    out_json = out_dir / OUT_JSON_NAME

    # ---- 13. write outputs only after every check passed ------------------------------------
    out_dir.mkdir(parents=True, exist_ok=True)
    import csv as _csv
    with open(out_csv, "w", newline="", encoding="utf-8") as f:
        w = _csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    quality = {
        "phase": "4C slice 5 — AO-05 order-level baseline reading (observed baseline; not a forecast)",
        "output": {
            "output_name": OUTPUT_NAME,
            "scenario_status": SCENARIO_STATUS,
            "grain": GRAIN,
            "standing": "OBSERVED_BASELINE",
        },
        "inputs": {
            "discount_order_summary.csv": {"rows": len(summary),
                                           "sha256": hashes["discount_order_summary.csv"]},
            "order_margin_map_phase2.csv": {"rows": len(orders),
                                            "sha256": hashes["order_margin_map_phase2.csv"]},
            "phase3b_quality_report.json": {"checks": 16, "status": "all PASS"},
        },
        "checks": [
            {"id": "inputs-exist", "description": "required frozen inputs present",
             "expected": "order summary + order fact + quality report",
             "actual": "present", "status": "PASS"},
            {"id": "frozen-inputs", "description": "frozen hashes match records",
             "expected": "byte-identical SHA-256 (2 files)", "actual": "match", "status": "PASS"},
            {"id": "upstream-standing", "description": "Phase 3B quality 16 checks all PASS",
             "expected": "16 checks all PASS (one reused ID in frozen record)",
             "actual": "16 checks all PASS", "status": "PASS"},
            {"id": "quarantine", "description": "no quarantined-Profit column",
             "expected": "absent from order summary", "actual": "absent", "status": "PASS"},
            {"id": "inputs", "description": "5009 unique orders, sets match fact",
             "expected": "5009 / 5009; sets equal",
             "actual": f"{len(summary)} / {summary['order_id'].nunique()}; sets equal",
             "status": "PASS"},
            {"id": "order-schema", "description": "order summary schema complete",
             "expected": "all 22 required columns", "actual": "present", "status": "PASS"},
            {"id": "band-coverage", "description": "exactly one frozen band per order",
             "expected": "B0 2055 / B1 415 / B2 1634 / B3 278 / B4 274 / B5 353; no NULL",
             "actual": "match", "status": "PASS"},
            {"id": "authority", "description": "all rows AUTHORITATIVE_ORDER",
             "expected": "AUTHORITATIVE_ORDER x 5009", "actual": "all match", "status": "PASS"},
            {"id": "flags", "description": "low_sample_flag FALSE convention",
             "expected": "FALSE x 5009", "actual": "all FALSE", "status": "PASS"},
            {"id": "rollups", "description": "revenue/COGS/freight/CTS/contribution rollups match fact",
             "expected": "gaps <= 1e-6", "actual": "match", "status": "PASS"},
            {"id": "margins-recomputed", "description": "per-order margins recomputed, never averaged",
             "expected": "0 mismatches x 5009 orders", "actual": "0 mismatches", "status": "PASS"},
            {"id": "wad-recomputed", "description": "per-order WAD/realization recomputed, never averaged",
             "expected": "0 mismatches x 5009 orders", "actual": "0 mismatches", "status": "PASS"},
            {"id": "negatives", "description": "50 flags exactly where contribution < 0",
             "expected": "50 / 0 mismatches", "actual": "50 / 0 mismatches", "status": "PASS"},
            {"id": "ambiguity", "description": "exactly one noted order, freight 26.55",
             "expected": "US-2014-150119 / 26.55 / ORDER_CONTAINS_AMBIGUOUS_PAIR_25P05_HELD_AT_ORDER",
             "actual": "match", "status": "PASS"},
            {"id": "attribution", "description": "one non-null customer + segment per order row",
             "expected": "no NULL; unique order_id", "actual": "verified", "status": "PASS"},
            {"id": "return-cohorts", "description": "cohorts sum to 5009; UNKNOWN never defaulted",
             "expected": "YES 296 / UNKNOWN 1 (CA-2015-102015) / NOT_RETURNED 4712",
             "actual": "match", "status": "PASS"},
            {"id": "grain", "description": "order grain only; no hypothetical/scenario columns",
             "expected": "no hypo_/scenario_/variance_ columns", "actual": "clean", "status": "PASS"},
        ],
        "limitations": [
            "Single observations carry no per-row sample-flag meaning beyond FALSE.",
            "Hypothetical order-level scenario detail does not exist and was not fabricated.",
            "Return status is filter context only; identifies no returned line.",
            "Conditional on benchmarks; freight methodology caveat carried.",
            "Descriptive visibility only; no causal attribution.",
        ],
        "failure_behavior": [
            "Missing file fails [inputs-exist] before any further I/O.",
            "Hash mismatch fails [frozen-inputs] before loading.",
            "Non-PASS upstream evidence fails [upstream-standing].",
            "Wrong schema fails [order-schema]; any failed check writes no outputs.",
        ],
        "determinism": "File-ordered rows (unique order_id), fixed metric order, repr() numeric formatting, no timestamps, no randomness, no environment-dependent values.",
        "outputs": {
            OUT_CSV_NAME: {"rows": len(rows), "sha256": sha256(out_csv)},
        },
    }
    # order-schema gate is implemented via REQUIRED_COLS subset check above
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(quality, f, indent=2)
        f.write("\n")
    quality["outputs"][OUT_CSV_NAME]["sha256"] = sha256(out_csv)
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(quality, f, indent=2)
        f.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
