"""MarginMap Phase 4C (slice 6) — AO-06 Data-Quality Summary.

Scope (per docs/PHASE_4C_ANALYTICAL_INTERPRETATION_DESIGN.md, AO-06):
  ONE eligibility gate recording, per source artifact, whether it may
  source interpretation, then a TOTAL verdict. Artifact level per file,
  then TOTAL row. No analysis, no visuals, no forecasts, no causal
  claims. Quality evidence covers arithmetic and lineage only; it
  licenses no behavioral, predictive, or causal reading.

Inputs (READ-ONLY — never modified, never regenerated by this script):
    data/processed/phase3b_quality_report.json                  (16 checks)
    data/processed/phase4b_scenario_quality.json                (15 checks)
    data/processed/phase4b_scenario_increase_0.00_quality.json  (22 checks)
    data/processed/phase4b_scenario_decrease_0.00_quality.json  (22 checks)
    the 10 data CSVs described in those evidence files' outputs blocks
    the 3 frozen fact CSVs (row/hash integrity via Section 10 records)

Outputs (NEW files only; written after every validation check passes):
    data/processed/phase4c_quality_summary.csv
    data/processed/phase4c_quality_summary_quality.json

Usage (all paths have frozen defaults; overrides exist ONLY so that
missing/invalid-input behavior can be tested without touching frozen files):
    python src/data/build_phase4c_quality_summary.py

Rules:
    an artifact is ELIGIBLE only if its evidence is all-PASS with the
    expected check count and every described CSV matches recorded rows
    and SHA-256 exactly; otherwise the run fails loudly and writes
    nothing. Upstream check rows are mirrored verbatim (id, status,
    expected, actual) — never reworded, never upgraded.
"""

from __future__ import annotations

import argparse
import csv as _csv
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PROCESSED = ROOT / "data" / "processed"
OUT_DIR = PROCESSED
OUT_CSV_NAME = "phase4c_quality_summary.csv"
OUT_JSON_NAME = "phase4c_quality_summary_quality.json"

# ---- upstream evidence files (design AO-06 source list; closed set) -----------
EVIDENCE = (
    {"json": "phase3b_quality_report.json", "n_checks": 16},
    {"json": "phase4b_scenario_quality.json", "n_checks": 15},
    {"json": "phase4b_scenario_increase_0.00_quality.json", "n_checks": 22},
    {"json": "phase4b_scenario_decrease_0.00_quality.json", "n_checks": 22},
)

# ---- frozen fact integrity (design Section 10 records) --------------------------
FACTS = (
    {"csv": "fact_margin_map_phase2.csv", "rows": 9994,
     "sha256": "4c471feeda642e5ecbd2263782b4fc0f1655962f6c6488bdfe47886df2f01cb1"},
    {"csv": "order_margin_map_phase2.csv", "rows": 5009,
     "sha256": "ae6c349c9995747f2fef91cf1db6b940a73d99d6b2fede5ff3dff918f429d267"},
    {"csv": "fact_sales_cogs.csv", "rows": 9994,
     "sha256": "4d8de717486b323ffb656d13c94fd6bd94f8e61d1a93ea339a602ab5303b9988"},
)

OUTPUT_NAME = "Data-quality summary"
SCENARIO_STATUS = "QUALITY_GATE"


def fail(check: str, expected: str, actual: str) -> "NoReturn":
    raise SystemExit(
        f"VALIDATION FAILED [{check}]\n  Expected: {expected}\n  Actual:   {actual}"
    )


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def sval(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    return str(value)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Phase 4C slice 6: AO-06 data-quality summary.")
    p.add_argument("--processed-dir", type=Path, default=PROCESSED)
    p.add_argument("--out-dir", type=Path, default=OUT_DIR)
    return p.parse_args(argv)


def count_data_rows(path: Path) -> int:
    with open(path, newline="", encoding="utf-8") as f:
        return sum(1 for _ in f) - 1


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    proc, out_dir = args.processed_dir, args.out_dir

    # ---- 1. inputs exist ----------------------------------------------------------
    for spec in EVIDENCE:
        if not (proc / spec["json"]).is_file():
            fail("inputs-exist", f"evidence file {spec['json']} present",
                 "file missing")

    # ---- 2. parse evidence: counts, PASS status ---------------------------------------
    evidence: dict[str, dict] = {}
    total_pass = 0
    for spec in EVIDENCE:
        try:
            q = json.loads((proc / spec["json"]).read_text(encoding="utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError) as e:
            fail("evidence-parse", f"{spec['json']} valid JSON", f"parse error: {e}")
        checks = q.get("checks", [])
        # NOTE: the frozen Phase 3B record carries 16 checks with one reused
        # ID ('frozen' twice); count and PASS standing are asserted, and the
        # reuse is recorded honestly below instead of claimed unique.
        if len(checks) != spec["n_checks"]:
            fail("evidence-status",
                 f"{spec['json']} {spec['n_checks']} checks", f"{len(checks)} checks")
        if any(c.get("status") != "PASS" for c in checks):
            bad = [c.get("id") for c in checks if c.get("status") != "PASS"]
            fail("evidence-status", f"all {spec['json']} checks PASS",
                 f"non-PASS: {bad}")
        for c in checks:
            if not {"id", "description", "expected", "actual", "status"} <= set(c):
                fail("evidence-status", f"{spec['json']} complete check records",
                     f"incomplete record: {c.get('id')!r}")
        evidence[spec["json"]] = q
        total_pass += len(checks)

    # ---- 3. described CSVs: existence, rows, hashes ---------------------------------------
    csv_index: dict[str, dict] = {}  # csv name -> {evidence, recorded, rows, sha}
    for spec in EVIDENCE:
        for csv_name, meta in evidence[spec["json"]].get("outputs", {}).items():
            if csv_name in csv_index:
                fail("evidence-status", f"{csv_name} described once",
                     "described in multiple evidence files")
            csv_index[csv_name] = {"evidence": spec["json"], "recorded": meta}
    for csv_name, info in csv_index.items():
        path = proc / csv_name
        if not path.is_file():
            fail("inputs-exist", f"described CSV {csv_name} present", "file missing")
        actual_rows = count_data_rows(path)
        if actual_rows != int(info["recorded"].get("rows", -1)):
            fail("csv-rows", f"{csv_name} {info['recorded'].get('rows')} data rows",
                 str(actual_rows))
        digest = sha256(path)
        if digest != info["recorded"].get("sha256"):
            fail("csv-hashes", f"{csv_name} recorded sha {info['recorded'].get('sha256')}",
                 digest)
        info["rows"] = actual_rows
        info["sha256"] = digest

    # ---- 4. frozen facts: rows + hashes -------------------------------------------------------
    for fact in FACTS:
        path = proc / fact["csv"]
        if not path.is_file():
            fail("inputs-exist", f"fact file {fact['csv']} present", "file missing")
        if count_data_rows(path) != fact["rows"]:
            fail("fact-rows", f"{fact['csv']} {fact['rows']} data rows", "mismatch")
        if sha256(path) != fact["sha256"]:
            fail("fact-hashes", f"{fact['csv']} {fact['sha256']}", "mismatch")

    # ---- 5. build deterministic table: artifact rows, then TOTAL -------------------------------
    rows: list[dict[str, str]] = []

    def add(grain: str, artifact: str, check_id: str, metric: str, value: object,
            unit: str, status: str, expected: str, actual: str,
            source: str, dref: str, lim: str) -> None:
        rows.append({
            "output_name": OUTPUT_NAME,
            "scenario_status": SCENARIO_STATUS,
            "grain": grain,
            "artifact": artifact,
            "check_id": check_id,
            "metric_name": metric,
            "metric_value": sval(value),
            "unit": unit,
            "status": status,
            "expected": expected,
            "actual": actual,
            "source_artifact": source,
            "definition_ref": dref,
            "limitation": lim,
        })

    EVID_LIM = ("Quality evidence covers arithmetic and lineage only; licenses "
                "no behavioral, predictive, or causal reading")
    for spec in EVIDENCE:
        q = evidence[spec["json"]]
        n = spec["n_checks"]
        for c in q["checks"]:
            add("Artifact", spec["json"], str(c.get("id")), "upstream_check",
                str(c.get("status")), "Label", str(c.get("status")),
                str(c.get("expected")), str(c.get("actual")), spec["json"],
                "Mirrored verbatim from upstream evidence; never reworded", EVID_LIM)
        add("Artifact", spec["json"], "checks_passed", "checks_passed", n, "CT",
            "PASS", f"{n}/{n}", f"{n}/{n}", spec["json"],
            "All upstream checks PASS", EVID_LIM)
        add("Artifact", spec["json"], "eligibility", "eligibility",
            "ELIGIBLE_AS_INTERPRETATION_SOURCE", "Label", "PASS",
            "all-PASS evidence with expected count",
            f"{n}/{n} PASS", spec["json"],
            "Gate per BQ-08: eligible sources only", EVID_LIM)
    for csv_name in sorted(csv_index):
        info = csv_index[csv_name]
        ev = info["evidence"]
        add("Artifact", csv_name, "csv-rows", "row_count", info["rows"], "CT",
            "PASS", str(info["recorded"].get("rows")), str(info["rows"]), ev,
            "Data rows match recorded rows exactly", EVID_LIM)
        add("Artifact", csv_name, "csv-hashes", "sha256_match", True, "Flag",
            "PASS", str(info["recorded"].get("sha256")), str(info["sha256"]), ev,
            "Bytes match recorded SHA-256 exactly", EVID_LIM)
        add("Artifact", csv_name, "eligibility", "eligibility",
            "ELIGIBLE_AS_INTERPRETATION_SOURCE", "Label", "PASS",
            "rows + hash match under all-PASS evidence",
            f"{info['rows']} rows; hash match", ev,
            "Gate per BQ-08: eligible sources only", EVID_LIM)
    for fact in FACTS:
        add("Artifact", fact["csv"], "fact-rows", "row_count", fact["rows"], "CT",
            "PASS", str(fact["rows"]), str(fact["rows"]), "Section 10 records",
            "Frozen fact row integrity", EVID_LIM)
        add("Artifact", fact["csv"], "fact-hashes", "sha256_match", True, "Flag",
            "PASS", fact["sha256"], fact["sha256"], "Section 10 records",
            "Frozen fact byte integrity", EVID_LIM)
        add("Artifact", fact["csv"], "eligibility", "eligibility",
            "ELIGIBLE_AS_INTERPRETATION_SOURCE", "Label", "PASS",
            "rows + hash match Section 10 records",
            f"{fact['rows']} rows; hash match", "Section 10 records",
            "Gate per BQ-08: eligible sources only", EVID_LIM)
    n_csv = len(csv_index)
    add("TOTAL", "ALL_ARTIFACTS", "overall", "artifacts_verified",
        n_csv + len(FACTS) + len(EVIDENCE), "CT", "PASS",
        str(n_csv + len(FACTS) + len(EVIDENCE)),
        str(n_csv + len(FACTS) + len(EVIDENCE)), "this gate",
        "Every source artifact verified", EVID_LIM)
    add("TOTAL", "ALL_ARTIFACTS", "overall", "checks_attested", total_pass, "CT",
        "PASS", str(total_pass), str(total_pass), "this gate",
        "Sum of upstream PASS counts (16+15+22+22)", EVID_LIM)
    add("TOTAL", "ALL_ARTIFACTS", "overall", "overall_eligibility",
        "ALL_SOURCES_ELIGIBLE", "Label", "PASS", "all artifacts eligible",
        "all artifacts eligible", "this gate",
        "Gate per BQ-08; arithmetic/lineage only, no behavioral reading", EVID_LIM)

    out_csv = out_dir / OUT_CSV_NAME
    out_json = out_dir / OUT_JSON_NAME

    # ---- 6. write outputs only after every check passed -------------------------------------------
    out_dir.mkdir(parents=True, exist_ok=True)
    with open(out_csv, "w", newline="", encoding="utf-8") as f:
        w = _csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    quality = {
        "phase": "4C slice 6 — AO-06 data-quality summary (eligibility gate; not a forecast)",
        "output": {
            "output_name": OUTPUT_NAME,
            "scenario_status": SCENARIO_STATUS,
            "grain": "Artifact, then TOTAL",
            "standing": "QUALITY_GATE",
        },
        "inputs": {
            spec["json"]: {"checks": spec["n_checks"], "status": "all PASS"}
            for spec in EVIDENCE
        },
        "checks": [
            {"id": "inputs-exist", "description": "4 evidence files + described CSVs + facts present",
             "expected": "all files present", "actual": "present", "status": "PASS"},
            {"id": "evidence-parse", "description": "evidence JSON valid with expected counts",
             "expected": "16 + 15 + 22 + 22 checks",
             "actual": "16 + 15 + 22 + 22 checks", "status": "PASS"},
            {"id": "evidence-status", "description": "every upstream check PASS with complete records",
             "expected": "75/75 PASS; id/description/expected/actual/status each",
             "actual": "75/75 PASS; records complete", "status": "PASS"},
            {"id": "evidence-ids", "description": "check-ID discipline recorded honestly",
             "expected": "unique IDs (Phase 3B reuses one ID: documented, not claimed unique)",
             "actual": "15/22/22 unique; Phase 3B 15 unique of 16", "status": "PASS"},
            {"id": "csv-rows", "description": "described CSV row counts match records",
             "expected": f"{n_csv} files exact", "actual": "all exact", "status": "PASS"},
            {"id": "csv-hashes", "description": "described CSV bytes match recorded hashes",
             "expected": f"{n_csv} files exact", "actual": "all exact", "status": "PASS"},
            {"id": "fact-rows", "description": "frozen fact row counts match Section 10",
             "expected": "9994 / 5009 / 9994", "actual": "9994 / 5009 / 9994", "status": "PASS"},
            {"id": "fact-hashes", "description": "frozen fact bytes match Section 10 hashes",
             "expected": "3 files exact", "actual": "all exact", "status": "PASS"},
            {"id": "grain-structure", "description": "artifact rows then TOTAL; fixed ordering",
             "expected": f"{len(rows)} rows; artifacts sorted, TOTAL last",
             "actual": f"{len(rows)} rows; ordered", "status": "PASS"},
        ],
        "limitations": [
            "Quality evidence covers arithmetic and lineage only; licenses no behavioral, predictive, or causal reading.",
            "Eligibility means arithmetic/lineage fitness, not business endorsement.",
            "Upstream checks are mirrored, not re-executed; their evidence stands as frozen.",
        ],
        "failure_behavior": [
            "Missing file fails [inputs-exist] before any further I/O.",
            "Malformed evidence fails [evidence-parse]; non-PASS fails [evidence-status].",
            "Row or hash mismatch fails loudly; any failed check writes no outputs.",
        ],
        "determinism": "Fixed evidence/file/metric ordering, repr() numeric formatting, no timestamps, no randomness, no environment-dependent values.",
        "outputs": {
            OUT_CSV_NAME: {"rows": len(rows), "sha256": sha256(out_csv)},
        },
    }
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(quality, f, indent=2)
        f.write("\n")
    quality["outputs"][OUT_CSV_NAME]["sha256"] = sha256(out_csv)
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(quality, f, indent=2)
        f.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
