"""MarginMap Phase 4B — uniform discount-decrease scenario (percentage-point input).

Scope (per docs/PHASE_4B_DESIGN_DISCOUNT_DECREASE.md):
  ONE discount-decrease scenario at a single stated percentage-point decrement,
  applied to all valid lines; line-level hypotheticals aggregated bottom-up to
  orders; Order x Discount Band reporting only. Constant observed quantity,
  frozen modeled-COGS percentage, observed freight passthrough, return/support
  OFF.

  Every figure produced here is hypothetical arithmetic sensitivity under
  stated assumptions. Not a forecast, not a demand statement, not evidence
  about what would have sold, not a pricing recommendation.

Inputs (READ-ONLY — never modified, never regenerated by this script):
    data/processed/fact_margin_map_phase2.csv    (line grain, 9,994 rows)
    data/processed/order_margin_map_phase2.csv   (order grain, 5,009 rows;
                                                 authoritative contribution)

Outputs (NEW files only; names carry the stated decrease for traceability):
    data/processed/phase4b_scenario_decrease_<delta>.csv
    data/processed/phase4b_scenario_decrease_<delta>_quality.json

Usage (decrease is a required, visible CLI argument — never hidden in code):
    python src/data/build_phase4b_decrease_scenarios.py --decrease-pp 0.00

    Decimal-fraction scale only: 0.05 means a decrease of 5 percentage points.
    Display-scale values such as 5 are rejected as out-of-range.

Formulas (frozen Phase 1A definitions restated — not redefined; quantity q
held constant throughout):
    gross(line)            = sales / (1 - d)            [d = observed discount]
    d'(line)               = round6(round6(d) - decrease)
    hypo_net(line)         = gross * (1 - d')
                           = sales * (1 - d') / (1 - d)  (dual form, reconciled)
    hypo_discount_amt      = gross - hypo_net
    hypo_cogs(line)        = hypo_net * modeled_cogs_pct / 100
                             (modeled_cogs_pct = frozen Phase 1 percentage,
                              e.g. 60.0 = 60%; verified per line against the
                              baseline identity modeled_cogs == net * pct/100)
    freight                = freight_cost_observed unchanged (NULL preserved)
    hypo_cts(order)        = authoritative order_freight + 0 + 0
    hypo_contrib(order)    = SUM(hypo_net) - SUM(hypo_cogs) - order_freight
    band(order)            = baseline observed order-WAD band (D3B-03 rule),
                             so the B0 reference cohort stays identifiable
    variance               = hypothetical - baseline (reconciled both ways)
    margin change          = hypothetical_margin_pp - baseline_margin_pp

Invalid-discount contract (AUTHORITATIVE — see design sections 9 and 21):
  permitted d' range is [0.00, 0.80]. If ANY computed d' falls outside that
  range, the ENTIRE run fails before any output is written. No clipping, no
  extrapolation, no silent correction, no dropped lines, no partial-subset
  execution. Negative decreases fail as the wrong slice type; display-scale
  values fail the decrease-bounds gate.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
LINE_CSV = ROOT / "data" / "processed" / "fact_margin_map_phase2.csv"
ORDER_CSV = ROOT / "data" / "processed" / "order_margin_map_phase2.csv"
OUT_DIR = ROOT / "data" / "processed"

# ---- frozen baseline expectations (Phase 1 / Phase 2 freeze records) --------
EXPECTED_LINES = 9994
EXPECTED_ORDERS = 5009
EXPECTED_REV = 2297200.8603
EXPECTED_COGS = 1493910.1285
EXPECTED_FREIGHT = 238173.79
EXPECTED_CONTRIB = 565116.9418
EXPECTED_QTY = 37873  # frozen Phase 1 total quantity (see PHASE_1_FREEZE.md)
TOL = 0.05  # currency tolerance for source-total reconciliation only

# ---- scenario bounds (approved Gates 2/7 + design sections 5/9) -------------
DECREASE_MIN = 0.00
DECREASE_MAX = 0.80
DPRIME_MIN = 0.00
DPRIME_MAX = 0.80

# ---- reporting thresholds (provisional, carried from D3B-02) -----------------
MIN_LINE_COUNT = 30
MIN_ORDER_COUNT = 10

BAND_ORDER = ["B0", "B1", "B2", "B3", "B4", "B5"]
QUARANTINE_COL = "source_profit_quarantined"
STANDING = "HYPOTHETICAL_ARITHMETIC_SENSITIVITY_NOT_A_FORECAST"


def fail(check: str, expected: str, actual: str) -> "NoReturn":
    raise SystemExit(
        f"VALIDATION FAILED [{check}]\n  Expected: {expected}\n  Actual:   {actual}"
    )


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def assign_band(d: float) -> str | None:
    """Fixed six-band mapping (D3B-01, reused unchanged)."""
    if d is None or (isinstance(d, float) and np.isnan(d)):
        return None
    if d == 0:
        return "B0"
    if 0 < d <= 0.15:
        return "B1"
    if 0.15 < d <= 0.25:
        return "B2"
    if 0.25 < d <= 0.35:
        return "B3"
    if 0.35 < d <= 0.55:
        return "B4"
    if 0.55 < d <= 0.80:
        return "B5"
    return None


def parse_args(argv: list[str] | None = None) -> float:
    p = argparse.ArgumentParser(
        description="Phase 4B: uniform discount-decrease scenario "
                    "(percentage-point input, decimal scale).")
    p.add_argument("--decrease-pp", type=float, required=True,
                   help="Stated uniform decrease in decimal fraction, e.g. "
                        "0.05 for a decrease of 5 percentage points. Must lie "
                        "within [0.00, 0.80]; negatives, display-scale values, "
                        "and anything else outside fail the entire run.")
    decrease = p.parse_args(argv).decrease_pp
    # decrease-exists: present and numeric (argparse guarantees presence and
    # float parsing; NaN/inf are still rejected here before any file I/O).
    if not isinstance(decrease, float) or not np.isfinite(decrease):
        fail("decrease-exists",
             "a finite numeric value for --decrease-pp",
             f"--decrease-pp {decrease!r}")
    # decrease-sign: this slice is decrease-only; negatives are the
    # separately gated increase type and must not enter here.
    if decrease < DECREASE_MIN:
        fail("decrease-sign",
             f"stated decrease >= {DECREASE_MIN:.2f} (decrease-only slice; "
             "negatives belong to the increase slice)",
             f"--decrease-pp {decrease}")
    # decrease-bounds: decimal scale only; display-scale values (e.g. 5)
    # fail here with a scale hint.
    if decrease > DECREASE_MAX:
        hint = ""
        if decrease >= 1.0:
            hint = " (display-scale value suspected: use decimal, e.g. 0.05)"
        fail("decrease-bounds",
             f"stated decrease within [{DECREASE_MIN:.2f}, "
             f"{DECREASE_MAX:.2f}] in decimal fraction{hint}",
             f"--decrease-pp {decrease}")
    return decrease


def main(argv: list[str] | None = None) -> None:
    decrease = parse_args(argv)
    scenario_id = f"discount_decrease_pp_{decrease:.2f}"
    checks: list[dict] = []

    def record(check_id: str, description: str, expected: str, actual: str,
               status: str = "PASS") -> None:
        checks.append({"id": check_id, "description": description,
                       "expected": expected, "actual": actual, "status": status})

    for p in [LINE_CSV, ORDER_CSV]:
        if not p.is_file():
            fail("input-exists", f"file at {p}", "NOT FOUND")
    line_hash_before = sha256(LINE_CSV)
    order_hash_before = sha256(ORDER_CSV)

    # ---- decrease input gates recorded (parsing already passed) --------------
    record("decrease-exists", "stated decrease present and numeric",
           "finite numeric --decrease-pp", f"{decrease}")
    record("decrease-sign", "decrease-only slice rejects negatives",
           f"decrease >= {DECREASE_MIN:.2f}", f"{decrease}")
    record("decrease-bounds", "stated decrease within decimal bounds",
           f"[{DECREASE_MIN:.2f}, {DECREASE_MAX:.2f}] decimal fraction",
           f"{decrease}")

    # ---- load (quarantined Profit column never loaded) ----------------------
    line_cols = pd.read_csv(LINE_CSV, nrows=0).columns.tolist()
    use_cols = [c for c in line_cols if c != QUARANTINE_COL]
    e = pd.read_csv(LINE_CSV, usecols=use_cols, dtype={"postal_code": str})
    o = pd.read_csv(ORDER_CSV)
    if QUARANTINE_COL in e.columns or QUARANTINE_COL in o.columns:
        fail("quarantine-excluded", f"{QUARANTINE_COL} absent from working frames",
             "column present")
    record("quarantine", "quarantined Profit excluded from computations",
           f"{QUARANTINE_COL} never loaded", "excluded")

    # ---- freight snapshot (load-time originals for genuine passthrough ------
    # ---- comparison later; the transformed column is never both sides) ------
    freight_snapshot = e["freight_cost_observed"].copy()
    ambiguity_snapshot = e["freight_ambiguity_flag"].copy()

    # ---- frozen input shape / identity --------------------------------------
    if len(e) != EXPECTED_LINES:
        fail("input-lines", f"{EXPECTED_LINES} lines", f"{len(e)}")
    if len(o) != EXPECTED_ORDERS or o["order_id"].nunique() != EXPECTED_ORDERS:
        fail("input-orders", f"{EXPECTED_ORDERS} unique orders",
             f"{len(o)} rows / {o['order_id'].nunique()} unique")
    if e["row_id"].nunique() != EXPECTED_LINES:
        fail("row-unique", f"{EXPECTED_LINES} unique row_id",
             f"{e['row_id'].nunique()}")
    record("inputs", "frozen input shapes",
           "9994 lines / 5009 unique orders",
           f"{len(e)} lines / {len(o)} orders")

    # ---- scenarios OFF in the baseline inputs --------------------------------
    if bool(e["return_processing_scenario_enabled"].any()) or \
            bool((e["return_processing_cost_scenario"] != 0).any()) or \
            bool(e["support_scenario_enabled"].any()) or \
            bool((e["support_cost_scenario"] != 0).any()):
        fail("scenarios-off", "return+support OFF/zero in line fact", "enabled")
    if bool((o["order_return_processing_cost_scenario"] != 0).any()) or \
            bool((o["order_support_cost_scenario"] != 0).any()):
        fail("scenarios-off-order", "return+support OFF/zero in order fact",
             "non-zero")
    record("scenarios-off", "return/support scenario layers remain OFF",
           "all flags FALSE and costs 0", "OFF confirmed")

    # ---- observed discount range ---------------------------------------------
    if bool(e["discount"].isna().any()):
        fail("discount-range", "no NULL observed discounts",
             f"{int(e['discount'].isna().sum())} NULL")
    bad = e[(e["discount"] < 0) | (e["discount"] >= 1)]
    if len(bad):
        fail("discount-range", "all observed discounts within [0, 1)",
             f"{len(bad)} outside")
    record("discount-range", "observed discounts within valid range",
           "[0, 1); no NULL", f"[{e['discount'].min()}, {e['discount'].max()}]")

    # ---- ambiguity scope (preserved, never imputed) ---------------------------
    ambig = e[e["freight_ambiguity_flag"]]
    if len(ambig) != 2 or ambig["order_id"].nunique() != 1:
        fail("ambiguity-scope", "exactly 2 flagged lines in one order",
             f"{len(ambig)} lines / {ambig['order_id'].nunique()} orders")
    if bool(ambig["freight_cost_observed"].notna().any()):
        fail("no-imputation", "flagged lines carry NULL freight", "value present")
    ambig_order = ambig["order_id"].iloc[0]
    record("ambiguity", "ambiguous freight pair preserved (NULL, flagged)",
           "2 lines NULL freight in one order", f"2 lines in {ambig_order}")

    # ---- line-level hypotheticals (quantity held constant) --------------------
    e = e.copy()
    e["discount_r"] = e["discount"].astype(float).round(6)
    # Gross reconstruction (frozen Phase 1A formula; d < 1 proven above).
    e["gross_revenue"] = e["sales"] / (1.0 - e["discount_r"])
    e["discount_amount"] = e["gross_revenue"] - e["net_revenue"]
    gap = float((e["discount_amount"]
                 - e["gross_revenue"] * e["discount_r"]).abs().max())
    if gap > 1e-6:
        fail("gross-dual", "gross/discount dual forms reconcile", f"{gap}")
    # Decrease arithmetic: d' = round6(round6(d) - decrease), per design sec 8.
    e["hypothetical_discount"] = (e["discount_r"] - decrease).round(6)
    # discount-bounds-per-line: whole-run fail-loud; never clip, drop, or
    # run on a partial subset. Diagnostic carries row_ids/counts/values.
    viol = e[(e["hypothetical_discount"] < DPRIME_MIN)
             | (e["hypothetical_discount"] > DPRIME_MAX)]
    if len(viol):
        sample_ids = viol["row_id"].head(10).tolist()
        fail("discount-bounds-per-line",
             f"every d' within [{DPRIME_MIN:.2f}, {DPRIME_MAX:.2f}] "
             "(no clipping, no dropped lines, no partial subset)",
             f"{len(viol)} lines violate bounds; "
             f"min d'={float(e['hypothetical_discount'].min()):.6f}; "
             f"max d'={float(e['hypothetical_discount'].max()):.6f}; "
             f"sample row_ids={sample_ids}")
    record("discount-bounds-per-line",
           "every resulting discount within [0.00, 0.80]",
           "0 violations; no clipping/drops/partial runs",
           f"min d'={float(e['hypothetical_discount'].min()):.6f}")
    # Universal all-valid-lines scope: nothing silently excluded.
    if len(e) != EXPECTED_LINES or e["row_id"].nunique() != EXPECTED_LINES:
        fail("no-silent-exclusion", f"{EXPECTED_LINES} lines in scope",
             f"{len(e)} rows / {e['row_id'].nunique()} unique")
    record("no-silent-exclusion", "universal scope preserved, nothing dropped",
           f"{EXPECTED_LINES} lines / {EXPECTED_ORDERS} orders in scope",
           f"{len(e)} lines in scope")
    e["hypothetical_net_revenue"] = (e["gross_revenue"]
                                     * (1.0 - e["hypothetical_discount"]))
    # Dual form: hypo_net == sales * (1 - d') / (1 - d). Reconciled, not assumed.
    gap2 = float((e["hypothetical_net_revenue"] - e["sales"]
                  * (1.0 - e["hypothetical_discount"])
                  / (1.0 - e["discount_r"])).abs().max())
    if gap2 > 1e-6:
        fail("hypo-revenue-dual-subtractive",
             "hypothetical revenue dual forms reconcile", f"{gap2}")
    record("hypo-revenue-dual-subtractive",
           "subtractive hypo revenue dual forms reconcile",
           "max gap <= 1e-6", f"{gap2:.2e}")
    e["hypothetical_discount_amount"] = (e["gross_revenue"]
                                         - e["hypothetical_net_revenue"])
    # Hypothetical COGS from the frozen line-level percentage.
    # Baseline identity asserted first: modeled_cogs == net * pct/100.
    base_gap = float((e["modeled_cogs"] - e["net_revenue"]
                      * e["modeled_cogs_pct"] / 100.0).abs().max())
    if base_gap > 1e-6:
        fail("cogs-pct-identity", "baseline COGS matches frozen percentage",
             f"{base_gap}")
    e["hypothetical_cogs"] = (e["hypothetical_net_revenue"]
                              * e["modeled_cogs_pct"] / 100.0)
    record("hypo-lines", "line hypotheticals computed (quantity constant)",
           "dual-form gaps <= 1e-6", f"gross {gap:.2e}; "
                                     f"cogs-pct {base_gap:.2e}")
    # Freight passthrough: values carried unchanged, NULLs preserved.
    # Genuine snapshot comparison: post-transform values vs the
    # load-time originals — never the transformed column against itself.
    if not e["freight_cost_observed"].equals(freight_snapshot):
        fail("freight-passthrough", "freight values bit-identical to load",
             "difference detected")
    if not e["freight_ambiguity_flag"].equals(ambiguity_snapshot):
        fail("freight-passthrough", "ambiguity flags unchanged", "changed")
    if int(e["freight_cost_observed"].isna().sum()) != 2:
        fail("freight-passthrough", "exactly 2 NULL freight values preserved",
             f"{int(e['freight_cost_observed'].isna().sum())} NULL")
    record("freight-passthrough", "observed freight passed through unchanged",
           "values identical; 2 NULL preserved; flags unchanged", "confirmed")

    # ---- baseline order rollup + baseline band (D3B-03 rule) ------------------
    g = e.groupby("order_id", sort=True)
    oroll = pd.DataFrame({
        "line_count": g["row_id"].size(),
        "order_quantity": g["quantity"].sum(),
        "order_gross": g["gross_revenue"].sum(),
        "order_base_net": g["net_revenue"].sum(),
        "order_base_disc": g["discount_amount"].sum(),
        "order_base_cogs_rollup": g["modeled_cogs"].sum(),
        "order_hypo_net": g["hypothetical_net_revenue"].sum(),
        "order_hypo_disc": g["hypothetical_discount_amount"].sum(),
        "order_hypo_cogs": g["hypothetical_cogs"].sum(),
    }).reset_index()
    oroll["order_wad_baseline"] = (oroll["order_base_disc"]
                                   / oroll["order_gross"])
    oroll["baseline_band"] = oroll["order_wad_baseline"].round(6).map(assign_band)
    if bool(oroll["baseline_band"].isna().any()):
        fail("order-band-coverage", "every order receives exactly one band",
             f"{int(oroll['baseline_band'].isna().sum())} unassigned")
    if len(oroll) != EXPECTED_ORDERS:
        fail("order-band-reconcile", f"order bands sum to {EXPECTED_ORDERS}",
             f"{len(oroll)}")
    record("order-bands", "baseline order-WAD band assignment (single rule)",
           "5009 orders exactly one band",
           " | ".join(f"{b}={int((oroll['baseline_band'] == b).sum())}"
                      for b in BAND_ORDER))

    # ---- constant observed quantity (explicit assertion) ----------------------
    # Quantity is never assigned, inferred, or recalculated anywhere above:
    # the rollup below only sums the frozen column. Proven, not presumed.
    if int(e["quantity"].sum()) != EXPECTED_QTY:
        fail("quantity-constant", f"line quantity total {EXPECTED_QTY}",
             f"{int(e['quantity'].sum())}")
    if int(oroll["order_quantity"].sum()) != EXPECTED_QTY:
        fail("quantity-constant", f"order quantity total {EXPECTED_QTY}",
             f"{int(oroll['order_quantity'].sum())}")
    record("quantity-constant", "hypothetical quantity equals baseline quantity",
           f"line + order totals {EXPECTED_QTY}; column never transformed",
           f"{int(oroll['order_quantity'].sum())}")

    # ---- join authoritative baseline (never recomputed) -----------------------
    od = oroll.merge(o, on="order_id", validate="one_to_one")
    if len(od) != EXPECTED_ORDERS:
        fail("order-join", "rollup x order fact = 5009", f"{len(od)}")
    # Bottom-up COGS rollup reconciled to the authoritative order fact.
    # Hypothetical COGS still uses ONLY the line-level modeled_cogs_pct;
    # the percentage is never derived from order currency.
    for col, ref in [("order_revenue", "order_base_net"),
                     ("order_cogs", "order_base_cogs_rollup")]:
        gapv = float((od[col] - od[ref]).abs().max())
        if gapv > 1e-6:
            fail("order-reconcile", f"rollup matches order fact {col}", f"{gapv}")
    record("cogs-reconcile", "order COGS rollup matches authoritative order fact",
           "max per-order gap <= 1e-6",
           f"{float((od['order_cogs'] - od['order_base_cogs_rollup']).abs().max()):.2e}")
    tr = float(od["order_revenue"].sum())
    tc = float(od["order_cogs"].sum())
    tp = float(od["order_contribution_profit"].sum())
    tf = float(od["order_freight"].sum())
    if abs(tr - EXPECTED_REV) > TOL:
        fail("frozen-rev", f"revenue {EXPECTED_REV}", f"{tr}")
    if abs(tc - EXPECTED_COGS) > TOL:
        fail("frozen-cogs", f"COGS {EXPECTED_COGS}", f"{tc}")
    if abs(tp - EXPECTED_CONTRIB) > TOL:
        fail("frozen-contrib", f"contribution {EXPECTED_CONTRIB}", f"{tp}")
    if abs(tf - EXPECTED_FREIGHT) > TOL:
        fail("frozen-freight", f"freight {EXPECTED_FREIGHT}", f"{tf}")
    record("frozen", "baseline reconciles to Phase 2 facts",
           f"contrib {EXPECTED_CONTRIB} / freight {EXPECTED_FREIGHT}",
           f"{tp:.4f} / {tf:.2f}")

    # ---- hypothetical order contribution (authoritative freight) --------------
    # Freight enters ONLY via the authoritative order fact (which already
    # holds the 25.05 ambiguous-pair total) — never via line summation.
    od["hypo_cost_to_serve"] = od["order_freight"]  # + 0 + 0 (OFF)
    od["hypo_contribution"] = (od["order_hypo_net"] - od["order_hypo_cogs"]
                               - od["hypo_cost_to_serve"])
    od["hypo_margin"] = np.where(od["order_hypo_net"] == 0, np.nan,
                                 od["hypo_contribution"]
                                 / od["order_hypo_net"] * 100.0)
    od["base_margin"] = np.where(od["order_revenue"] == 0, np.nan,
                                 od["order_contribution_profit"]
                                 / od["order_revenue"] * 100.0)
    od["neg_hypo"] = (od["hypo_contribution"] < 0).astype(int)
    od["neg_base"] = (od["order_contribution_profit"] < 0).astype(int)
    od["has_ambiguity"] = (od["order_id"] == ambig_order).astype(int)

    # ---- Order x Band reporting (baseline bands; hypotheticals beside) --------
    agg = od.groupby("baseline_band", sort=True).agg(
        order_count=("order_id", "nunique"),
        line_count=("line_count", "sum"),
        quantity=("order_quantity", "sum"),
        base_gross=("order_gross", "sum"),
        base_net=("order_revenue", "sum"),
        base_disc=("order_base_disc", "sum"),
        base_cogs=("order_cogs", "sum"),
        base_freight=("order_freight", "sum"),
        base_cts=("order_cost_to_serve", "sum"),
        base_contrib=("order_contribution_profit", "sum"),
        hypo_net=("order_hypo_net", "sum"),
        hypo_disc=("order_hypo_disc", "sum"),
        hypo_cogs=("order_hypo_cogs", "sum"),
        hypo_cts=("hypo_cost_to_serve", "sum"),
        hypo_contrib=("hypo_contribution", "sum"),
        neg_base_orders=("neg_base", "sum"),
        neg_hypo_orders=("neg_hypo", "sum"),
        ambiguity_orders=("has_ambiguity", "sum"),
    ).reset_index().rename(columns={"baseline_band": "band"})
    agg["base_gross_profit"] = agg["base_net"] - agg["base_cogs"]
    agg["hypo_gross_profit"] = agg["hypo_net"] - agg["hypo_cogs"]
    # Variances: hypothetical - baseline, recomputed independently below.
    for stub in ["net_revenue", "discount_amount", "cogs", "freight",
                 "cost_to_serve", "contribution_profit", "gross_profit"]:
        bcol = {"net_revenue": "base_net", "discount_amount": "base_disc",
                "cogs": "base_cogs", "freight": "base_freight",
                "cost_to_serve": "base_cts",
                "contribution_profit": "base_contrib",
                "gross_profit": "base_gross_profit"}[stub]
        hcol = {"net_revenue": "hypo_net", "discount_amount": "hypo_disc",
                "cogs": "hypo_cogs", "freight": "hypo_cts",
                "cost_to_serve": "hypo_cts",
                "contribution_profit": "hypo_contrib",
                "gross_profit": "hypo_gross_profit"}[stub]
        agg[f"variance_{stub}"] = agg[hcol] - agg[bcol]
    # Freight variance must be exactly zero (passthrough proof).
    if float(agg["variance_freight"].abs().max()) > 1e-9:
        fail("variance-freight", "freight variance exactly 0 (passthrough)",
             f"{float(agg['variance_freight'].abs().max()):.2e}")
    agg["base_wad"] = agg["base_disc"] / agg["base_gross"]
    agg["hypo_wad"] = agg["hypo_disc"] / agg["base_gross"]
    agg["base_contrib_margin"] = agg["base_contrib"] / agg["base_net"] * 100.0
    agg["hypo_contrib_margin"] = agg["hypo_contrib"] / agg["hypo_net"] * 100.0
    agg["margin_change_pp"] = (agg["hypo_contrib_margin"]
                               - agg["base_contrib_margin"])
    agg["base_gross_margin"] = agg["base_gross_profit"] / agg["base_net"] * 100.0
    agg["hypo_gross_margin"] = agg["hypo_gross_profit"] / agg["hypo_net"] * 100.0
    agg["gross_margin_change_pp"] = (agg["hypo_gross_margin"]
                                     - agg["base_gross_margin"])
    agg["low_sample_flag"] = ((agg["line_count"] < MIN_LINE_COUNT)
                              | (agg["order_count"] < MIN_ORDER_COUNT))
    # Independent variance reconciliation (recomputed, not copied).
    for stub, h, b in [("net_revenue", "hypo_net", "base_net"),
                       ("contribution_profit", "hypo_contrib", "base_contrib"),
                       ("cogs", "hypo_cogs", "base_cogs")]:
        gapv = float(((agg[h] - agg[b]) - agg[f"variance_{stub}"]).abs().max())
        if gapv > 1e-9:
            fail("variance-reconcile", f"variance_{stub} == hypo - base",
                 f"{gapv}")
    record("variances", "variance arithmetic reconciled both ways",
           "max gap <= 1e-9; freight variance 0", "confirmed")

    # ---- TOTAL row --------------------------------------------------------------
    tot = pd.DataFrame([{
        "band": "TOTAL",
        "order_count": int(agg["order_count"].sum()),
        "line_count": int(agg["line_count"].sum()),
        "quantity": int(agg["quantity"].sum()),
        **{c: float(agg[c].sum()) for c in
           ["base_gross", "base_net", "base_disc", "base_cogs", "base_freight",
            "base_cts", "base_contrib", "hypo_net", "hypo_disc", "hypo_cogs",
            "hypo_cts", "hypo_contrib", "base_gross_profit",
            "hypo_gross_profit", "neg_base_orders", "neg_hypo_orders",
            "ambiguity_orders"]},
    }])
    for stub in ["net_revenue", "discount_amount", "cogs", "freight",
                 "cost_to_serve", "contribution_profit", "gross_profit"]:
        tot[f"variance_{stub}"] = np.nan  # filled below from hypo-base
    out = pd.concat([agg, tot], ignore_index=True)
    for stub, h, b in [("net_revenue", "hypo_net", "base_net"),
                       ("discount_amount", "hypo_disc", "base_disc"),
                       ("cogs", "hypo_cogs", "base_cogs"),
                       ("freight", "hypo_cts", "base_freight"),
                       ("cost_to_serve", "hypo_cts", "base_cts"),
                       ("contribution_profit", "hypo_contrib", "base_contrib"),
                       ("gross_profit", "hypo_gross_profit",
                        "base_gross_profit")]:
        out[f"variance_{stub}"] = out[h] - out[b]
    out["base_wad"] = out["base_disc"] / out["base_gross"]
    out["hypo_wad"] = out["hypo_disc"] / out["base_gross"]
    out["base_contrib_margin"] = out["base_contrib"] / out["base_net"] * 100.0
    out["hypo_contrib_margin"] = out["hypo_contrib"] / out["hypo_net"] * 100.0
    out["margin_change_pp"] = (out["hypo_contrib_margin"]
                               - out["base_contrib_margin"])
    out["base_gross_margin"] = out["base_gross_profit"] / out["base_net"] * 100.0
    out["hypo_gross_margin"] = (out["hypo_gross_profit"] / out["hypo_net"]
                                * 100.0)
    out["gross_margin_change_pp"] = (out["hypo_gross_margin"]
                                     - out["base_gross_margin"])
    out["low_sample_flag"] = ((out["line_count"] < MIN_LINE_COUNT)
                              | (out["order_count"] < MIN_ORDER_COUNT))
    trow = out[out["band"] == "TOTAL"].iloc[0]
    if abs(float(trow["base_contrib"]) - EXPECTED_CONTRIB) > TOL:
        fail("total-baseline", f"TOTAL baseline contrib {EXPECTED_CONTRIB}",
             f"{trow['base_contrib']}")
    if int(trow["order_count"]) != EXPECTED_ORDERS or \
            int(trow["line_count"]) != EXPECTED_LINES:
        fail("total-counts", "TOTAL 5009 orders / 9994 lines",
             f"{trow['order_count']} / {trow['line_count']}")
    record("totals", "TOTAL row reconciles to frozen baseline",
           f"{EXPECTED_ORDERS} orders / contrib {EXPECTED_CONTRIB}",
           f"{int(trow['order_count'])} orders / "
           f"{float(trow['base_contrib']):.4f}")

    # ---- metadata / assumption / N-A layers --------------------------------------
    out["scenario_id"] = scenario_id
    out["scenario_type"] = "discount_decrease"
    out["input_form"] = "decrease_pp"
    out["stated_decrease_pp"] = decrease
    out["scope"] = "all_valid_lines"
    out["basis"] = "ORDER"
    out["result_standing"] = STANDING
    out["quantity_assumption"] = "CONSTANT_OBSERVED_QUANTITY"
    out["cogs_method"] = "FROZEN_MODELED_COGS_PCT"
    out["freight_method"] = "OBSERVED_PASSTHROUGH"
    out["return_support"] = "OFF"
    out["fixed_unit_cost_view"] = "N/A"
    out["fixed_unit_cost_reason"] = "COMPARATOR_NOT_IN_INITIAL_BUILD"
    out["demand_response_view"] = "N/A"
    out["demand_response_reason"] = "RESPONSE_NOT_ESTIMATED"
    for col in ["scenario_id", "scenario_type", "input_form", "scope",
                "basis", "result_standing", "quantity_assumption",
                "cogs_method", "freight_method", "return_support",
                "fixed_unit_cost_view", "fixed_unit_cost_reason",
                "demand_response_view", "demand_response_reason"]:
        if bool(out[col].isna().any()) or bool((out[col] == "").any()):
            fail("metadata-complete", f"metadata column {col} populated",
                 "missing value")
    if not bool(((out["fixed_unit_cost_view"] == "N/A") &
                 (out["demand_response_view"] == "N/A")).all()):
        fail("metadata-complete", "unsupported metrics explicitly N/A",
             "non-N/A value present")
    if not bool(((out["scenario_type"] == "discount_decrease") &
                 (out["input_form"] == "decrease_pp") &
                 (out["scenario_id"] == scenario_id)).all()):
        fail("metadata-decrease", "decrease metadata consistent with input",
             scenario_id)
    if not bool(((out["stated_decrease_pp"] == decrease)).all()):
        fail("metadata-decrease", "stated decrease recorded on every row",
             f"{decrease}")
    record("metadata", "scenario metadata and assumption lineage complete",
           "all lineage columns populated", scenario_id)
    record("metadata-decrease", "decrease scenario identity consistent",
           "discount_decrease / decrease_pp / id matches filename",
           scenario_id)
    out["_sort"] = out["band"].map(
        {b: i for i, b in enumerate(BAND_ORDER + ["TOTAL"])})
    out = out.sort_values("_sort").drop(columns=["_sort"]).reset_index(drop=True)

    # ---- frozen inputs unchanged --------------------------------------------------
    if sha256(LINE_CSV) != line_hash_before:
        fail("frozen-line", "line fact byte-identical after run", "MODIFIED")
    if sha256(ORDER_CSV) != order_hash_before:
        fail("frozen-order", "order fact byte-identical after run", "MODIFIED")
    record("frozen-inputs", "frozen Phase 1/Phase 2 files unchanged",
           "byte-identical SHA-256 before/after", "unchanged")

    # ---- write outputs (only after every check above has passed) -------------------
    OUT_CSV = OUT_DIR / f"phase4b_scenario_decrease_{decrease:.2f}.csv"
    QUALITY_JSON = OUT_DIR / f"phase4b_scenario_decrease_{decrease:.2f}_quality.json"
    if QUARANTINE_COL in out.columns:
        fail("quarantine-output", f"{QUARANTINE_COL} absent from output",
             "column present")
    out.to_csv(OUT_CSV, index=False, encoding="utf-8")
    report = {
        "phase": "4B decrease slice — uniform discount-decrease scenario "
                 "(hypothetical arithmetic sensitivity; not a forecast)",
        "scenario": {
            "scenario_id": scenario_id,
            "scenario_type": "discount_decrease",
            "input_form": "decrease_pp",
            "stated_decrease_pp": decrease,
            "decrease_bounds": [DECREASE_MIN, DECREASE_MAX],
            "dprime_bounds": [DPRIME_MIN, DPRIME_MAX],
            "scope": "all_valid_lines",
            "quantity_assumption": "CONSTANT_OBSERVED_QUANTITY",
            "cogs_method": "FROZEN_MODELED_COGS_PCT",
            "freight_method": "OBSERVED_PASSTHROUGH",
            "return_support": "OFF",
            "reporting": "Order x Discount Band (baseline bands), ORDER basis",
            "standing": STANDING,
        },
        "inputs": {
            "fact_margin_map_phase2.csv": {"rows": len(e),
                                           "sha256": line_hash_before},
            "order_margin_map_phase2.csv": {"rows": len(o),
                                            "sha256": order_hash_before},
        },
        "checks": checks,
        "outputs": {OUT_CSV.name: {"rows": int(len(out)),
                                   "columns": int(len(out.columns)),
                                   "sha256": sha256(OUT_CSV)}},
    }
    with open(QUALITY_JSON, "w", encoding="utf-8") as fh:
        json.dump(report, fh, indent=2)
        fh.write("\n")

    print(f"OK: scenario {scenario_id} ({len(out)} band rows) -> {OUT_CSV}")
    print(f"OK: baseline contrib={tp:,.4f} | hypo contrib="
          f"{float(trow['hypo_contrib']):,.4f} | "
          f"variance={float(trow['variance_contribution_profit']):,.4f}")
    print(f"OK: {len([c for c in checks if c['status'] == 'PASS'])}/"
          f"{len(checks)} checks PASS")


if __name__ == "__main__":
    try:
        main()
    except SystemExit as exc:
        print(str(exc), file=sys.stderr)
        raise
