"""MarginMap Phase 4C (slice 1) — AO-01 Baseline TOTAL Performance Summary.

Scope (per docs/PHASE_4C_ANALYTICAL_INTERPRETATION_DESIGN.md, AO-01):
  ONE observed-baseline TOTAL summary. No bands, no scenarios, no order
  detail, no visuals, no forecasts, no causal claims. Every figure below
  is an observed historical fact, a derived reference, or a modeled
  estimate conditional on the frozen benchmark structure, with
  return/support OFF (zero means scenario-excluded, never actual cost).

Inputs (READ-ONLY — never modified, never regenerated by this script):
    data/processed/fact_margin_map_phase2.csv   (line grain, 9,994 rows)
    data/processed/order_margin_map_phase2.csv  (order grain, 5,009 rows;
                                                 authoritative contribution)
    data/processed/discount_band_summary.csv    (ORDER TOTAL row used as an
                                                 independent cross-check only)

Outputs (NEW files only; written after every validation check passes):
    data/processed/phase4c_baseline_total.csv
    data/processed/phase4c_baseline_total_quality.json

Usage (all paths have frozen defaults; overrides exist ONLY so that
missing/invalid-input behavior can be tested without touching frozen files):
    python src/data/build_phase4c_baseline_summary.py

Formulas (frozen Phase 1A definitions restated — not redefined):
    net_revenue(line)      = sales (authoritative; discount already applied)
    gross_revenue(line)    = sales / (1 - discount)   [derived reference]
    discount_amount        = gross - net              [revenue forgone]
    wad                    = SUM(discount_amount) / SUM(gross)
                             (dual: 1 - SUM(net)/SUM(gross), reconciled)
    modeled_cogs(line)     = sales * modeled_cogs_pct / 100 (frozen pct)
    contribution(order)    = order_revenue - order_cogs - order_freight
                             (return/support OFF; authoritative order fact)
    margins                = SUM/SUM on net revenue; changes in pp (n/a here)
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
LINE_CSV = ROOT / "data" / "processed" / "fact_margin_map_phase2.csv"
ORDER_CSV = ROOT / "data" / "processed" / "order_margin_map_phase2.csv"
BAND_CSV = ROOT / "data" / "processed" / "discount_band_summary.csv"
OUT_DIR = ROOT / "data" / "processed"
OUT_CSV_NAME = "phase4c_baseline_total.csv"
OUT_JSON_NAME = "phase4c_baseline_total_quality.json"

# ---- frozen baseline expectations (Phase 1 / Phase 2 / Phase 3B records) ----
EXPECTED_LINES = 9994
EXPECTED_ORDERS = 5009
EXPECTED_QTY = 37873
EXPECTED_REV = 2297200.8603
EXPECTED_COGS = 1493910.1285
EXPECTED_FREIGHT = 238173.79
EXPECTED_CONTRIB = 565116.9418
EXPECTED_WAD = 0.197887  # ORDER TOTAL row (overall 0.1979)
EXPECTED_CONTRIB_MARGIN = 24.600241  # ORDER TOTAL row (overall 24.6002%)
EXPECTED_NEG_ORDERS = 50
EXPECTED_RETURN_YES = 296
EXPECTED_RETURN_UNKNOWN = 1
EXPECTED_NULL_FREIGHT_LINES = 2
TOL = 0.05  # currency tolerance for source-total reconciliation only
DUAL_TOL = 1e-6  # dual-form / identity reconciliation tolerance
MARGIN_TOL = 1e-6  # SUM/SUM margin reconciliation tolerance

# ---- frozen input hashes (all prior freeze records) --------------------------
FROZEN_HASHES = {
    "fact_margin_map_phase2.csv":
        "4c471feeda642e5ecbd2263782b4fc0f1655962f6c6488bdfe47886df2f01cb1",
    "order_margin_map_phase2.csv":
        "ae6c349c9995747f2fef91cf1db6b940a73d99d6b2fede5ff3dff918f429d267",
    "fact_sales_cogs.csv":
        "4d8de717486b323ffb656d13c94fd6bd94f8e61d1a93ea339a602ab5303b9988",
}

QUARANTINE_COL = "source_profit_quarantined"
OUTPUT_NAME = "Baseline performance summary (TOTAL)"
SCENARIO_STATUS = "OBSERVED BASELINE"
GRAIN = "TOTAL"


def fail(check: str, expected: str, actual: str) -> "NoReturn":
    raise SystemExit(
        f"VALIDATION FAILED [{check}]\n  Expected: {expected}\n  Actual:   {actual}"
    )


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Phase 4C slice 1: AO-01 baseline TOTAL summary.")
    p.add_argument("--line-csv", type=Path, default=LINE_CSV)
    p.add_argument("--order-csv", type=Path, default=ORDER_CSV)
    p.add_argument("--band-csv", type=Path, default=BAND_CSV)
    p.add_argument("--out-dir", type=Path, default=OUT_DIR)
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    line_csv, order_csv, band_csv = args.line_csv, args.order_csv, args.band_csv
    out_dir = args.out_dir

    # ---- 1. source-artifact identity (fail-loud before any I/O beyond this) --
    for label, path in (("line fact", line_csv), ("order fact", order_csv),
                        ("band summary", band_csv)):
        if not path.is_file():
            fail("inputs-exist", f"{label} present at {path}", "file missing")

    line_hash = sha256(line_csv)
    order_hash = sha256(order_csv)
    if line_hash != FROZEN_HASHES["fact_margin_map_phase2.csv"]:
        fail("frozen-inputs", FROZEN_HASHES["fact_margin_map_phase2.csv"],
             line_hash)
    if order_hash != FROZEN_HASHES["order_margin_map_phase2.csv"]:
        fail("frozen-inputs", FROZEN_HASHES["order_margin_map_phase2.csv"],
             order_hash)

    # ---- 2. load (quarantined Profit never enters a working frame) ------------
    line_cols = [c for c in pd.read_csv(line_csv, nrows=0).columns
                 if c != QUARANTINE_COL]
    if QUARANTINE_COL not in pd.read_csv(line_csv, nrows=0).columns:
        fail("quarantine", f"{QUARANTINE_COL} present-but-excluded",
             "quarantine column missing from input")
    lines = pd.read_csv(line_csv, usecols=line_cols)
    orders = pd.read_csv(order_csv)
    bands = pd.read_csv(band_csv)
    if QUARANTINE_COL in lines.columns or QUARANTINE_COL in orders.columns:
        fail("quarantine", f"{QUARANTINE_COL} never loaded",
             "quarantine column in working frame")

    # ---- 3. shapes ------------------------------------------------------------
    if len(lines) != EXPECTED_LINES:
        fail("inputs", f"{EXPECTED_LINES} lines", f"{len(lines)} lines")
    if len(orders) != EXPECTED_ORDERS or orders["order_id"].nunique() != EXPECTED_ORDERS:
        fail("inputs", f"{EXPECTED_ORDERS} unique orders",
             f"{len(orders)} rows / {orders['order_id'].nunique()} unique")

    # ---- 4. scenarios OFF ------------------------------------------------------
    for col in ("return_processing_scenario_enabled", "support_scenario_enabled"):
        if bool(lines[col].fillna(False).any()):
            fail("scenarios-off", f"{col} all FALSE", "TRUE found")
    for col in ("return_processing_cost_scenario", "support_cost_scenario"):
        if float(lines[col].fillna(0).abs().sum()) != 0.0:
            fail("scenarios-off", f"{col} all 0", "nonzero found")

    # ---- 5. observed discount range --------------------------------------------
    if lines["discount"].isna().any():
        fail("discount-range", "[0, 1); no NULL", "NULL discount found")
    dmin, dmax = float(lines["discount"].min()), float(lines["discount"].max())
    if not (0 <= dmin and dmax < 1):
        fail("discount-range", "[0, 1)", f"[{dmin}, {dmax}]")

    # ---- 6. quantity ------------------------------------------------------------
    qty = int(lines["quantity"].sum())
    if qty != EXPECTED_QTY:
        fail("quantity-constant", str(EXPECTED_QTY), str(qty))

    # ---- 7. authoritative TOTALs from the order fact -----------------------------
    rev = float(orders["order_revenue"].sum())
    cogs = float(orders["order_cogs"].sum())
    freight = float(orders["order_freight"].sum())
    contrib = float(orders["order_contribution_profit"].sum())
    if abs(rev - EXPECTED_REV) > TOL:
        fail("frozen", f"revenue {EXPECTED_REV} +/- {TOL}", repr(rev))
    if abs(cogs - EXPECTED_COGS) > TOL:
        fail("frozen", f"COGS {EXPECTED_COGS} +/- {TOL}", repr(cogs))
    if abs(freight - EXPECTED_FREIGHT) > TOL:
        fail("frozen", f"freight {EXPECTED_FREIGHT} +/- {TOL}", repr(freight))
    if abs(contrib - EXPECTED_CONTRIB) > TOL:
        fail("frozen", f"contribution {EXPECTED_CONTRIB} +/- {TOL}", repr(contrib))
    contrib_margin = contrib / rev * 100
    if abs(contrib_margin - EXPECTED_CONTRIB_MARGIN) > MARGIN_TOL:
        fail("frozen", f"margin {EXPECTED_CONTRIB_MARGIN} +/- {MARGIN_TOL}",
             repr(contrib_margin))
    gross_profit = rev - cogs
    gross_margin = gross_profit / rev * 100

    # ---- 8. COGS-percentage identity (frozen revenue-based rule) ------------------
    cogs_gap = float(
        (lines["modeled_cogs"] - lines["sales"] * lines["modeled_cogs_pct"] / 100
         ).abs().max())
    if cogs_gap > DUAL_TOL:
        fail("cogs-reconcile", f"max identity gap <= {DUAL_TOL}", repr(cogs_gap))
    if abs(float(lines["modeled_cogs"].sum()) - cogs) > TOL:
        fail("cogs-reconcile", "line COGS sums to order COGS",
             repr(float(lines["modeled_cogs"].sum())))

    # ---- 9. gross / WAD recomputation (dual-form) ----------------------------------
    gross_line = lines["sales"] / (1 - lines["discount"])
    gross = float(gross_line.sum())
    disc = float(gross - float(lines["sales"].sum()))
    wad = float(disc / gross)
    wad_dual = float(1 - float(lines["sales"].sum()) / gross)
    if abs(wad - wad_dual) > DUAL_TOL:
        fail("wad", f"dual gap <= {DUAL_TOL}", repr(abs(wad - wad_dual)))
    if abs(wad - EXPECTED_WAD) > 1e-6:
        fail("wad", f"WAD {EXPECTED_WAD} +/- 1e-6", repr(wad))
    realization = (1 - wad) * 100

    # ---- 10. freight NULL preservation / ambiguity ----------------------------------
    null_mask = lines["freight_cost_observed"].isna()
    null_n = int(null_mask.sum())
    if null_n != EXPECTED_NULL_FREIGHT_LINES:
        fail("ambiguity", f"{EXPECTED_NULL_FREIGHT_LINES} NULL freight lines",
             str(null_n))
    amb_orders = lines.loc[null_mask, "order_id"].unique().tolist()
    if len(amb_orders) != 1:
        fail("ambiguity", "NULLs in exactly one order", repr(amb_orders))

    # ---- 11. ORDER TOTAL cross-check (independent artifact, read-only) --------------
    required_band_cols = {"basis", "band", "net_revenue", "gross_revenue",
                          "discount_amount", "wad", "freight_cost",
                          "contribution_profit", "contribution_margin_pct",
                          "neg_contribution_orders"}
    if not required_band_cols.issubset(set(bands.columns)):
        fail("band-total-crosscheck", f"band columns {sorted(required_band_cols)}",
             f"columns {list(bands.columns)}")
    total_rows = bands[(bands["basis"] == "ORDER") & (bands["band"] == "TOTAL")]
    if len(total_rows) != 1:
        fail("band-total-crosscheck", "exactly one ORDER TOTAL row",
             f"{len(total_rows)} rows")
    t = total_rows.iloc[0]
    for label, actual, expected in (
            ("net", float(t["net_revenue"]), rev),
            ("gross", float(t["gross_revenue"]), gross),
            ("discount", float(t["discount_amount"]), disc),
            ("freight", float(t["freight_cost"]), freight),
            ("contribution", float(t["contribution_profit"]), contrib)):
        if abs(actual - expected) > TOL:
            fail("band-total-crosscheck", f"TOTAL {label} reconciles",
                 f"band={actual!r} recomputed={expected!r}")
    if abs(float(t["wad"]) - wad) > 1e-6:
        fail("band-total-crosscheck", "TOTAL WAD reconciles", repr(float(t["wad"])))
    if abs(float(t["contribution_margin_pct"]) - contrib_margin) > MARGIN_TOL:
        fail("band-total-crosscheck", "TOTAL margin reconciles",
             repr(float(t["contribution_margin_pct"])))

    # ---- 12. negative-contribution orders (order grain, authoritative) ---------------
    neg_orders = int((orders["order_contribution_profit"] < 0).sum())
    if neg_orders != EXPECTED_NEG_ORDERS:
        fail("negatives", str(EXPECTED_NEG_ORDERS), str(neg_orders))
    if int(float(t["neg_contribution_orders"])) != neg_orders:
        fail("negatives", "band TOTAL count matches order fact",
             repr(float(t["neg_contribution_orders"])))

    # ---- 13. return-status cohorts (filter context only) ------------------------------
    rc = orders["order_return_status"].value_counts(dropna=False)
    n_yes = int(rc.get("YES", 0))
    n_unk = int(rc.get("UNKNOWN", 0))
    n_not = int(rc.get("NOT_RETURNED", 0))
    if n_yes != EXPECTED_RETURN_YES or n_unk != EXPECTED_RETURN_UNKNOWN:
        fail("return-cohorts",
             f"YES {EXPECTED_RETURN_YES} / UNKNOWN {EXPECTED_RETURN_UNKNOWN}",
             f"YES {n_yes} / UNKNOWN {n_unk}")
    if n_yes + n_unk + n_not != EXPECTED_ORDERS:
        fail("return-cohorts", f"cohorts sum to {EXPECTED_ORDERS}",
             str(n_yes + n_unk + n_not))

    # ---- 14. build deterministic metric table ------------------------------------------
    L = "fact_margin_map_phase2.csv"
    O = "order_margin_map_phase2.csv"
    B = "discount_band_summary.csv (ORDER TOTAL cross-check)"
    rows: list[dict[str, str]] = []

    def add(metric: str, value: object, unit: str, source: str,
            definition_ref: str, limitation: str) -> None:
        if isinstance(value, float):
            sval = repr(value)
        else:
            sval = str(value)
        rows.append({
            "output_name": OUTPUT_NAME,
            "scenario_status": SCENARIO_STATUS,
            "grain": GRAIN,
            "source_artifact": source,
            "metric_name": metric,
            "metric_value": sval,
            "unit": unit,
            "definition_ref": definition_ref,
            "limitation": limitation,
        })

    add("net_revenue", rev, "CUR", O,
        "FINANCIAL_MODEL.md S4.1 (Net Revenue = Sales); metric dictionary: Net revenue",
        "Authoritative; never subtract discount again")
    add("gross_revenue", gross, "CUR", L + "; cross-checked vs " + B,
        "FINANCIAL_MODEL.md S4.2; metric dictionary: Gross revenue",
        "Derived reference only; never an observed list price")
    add("discount_amount", disc, "CUR", L + "; cross-checked vs " + B,
        "FINANCIAL_MODEL.md S4.3; metric dictionary: Discount amount",
        "Revenue forgone, not profit loss")
    add("modeled_cogs", cogs, "CUR", O + "; line identity vs " + L,
        "Phase 1C-3 revenue-based rule (sales x modeled_cogs_pct / 100); metric dictionary: Modeled COGS",
        "Analytical estimate conditional on benchmarks; not accounting COGS")
    add("modeled_gross_profit", gross_profit, "CUR", O,
        "FINANCIAL_MODEL.md (Gross Profit = Net Revenue - COGS)",
        "Excludes serve costs; not contribution")
    add("modeled_gross_margin_pct", gross_margin, "PCT", O,
        "SUM/SUM on net revenue; NULL/blank if net = 0",
        "Conditional on benchmarks; within-group constancy by construction")
    add("freight_cost", freight, "CUR", O + "; NULLs preserved in " + L,
        "Observed Dataset 1-US join; metric dictionary: Freight cost",
        "Observed field, methodology unverified (Phase 2 caveat)")
    add("cost_to_serve", freight, "CUR", O,
        "order_freight + 0 + 0 (return/support OFF)",
        "Zero means scenario-excluded, never actual cost")
    add("contribution_profit", contrib, "CUR", O + "; cross-checked vs " + B,
        "Waterfall on authoritative order fact; metric dictionary: Contribution profit",
        "Authoritative at order grain and above; conditional on benchmarks with return/support OFF")
    add("contribution_margin_pct", contrib_margin, "PCT", O + "; cross-checked vs " + B,
        "SUM/SUM on net revenue; metric dictionary: Contribution margin %",
        "Denominator net revenue, never gross")
    add("wad", wad, "DEC", L + "; cross-checked vs " + B,
        "SUM(discount_amount)/SUM(gross), dual reconciled; metric dictionary: WAD",
        "Never an arithmetic mean of rates")
    add("revenue_realization_rate", realization, "PCT", L + "; cross-checked vs " + B,
        "SUM(net)/SUM(gross) x 100; metric dictionary: Revenue realization rate",
        "Complement of discount absorption")
    add("quantity", EXPECTED_QTY, "CT", L,
        "Source field quantity, SUM; metric dictionary: Quantity",
        "Volume co-occurrence context; reused bit-identical in scenarios")
    add("order_count", EXPECTED_ORDERS, "CT", O,
        "DISTINCT order_id; metric dictionary: Order count",
        "Sample-size companion")
    add("line_count", EXPECTED_LINES, "CT", L,
        "COUNT row_id; metric dictionary: Line count",
        "Sample-size companion")
    add("neg_contribution_orders", neg_orders, "CT", O + "; cross-checked vs " + B,
        "Orders with order_contribution_profit < 0; metric dictionary: Negative-contribution flags/counts",
        "Order grain only; line-level partials excluded by grain rule; conditional on OFF baseline")
    add("return_yes_orders", n_yes, "CT", O,
        "order_return_status cohort count (filter context only)",
        "Filter flag only; identifies no returned line")
    add("return_unknown_orders", n_unk, "CT", O,
        "order_return_status cohort count, never defaulted",
        "Retained as UNKNOWN")
    add("return_not_returned_orders", n_not, "CT", O,
        "order_return_status cohort count (filter context only)",
        "Conditional on candidate-Returns completeness assumption")
    add("null_freight_lines", null_n, "CT", L,
        "Lines with NULL freight_cost_observed (ambiguity control)",
        "NULL preserved and flagged; 25.05 pair total via order aggregation only")

    out_csv = out_dir / OUT_CSV_NAME
    out_json = out_dir / OUT_JSON_NAME

    # ---- 15. write outputs only after every check passed -------------------------------
    out_dir.mkdir(parents=True, exist_ok=True)
    import csv as _csv
    with open(out_csv, "w", newline="", encoding="utf-8") as f:
        w = _csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    quality = {
        "phase": "4C slice 1 — AO-01 baseline TOTAL performance summary (observed baseline; not a forecast)",
        "output": {
            "output_name": OUTPUT_NAME,
            "scenario_status": SCENARIO_STATUS,
            "grain": GRAIN,
            "standing": "OBSERVED_BASELINE",
        },
        "inputs": {
            "fact_margin_map_phase2.csv": {"rows": len(lines), "sha256": line_hash},
            "order_margin_map_phase2.csv": {"rows": len(orders), "sha256": order_hash},
        },
        "checks": [
            {"id": "inputs-exist", "description": "required frozen inputs present",
             "expected": "line + order + band files", "actual": "present", "status": "PASS"},
            {"id": "frozen-inputs", "description": "frozen hashes match records",
             "expected": "byte-identical SHA-256", "actual": "match", "status": "PASS"},
            {"id": "quarantine", "description": "quarantined Profit excluded",
             "expected": "source_profit_quarantined never loaded", "actual": "excluded", "status": "PASS"},
            {"id": "inputs", "description": "frozen input shapes",
             "expected": "9994 lines / 5009 unique orders",
             "actual": f"{len(lines)} lines / {orders['order_id'].nunique()} orders", "status": "PASS"},
            {"id": "scenarios-off", "description": "return/support layers OFF",
             "expected": "all flags FALSE and costs 0", "actual": "OFF confirmed", "status": "PASS"},
            {"id": "discount-range", "description": "observed discounts valid",
             "expected": "[0, 1); no NULL", "actual": f"[{dmin}, {dmax}]", "status": "PASS"},
            {"id": "quantity-total", "description": "quantity reconciles",
             "expected": str(EXPECTED_QTY), "actual": str(qty), "status": "PASS"},
            {"id": "revenue-reconcile", "description": "net revenue reconciles",
             "expected": f"{EXPECTED_REV} +/- {TOL}", "actual": repr(rev), "status": "PASS"},
            {"id": "cogs-reconcile", "description": "modeled COGS reconciles (identity + total)",
             "expected": f"{EXPECTED_COGS} +/- {TOL}; identity gap <= {DUAL_TOL}",
             "actual": f"{cogs!r}; gap {cogs_gap!r}", "status": "PASS"},
            {"id": "freight-reconcile", "description": "freight reconciles",
             "expected": f"{EXPECTED_FREIGHT} +/- {TOL}", "actual": repr(freight), "status": "PASS"},
            {"id": "contribution-reconcile", "description": "contribution reconciles",
             "expected": f"{EXPECTED_CONTRIB} +/- {TOL}", "actual": repr(contrib), "status": "PASS"},
            {"id": "margin-reconcile", "description": "SUM/SUM margin reconciles",
             "expected": f"{EXPECTED_CONTRIB_MARGIN} +/- {MARGIN_TOL}",
             "actual": repr(contrib_margin), "status": "PASS"},
            {"id": "wad-reconcile", "description": "WAD dual-form + value reconciles",
             "expected": f"{EXPECTED_WAD} +/- 1e-6; dual gap <= {DUAL_TOL}",
             "actual": f"{wad!r}; dual gap {abs(wad - wad_dual)!r}", "status": "PASS"},
            {"id": "band-total-crosscheck", "description": "ORDER TOTAL row reconciles",
             "expected": "net/gross/discount/freight/contribution/WAD/margin match",
             "actual": "match", "status": "PASS"},
            {"id": "negatives", "description": "negative-contribution order count",
             "expected": str(EXPECTED_NEG_ORDERS), "actual": str(neg_orders), "status": "PASS"},
            {"id": "return-cohorts", "description": "return-status cohorts (context only)",
             "expected": f"YES {EXPECTED_RETURN_YES} / UNKNOWN {EXPECTED_RETURN_UNKNOWN}",
             "actual": f"YES {n_yes} / UNKNOWN {n_unk} / NOT_RETURNED {n_not}", "status": "PASS"},
            {"id": "ambiguity", "description": "ambiguous freight preserved",
             "expected": "2 NULL lines in one order",
             "actual": f"{null_n} lines in {amb_orders[0]}", "status": "PASS"},
            {"id": "grain-consistency", "description": "authoritative order grain; no line partials mixed",
             "expected": "order fact primary; band TOTAL cross-check only",
             "actual": "consistent", "status": "PASS"},
        ],
        "outputs": {
            OUT_CSV_NAME: {"rows": len(rows), "sha256": sha256(out_csv)},
        },
    }
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(quality, f, indent=2)
        f.write("\n")
    # refresh output hash after final newline-stable write
    quality["outputs"][OUT_CSV_NAME]["sha256"] = sha256(out_csv)
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(quality, f, indent=2)
        f.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
