"""MarginMap Phase 4C (slice 3) — AO-03 Scenario Comparison at TOTAL.

Scope (per docs/PHASE_4C_ANALYTICAL_INTERPRETATION_DESIGN.md, AO-03):
  ONE headline arithmetic-sensitivity reading per frozen scenario instance
  beside its identical-scope baseline, at Overall TOTAL only. No bands, no
  order detail, no visuals, no forecasts, no causal claims. Baseline rows
  are observed/modeled facts; hypothetical and variance rows are scenario
  values under stated assumptions (constant quantity, frozen modeled-COGS
  percentages, freight passthrough, return/support OFF).

Inputs (READ-ONLY — never modified, never regenerated by this script):
    data/processed/phase4b_scenario_uniform_0.10.csv  + quality JSON (15/15)
    data/processed/phase4b_scenario_increase_0.00.csv + quality JSON (22/22)
    data/processed/phase4b_scenario_decrease_0.00.csv + quality JSON (22/22)

Outputs (NEW files only; written after every validation check passes):
    data/processed/phase4c_scenario_comparison_total.csv
    data/processed/phase4c_scenario_comparison_total_quality.json

Usage (all paths have frozen defaults; overrides exist ONLY so that
missing/invalid-input behavior can be tested without touching frozen files):
    python src/data/build_phase4c_scenario_comparison.py

Rules (frozen definitions restated — not redefined):
    variance = hypothetical - baseline (reconciled both ways); relative
    variance = variance / baseline x 100, NULL/blank where baseline is zero
    (absolute variance still reported); margin changes in percentage points
    (SUM/SUM margins, never averaged); freight variance exactly 0 by
    passthrough design. Identity slices (0.00) carry zero variances by
    construction (integrity, not economics).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
PROCESSED = ROOT / "data" / "processed"
OUT_DIR = PROCESSED
OUT_CSV_NAME = "phase4c_scenario_comparison_total.csv"
OUT_JSON_NAME = "phase4c_scenario_comparison_total_quality.json"

# ---- frozen instances (Phase 4B freeze records; nothing else is a source) ----
INSTANCES = (
    {"key": "uniform",
     "csv": "phase4b_scenario_uniform_0.10.csv",
     "json": "phase4b_scenario_uniform_0.10_quality.json",
     "scenario_id": "uniform_replace_0.10",
     "scenario_type": "uniform_replacement",
     "input_form": "replacement_rate",
     "stated_col": "stated_rate",
     "stated_value": 0.10,
     "n_checks": 15},
    {"key": "uniform020",
     "csv": "phase4b_scenario_uniform_0.20.csv",
     "json": "phase4b_scenario_uniform_0.20_quality.json",
     "scenario_id": "uniform_replace_0.20",
     "scenario_type": "uniform_replacement",
     "input_form": "replacement_rate",
     "stated_col": "stated_rate",
     "stated_value": 0.20,
     "n_checks": 15},
    {"key": "increase",
     "csv": "phase4b_scenario_increase_0.00.csv",
     "json": "phase4b_scenario_increase_0.00_quality.json",
     "scenario_id": "discount_increase_pp_0.00",
     "scenario_type": "discount_increase",
     "input_form": "increase_pp",
     "stated_col": "stated_increase_pp",
     "stated_value": 0.0,
     "n_checks": 22},
    {"key": "decrease",
     "csv": "phase4b_scenario_decrease_0.00.csv",
     "json": "phase4b_scenario_decrease_0.00_quality.json",
     "scenario_id": "discount_decrease_pp_0.00",
     "scenario_type": "discount_decrease",
     "input_form": "decrease_pp",
     "stated_col": "stated_decrease_pp",
     "stated_value": 0.0,
     "n_checks": 22},
)

# ---- frozen baseline expectations (Phase 1 / Phase 2 freeze records) ---------
EXPECTED_LINES = 9994
EXPECTED_ORDERS = 5009
EXPECTED_QTY = 37873
EXPECTED_REV = 2297200.8603
EXPECTED_COGS = 1493910.1285
EXPECTED_FREIGHT = 238173.79
EXPECTED_CONTRIB = 565116.9418
EXPECTED_MARGIN = 24.600241
EXPECTED_UNIFORM_HYPO = 660523.18
EXPECTED_UNIFORM_VAR = 95406.24
EXPECTED_UNIFORM_PP = 1.03
EXPECTED_UNIFORM020_HYPO = 560667.96
EXPECTED_UNIFORM020_VAR = -4448.98
TOL = 0.05  # currency tolerance for source-total reconciliation only
VAR_TOL = 1e-9  # variance arithmetic reconciliation tolerance
PP_TOL = 0.005  # headline pp cross-check tolerance (design rounds to 2dp)

# ---- frozen fact hashes (chain-of-custody via scenario quality JSONs) ---------
FROZEN_FACT_HASHES = {
    "fact_margin_map_phase2.csv":
        "4038684d113ffee5697a4859991159b630802eb1697c3e12ee59735db5d42e06",
    "order_margin_map_phase2.csv":
        "ae6c349c9995747f2fef91cf1db6b940a73d99d6b2fede5ff3dff918f429d267",
}

OUTPUT_NAME = "Scenario comparison at TOTAL"
GRAIN = "Overall TOTAL"
STATUS_BASE = "OBSERVED BASELINE"
STATUS_HYPO = "HYPOTHETICAL_ARITHMETIC_SENSITIVITY"

REQUIRED_CSV_COLS = {"band", "order_count", "line_count", "quantity",
                     "base_net", "base_disc", "base_cogs", "base_freight",
                     "base_cts", "base_contrib", "hypo_net", "hypo_disc",
                     "hypo_cogs", "hypo_cts", "hypo_contrib",
                     "base_gross_profit", "hypo_gross_profit",
                     "variance_net_revenue", "variance_discount_amount",
                     "variance_cogs", "variance_freight", "variance_cost_to_serve",
                     "variance_contribution_profit", "variance_gross_profit",
                     "base_wad", "hypo_wad", "base_contrib_margin",
                     "hypo_contrib_margin", "margin_change_pp",
                     "base_gross_margin", "hypo_gross_margin",
                     "gross_margin_change_pp", "low_sample_flag", "scenario_id",
                     "scenario_type", "input_form", "scope", "basis",
                     "result_standing", "quantity_assumption", "cogs_method",
                     "freight_method", "return_support", "fixed_unit_cost_view",
                     "fixed_unit_cost_reason", "demand_response_view",
                     "demand_response_reason"}


def fail(check: str, expected: str, actual: str) -> "NoReturn":
    raise SystemExit(
        f"VALIDATION FAILED [{check}]\n  Expected: {expected}\n  Actual:   {actual}"
    )


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Phase 4C slice 3: AO-03 scenario comparison at TOTAL.")
    p.add_argument("--processed-dir", type=Path, default=PROCESSED)
    p.add_argument("--out-dir", type=Path, default=OUT_DIR)
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    proc, out_dir = args.processed_dir, args.out_dir

    # ---- 1. source-artifact identity (fail-loud before any further I/O) --------
    for inst in INSTANCES:
        for label, name in (("scenario CSV", inst["csv"]),
                            ("quality JSON", inst["json"])):
            if not (proc / name).is_file():
                fail("inputs-exist", f"{label} present at {proc / name}",
                     "file missing")

    # ---- 2. quality evidence: counts, PASS status, unique IDs --------------------
    qualities: dict[str, dict] = {}
    for inst in INSTANCES:
        try:
            q = json.loads((proc / inst["json"]).read_text(encoding="utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError) as e:
            fail("quality-status", f"{inst['json']} valid JSON", f"parse error: {e}")
        checks = q.get("checks", [])
        ids = [c.get("id") for c in checks]
        if len(checks) != inst["n_checks"] or len(set(ids)) != len(ids):
            fail("quality-status",
                 f"{inst['json']} {inst['n_checks']}/{inst['n_checks']} unique checks",
                 f"{len(checks)} checks / {len(set(ids))} unique IDs")
        if any(c.get("status") != "PASS" for c in checks):
            bad = [c.get("id") for c in checks if c.get("status") != "PASS"]
            fail("quality-status", f"all {inst['json']} checks PASS",
                 f"non-PASS: {bad}")
        scen = q.get("scenario", {})
        if scen.get("scenario_id") != inst["scenario_id"] or \
                scen.get("scenario_type") != inst["scenario_type"] or \
                scen.get("input_form") != inst["input_form"]:
            fail("identifiers", f"{inst['scenario_id']} / {inst['scenario_type']} / "
                                f"{inst['input_form']}",
                 f"{scen.get('scenario_id')} / {scen.get('scenario_type')} / "
                 f"{scen.get('input_form')}")
        if scen.get("scope") != "all_valid_lines":
            fail("identifiers", "scope all_valid_lines", repr(scen.get("scope")))
        # chain-of-custody: frozen fact hashes recorded in scenario evidence
        for fname, digest in FROZEN_FACT_HASHES.items():
            recorded = q.get("inputs", {}).get(fname, {}).get("sha256")
            if recorded != digest:
                fail("fact-chain", f"{fname} {digest}", repr(recorded))
        qualities[inst["key"]] = q

    # ---- 3. chain integrity: CSV bytes match sha recorded in quality JSON --------
    frames: dict[str, pd.DataFrame] = {}
    for inst in INSTANCES:
        digest = sha256(proc / inst["csv"])
        recorded = qualities[inst["key"]].get("outputs", {}).get(
            inst["csv"], {}).get("sha256")
        if digest != recorded:
            fail("quality-chain", f"{inst['csv']} sha {recorded}", digest)
        frames[inst["key"]] = pd.read_csv(proc / inst["csv"])

    # ---- 4. shapes, schema, quarantine ----------------------------------------------
    totals: dict[str, pd.Series] = {}
    for inst in INSTANCES:
        df = frames[inst["key"]]
        if df.shape != (7, 52):
            fail("shapes", f"{inst['csv']} 7 rows x 52 cols", repr(df.shape))
        if REQUIRED_CSV_COLS - set(df.columns):
            fail("band-schema", f"columns {sorted(REQUIRED_CSV_COLS)}",
                 f"columns {list(df.columns)}")
        if "source_profit_quarantined" in df.columns or "profit" in df.columns:
            fail("quarantine", "no quarantined-Profit column", "profit column present")
        t = df[df["band"] == "TOTAL"]
        if len(t) != 1:
            fail("shapes", f"{inst['csv']} exactly one TOTAL row", f"{len(t)} rows")
        totals[inst["key"]] = t.iloc[0]
        row = totals[inst["key"]]
        if row["scenario_id"] != inst["scenario_id"] or \
                row["scenario_type"] != inst["scenario_type"] or \
                row["input_form"] != inst["input_form"]:
            fail("identifiers", f"TOTAL row {inst['scenario_id']}",
                 repr(row["scenario_id"]))
        if float(row[inst["stated_col"]]) != inst["stated_value"]:
            fail("input-forms", f"{inst['stated_col']} {inst['stated_value']}",
                 repr(row[inst["stated_col"]]))
        if row["basis"] != "ORDER" or row["scope"] != "all_valid_lines":
            fail("identifiers", "basis ORDER / scope all_valid_lines",
                 f"{row['basis']} / {row['scope']}")
        if row["result_standing"] != "HYPOTHETICAL_ARITHMETIC_SENSITIVITY_NOT_A_FORECAST":
            fail("identifiers", "standing HYPOTHETICAL_ARITHMETIC_SENSITIVITY_NOT_A_FORECAST",
                 repr(row["result_standing"]))
        for col, label in (("quantity_assumption", "CONSTANT_OBSERVED_QUANTITY"),
                           ("cogs_method", "FROZEN_MODELED_COGS_PCT"),
                           ("freight_method", "OBSERVED_PASSTHROUGH"),
                           ("return_support", "OFF")):
            if row[col] != label:
                fail("assumption-labels", f"{col} {label}", repr(row[col]))
        if pd.notna(row["fixed_unit_cost_view"]) or \
                row["fixed_unit_cost_reason"] != "COMPARATOR_NOT_IN_INITIAL_BUILD":
            fail("na-markers", "fixed_unit_cost N/A with reason",
                 repr((row["fixed_unit_cost_view"], row["fixed_unit_cost_reason"])))
        if pd.notna(row["demand_response_view"]) or \
                row["demand_response_reason"] != "RESPONSE_NOT_ESTIMATED":
            fail("na-markers", "demand_response N/A with reason",
                 repr((row["demand_response_view"], row["demand_response_reason"])))
        if int(row["quantity"]) != EXPECTED_QTY or \
                int(row["order_count"]) != EXPECTED_ORDERS or \
                int(row["line_count"]) != EXPECTED_LINES:
            fail("counts", f"{EXPECTED_LINES}/{EXPECTED_ORDERS}/{EXPECTED_QTY}",
                 f"{row['line_count']}/{row['order_count']}/{row['quantity']}")

    # ---- 5. baseline identical across instances + frozen ------------------------------
    ref = totals["uniform"]
    for key in ("uniform020", "increase", "decrease"):
        for col in ("base_net", "base_disc", "base_cogs", "base_freight",
                    "base_cts", "base_contrib", "base_gross_profit",
                    "base_wad", "base_contrib_margin", "base_gross_margin"):
            if abs(float(totals[key][col]) - float(ref[col])) > TOL:
                fail("baseline-identical", f"{col} identical across instances",
                     f"{key}={float(totals[key][col])!r} uniform={float(ref[col])!r}")
    for label, actual, expected in (
            ("net", float(ref["base_net"]), EXPECTED_REV),
            ("cogs", float(ref["base_cogs"]), EXPECTED_COGS),
            ("freight", float(ref["base_freight"]), EXPECTED_FREIGHT),
            ("contribution", float(ref["base_contrib"]), EXPECTED_CONTRIB)):
        if abs(actual - expected) > TOL:
            fail("baseline-frozen", f"baseline {label} {expected} +/- {TOL}",
                 repr(actual))

    # ---- 6. variance + margin reconciliation (both ways) ---------------------------------
    CUR_PAIRS = (("variance_net_revenue", "hypo_net", "base_net"),
                 ("variance_discount_amount", "hypo_disc", "base_disc"),
                 ("variance_cogs", "hypo_cogs", "base_cogs"),
                 ("variance_gross_profit", "hypo_gross_profit", "base_gross_profit"),
                 ("variance_contribution_profit", "hypo_contrib", "base_contrib"))
    for inst in INSTANCES:
        row = totals[inst["key"]]
        for var_col, hypo_col, base_col in CUR_PAIRS:
            gap = abs(float(row[var_col]) - (float(row[hypo_col]) - float(row[base_col])))
            if gap > VAR_TOL:
                fail("variance-reconcile",
                     f"{inst['key']} {var_col} hypo-base gap <= {VAR_TOL}", repr(gap))
        if float(row["variance_freight"]) != 0.0:
            fail("freight-zero", "variance_freight exactly 0",
                 repr(float(row["variance_freight"])))
        if float(row["variance_cost_to_serve"]) != 0.0:
            fail("freight-zero", "variance_cost_to_serve exactly 0",
                 repr(float(row["variance_cost_to_serve"])))
        if abs(float(row["hypo_cts"]) - float(row["base_freight"])) > VAR_TOL:
            fail("freight-zero", "hypo_cts = base freight (passthrough)",
                 repr(float(row["hypo_cts"])))
        pp_gap = abs(float(row["margin_change_pp"]) -
                     (float(row["hypo_contrib_margin"]) - float(row["base_contrib_margin"])))
        if pp_gap > VAR_TOL:
            fail("margin-pp", f"{inst['key']} margin_change_pp gap <= {VAR_TOL}",
                 repr(pp_gap))
        gpp_gap = abs(float(row["gross_margin_change_pp"]) -
                      (float(row["hypo_gross_margin"]) - float(row["base_gross_margin"])))
        if gpp_gap > VAR_TOL:
            fail("margin-pp", f"{inst['key']} gross_margin_change_pp gap <= {VAR_TOL}",
                 repr(gpp_gap))

    # ---- 7. headline cross-checks (design rounded figures) ---------------------------------
    urow = totals["uniform"]
    if abs(float(urow["hypo_contrib"]) - EXPECTED_UNIFORM_HYPO) > TOL:
        fail("headline", f"uniform hypo {EXPECTED_UNIFORM_HYPO}",
             repr(float(urow["hypo_contrib"])))
    if abs(float(urow["variance_contribution_profit"]) - EXPECTED_UNIFORM_VAR) > TOL:
        fail("headline", f"uniform variance {EXPECTED_UNIFORM_VAR}",
             repr(float(urow["variance_contribution_profit"])))
    if abs(float(urow["margin_change_pp"]) - EXPECTED_UNIFORM_PP) > PP_TOL:
        fail("headline", f"uniform pp change {EXPECTED_UNIFORM_PP}",
             repr(float(urow["margin_change_pp"])))
    u20 = totals["uniform020"]
    if abs(float(u20["hypo_contrib"]) - EXPECTED_UNIFORM020_HYPO) > TOL:
        fail("headline", f"uniform020 hypo {EXPECTED_UNIFORM020_HYPO}",
             repr(float(u20["hypo_contrib"])))
    if abs(float(u20["variance_contribution_profit"]) - EXPECTED_UNIFORM020_VAR) > TOL:
        fail("headline", f"uniform020 variance {EXPECTED_UNIFORM020_VAR}",
             repr(float(u20["variance_contribution_profit"])))
    for key in ("increase", "decrease"):
        row = totals[key]
        if float(row["variance_contribution_profit"]) != 0.0 or \
                float(row["variance_net_revenue"]) != 0.0 or \
                float(row["margin_change_pp"]) != 0.0:
            fail("headline", f"{key} identity variances zero",
                 repr((float(row["variance_contribution_profit"]),
                       float(row["variance_net_revenue"]),
                       float(row["margin_change_pp"]))))

    # ---- 8. build deterministic metric table (TOTAL only; no band detail) --------------------
    rows: list[dict[str, str]] = []

    def sval(value: object) -> str:
        if value is None:
            return ""
        try:
            if pd.isna(value):
                return ""
        except (TypeError, ValueError):
            return str(value)
        if type(value).__module__ == "numpy":
            value = value.item()
            if value is None:
                return ""
        return repr(value) if isinstance(value, float) else str(value)

    def add(scenario_id: str, block: str, status: str, metric: str,
            value: object, unit: str, source: str, definition_ref: str,
            limitation: str) -> None:
        rows.append({
            "output_name": OUTPUT_NAME,
            "scenario_status": status,
            "grain": GRAIN,
            "scenario_id": scenario_id,
            "block": block,
            "source_artifact": source,
            "metric_name": metric,
            "metric_value": sval(value),
            "unit": unit,
            "definition_ref": definition_ref,
            "limitation": limitation,
        })

    BASE_DEF = "Stored TOTAL baseline beside the identical-scope hypothetical"
    HYPO_DEF = "Stored TOTAL hypothetical under the stated assumptions"
    COND = "Conditional illustration under stated assumptions; not a forecast"
    for inst in INSTANCES:
        row = totals[inst["key"]]
        sid, csv = inst["scenario_id"], inst["csv"]
        base_lim = "Observed/modeled baseline fact; identical scope to hypothetical"
        hypo_lim = ("Hypothetical arithmetic sensitivity (constant quantity, frozen "
                    "COGS pct, freight passthrough, return/support OFF); not a forecast")
        for metric, col, unit, dref in (
                ("net_revenue", "base_net", "CUR", "Net revenue = Sales (authoritative)"),
                ("discount_amount", "base_disc", "CUR", "Discount amount = gross - net"),
                ("modeled_cogs", "base_cogs", "CUR", "Frozen revenue-based modeled COGS"),
                ("gross_profit", "base_gross_profit", "CUR", "Gross profit = net - COGS"),
                ("gross_margin", "base_gross_margin", "PCT", "Gross margin SUM/SUM on net"),
                ("freight_cost", "base_freight", "CUR", "Observed freight passthrough base"),
                ("cost_to_serve", "base_cts", "CUR", "Serve cost = freight + 0 + 0 (OFF)"),
                ("contribution_profit", "base_contrib", "CUR", "Authoritative TOTAL contribution"),
                ("contribution_margin", "base_contrib_margin", "PCT", "Contribution margin SUM/SUM on net"),
                ("wad", "base_wad", "DEC", "WAD gross-weighted; never averaged")):
            add(sid, "baseline", STATUS_BASE, metric, row[col], unit, csv,
                BASE_DEF + "; " + dref, base_lim)
        add(sid, "baseline", STATUS_BASE, "quantity", row["quantity"], "CT", csv,
            BASE_DEF + "; observed quantity, SUM", base_lim + "; reused bit-identical in scenario")
        add(sid, "baseline", STATUS_BASE, "order_count", row["order_count"], "CT", csv,
            BASE_DEF + "; DISTINCT order_id", base_lim)
        add(sid, "baseline", STATUS_BASE, "line_count", row["line_count"], "CT", csv,
            BASE_DEF + "; COUNT row_id", base_lim)
        for metric, col, unit, dref in (
                ("net_revenue", "hypo_net", "CUR", "Hypothetical net under stated d'"),
                ("discount_amount", "hypo_disc", "CUR", "Hypothetical discount absorption"),
                ("modeled_cogs", "hypo_cogs", "CUR", "Hypo net x frozen COGS pct (constancy disclosed)"),
                ("gross_profit", "hypo_gross_profit", "CUR", "Hypothetical gross profit"),
                ("gross_margin", "hypo_gross_margin", "PCT", "Hypothetical gross margin SUM/SUM"),
                ("cost_to_serve", "hypo_cts", "CUR", "Hypo CTS = order freight + 0 + 0"),
                ("contribution_profit", "hypo_contrib", "CUR", "Arithmetic scenario contribution"),
                ("contribution_margin", "hypo_contrib_margin", "PCT", "Scenario margin SUM/SUM"),
                ("wad", "hypo_wad", "DEC", "Hypothetical WAD under stated d'")):
            add(sid, "hypothetical", STATUS_HYPO, metric, row[col], unit, csv,
                HYPO_DEF + "; " + dref, hypo_lim)
        for metric, col, unit, dref in (
                ("net_revenue", "variance_net_revenue", "CUR", "Hypothetical minus baseline"),
                ("discount_amount", "variance_discount_amount", "CUR", "Hypothetical minus baseline"),
                ("modeled_cogs", "variance_cogs", "CUR", "Hypothetical minus baseline"),
                ("gross_profit", "variance_gross_profit", "CUR", "Hypothetical minus baseline"),
                ("contribution_profit", "variance_contribution_profit", "CUR", "Hypothetical minus baseline"),
                ("freight", "variance_freight", "CUR", "Exactly 0 by passthrough design"),
                ("cost_to_serve", "variance_cost_to_serve", "CUR", "Exactly 0 by passthrough design")):
            add(sid, "variance", STATUS_HYPO, "variance_" + metric
                if not metric.startswith("variance") else metric,
                row[col], unit, csv, "Stored variance, reconciled both ways (<=1e-9); " + dref, COND)
        base_contrib = float(row["base_contrib"])
        var_contrib = float(row["variance_contribution_profit"])
        rel = var_contrib / base_contrib * 100 if base_contrib != 0 else None
        add(sid, "variance", STATUS_HYPO, "relative_contribution_variance", rel,
            "PCT", csv,
            "Computed variance/baseline x 100; NULL/blank where baseline is zero",
            COND + "; shown only where baseline nonzero")
        add(sid, "variance", STATUS_HYPO, "margin_change_pp",
            row["margin_change_pp"], "PP", csv,
            "Stored pp change, recomputed hypo minus base (<=1e-9)", COND)
        add(sid, "variance", STATUS_HYPO, "gross_margin_change_pp",
            row["gross_margin_change_pp"], "PP", csv,
            "Stored pp change, recomputed hypo minus base (<=1e-9)", COND)
        add(sid, "variance", STATUS_HYPO, "low_sample_flag",
            str(bool(row["low_sample_flag"])), "Flag", csv,
            "Thin-cell marker carried from source TOTAL row",
            "Provisional thresholds; FALSE on all three TOTAL rows")
        add(sid, "variance", STATUS_HYPO, "fixed_unit_cost_view", None, "Label", csv,
            "N/A: COMPARATOR_NOT_IN_INITIAL_BUILD",
            "Marked unavailable with reason; never estimated")
        add(sid, "variance", STATUS_HYPO, "demand_response_view", None, "Label", csv,
            "N/A: RESPONSE_NOT_ESTIMATED",
            "Marked unavailable with reason; never estimated")

    out_csv = out_dir / OUT_CSV_NAME
    out_json = out_dir / OUT_JSON_NAME

    # ---- 9. write outputs only after every check passed --------------------------------------
    out_dir.mkdir(parents=True, exist_ok=True)
    import csv as _csv
    with open(out_csv, "w", newline="", encoding="utf-8") as f:
        w = _csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    quality = {
        "phase": "4C slice 3 — AO-03 scenario comparison at TOTAL (arithmetic sensitivity; not a forecast)",
        "output": {
            "output_name": OUTPUT_NAME,
            "grain": GRAIN,
            "scenario_status": "BASELINE_BESIDE_HYPOTHETICAL",
            "standing": "HYPOTHETICAL_ARITHMETIC_SENSITIVITY_NOT_A_FORECAST",
        },
        "inputs": {
            inst["csv"]: {"rows": 7, "columns": 52,
                          "sha256": sha256(proc / inst["csv"]),
                          "scenario_id": inst["scenario_id"]}
            for inst in INSTANCES
        },
        "evidence": {
            inst["json"]: {"checks": inst["n_checks"], "status": "all PASS",
                           "scenario_id": inst["scenario_id"]}
            for inst in INSTANCES
        },
        "checks": [
            {"id": "inputs-exist", "description": "4 scenario CSVs + 4 quality JSONs present",
             "expected": "8 files", "actual": "present", "status": "PASS"},
            {"id": "quality-status", "description": "frozen quality evidence all PASS, unique IDs",
             "expected": "15/15 + 15/15 + 22/22 + 22/22 unique",
             "actual": "15/15 + 15/15 + 22/22 + 22/22 unique", "status": "PASS"},
            {"id": "quality-chain", "description": "CSV bytes match sha recorded in quality JSON",
             "expected": "4/4 match", "actual": "4/4 match", "status": "PASS"},
            {"id": "fact-chain", "description": "fact hashes in scenario evidence match freeze records",
             "expected": "2 facts x 4 evidence files match", "actual": "match", "status": "PASS"},
            {"id": "identifiers", "description": "scenario_id/type/scope/basis/standing per instance",
             "expected": "uniform_replace_0.10 / uniform_replace_0.20 / discount_increase_pp_0.00 / discount_decrease_pp_0.00; ORDER; all_valid_lines",
             "actual": "match", "status": "PASS"},
            {"id": "input-forms", "description": "stated input form + value per instance",
             "expected": "replacement_rate 0.10; replacement_rate 0.20; increase_pp 0.0; decrease_pp 0.0",
             "actual": "match", "status": "PASS"},
            {"id": "shapes", "description": "scenario file shapes + TOTAL row",
             "expected": "7 rows x 52 cols x 4 files; one TOTAL each",
             "actual": "match", "status": "PASS"},
            {"id": "band-schema", "description": "required TOTAL columns present",
             "expected": "all required columns", "actual": "present", "status": "PASS"},
            {"id": "quarantine", "description": "no quarantined-Profit column",
             "expected": "absent from all 4 CSVs", "actual": "absent", "status": "PASS"},
            {"id": "assumption-labels", "description": "assumption labels on every TOTAL row",
             "expected": "CONSTANT_OBSERVED_QUANTITY / FROZEN_MODELED_COGS_PCT / OBSERVED_PASSTHROUGH / OFF",
             "actual": "match", "status": "PASS"},
            {"id": "na-markers", "description": "unlicensed views N/A with reasons",
             "expected": "COMPARATOR_NOT_IN_INITIAL_BUILD / RESPONSE_NOT_ESTIMATED",
             "actual": "match", "status": "PASS"},
            {"id": "counts", "description": "universal scope counts per TOTAL",
             "expected": "9994 / 5009 / 37873 x 4", "actual": "match", "status": "PASS"},
            {"id": "baseline-identical", "description": "baseline blocks identical across instances",
             "expected": "10 baseline columns match within 0.05", "actual": "identical", "status": "PASS"},
            {"id": "baseline-frozen", "description": "baseline TOTAL equals frozen baseline",
             "expected": "2297200.8603 / 1493910.1285 / 238173.79 / 565116.9418",
             "actual": "match", "status": "PASS"},
            {"id": "variance-reconcile", "description": "stored variances equal hypo-base",
             "expected": "5 currency pairs x 4 instances, gaps <= 1e-9",
             "actual": "reconciled", "status": "PASS"},
            {"id": "freight-zero", "description": "freight variance exactly 0; CTS passthrough",
             "expected": "0.0 x 4; hypo_cts = base freight", "actual": "zero", "status": "PASS"},
            {"id": "margin-pp", "description": "stored pp changes equal recomputed",
             "expected": "2 pp pairs x 4 instances, gaps <= 1e-9", "actual": "recomputed", "status": "PASS"},
            {"id": "headline", "description": "headline figures match design (+ identities zero)",
             "expected": "hypo 660523.18 / var 95406.24 / +1.03pp; uniform020 hypo 560667.96 / var -4448.98; identities 0.0",
             "actual": "match", "status": "PASS"},
            {"id": "grain", "description": "TOTAL-only output; no band detail emitted",
             "expected": "4 instances x 3 blocks, TOTAL grain", "actual": "TOTAL only", "status": "PASS"},
        ],
        "limitations": [
            "Identity slices show zero variance by construction (integrity, not economics).",
            "Nonzero universal pp shifts have no valid output and do not appear here.",
            "LINE-basis scenario detail is not licensed.",
            "Conditional illustration under stated assumptions; not a forecast.",
        ],
        "failure_behavior": [
            "Missing file fails [inputs-exist] before any further I/O.",
            "Non-PASS or malformed quality evidence fails [quality-status].",
            "CSV/evidence sha mismatch fails [quality-chain] before loading.",
            "Wrong schema fails [band-schema]; any failed check writes no outputs.",
        ],
        "determinism": "Fixed instance/block/metric ordering, repr() numeric formatting, no timestamps, no randomness, no environment-dependent values.",
        "outputs": {
            OUT_CSV_NAME: {"rows": len(rows), "sha256": sha256(out_csv)},
        },
    }
    with open(out_json, "w", encoding="utf-8", newline="\n") as f:
        json.dump(quality, f, indent=2)
        f.write("\n")
    quality["outputs"][OUT_CSV_NAME]["sha256"] = sha256(out_csv)
    with open(out_json, "w", encoding="utf-8", newline="\n") as f:
        json.dump(quality, f, indent=2)
        f.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
